### ISSUE TITLE
Build on win 10 with mingw64 gcc9.1.0 Error 2

### ISSUE THREAD

**Issue by qiu-hao** [copperspice/copperspice#109]
CMakeFiles\CsGui1.5.dir\dialogs\qabstractpagesetupdialog.cpp.obj: too many sections (38664)
 CMakeFiles\CsGui1.5.dir\dialogs\qabstractpagesetupdialog.cpp.obj: 'file too big'

**Comment by agserm** [comment]
Thank you for reporting this issue. Just for reference, here are the platforms and compiler versions we are currently building in CI: https://www.copperspice.com/docs/cs_overview/supported-platforms.html

We are planning to upgrade the supported MinGW version around October.

The issue you are describing is most likely not related to the version of MinGW. Please try adding the following two environment variables, either in your system environment or on the command line:

```
CFLAGS="-Wa,-mbig-obj"
CXXFLAGS="-Wa,-mbig-obj"
```

Please let us know what you find.

**Comment by bgeller** [comment]
Closing due to no reply. Please open a new ticket if you still have concerns.
