### ISSUE TITLE
Update CMakeFiles.txt to modern CMake

### ISSUE THREAD

**Issue by janwilmans** [copperspice/copperspice#111]
Goals: 

- document why options are needed on specific platforms
- centralize platform specific settings such as /INCREMENTAL:NO, /bigobj, or -Wl,-undefined,error
- prevent unneeded dependencies and rebuilding 
- use more maintainable modern cmake constructs

Direction:

- create toolchain files to accommodate platform settings
- prefer target_* such as 'target_link_libraries' and 'target_include_directories' instead of  'link_libraries' or 'include_directories' (the former operate in the target scope in stead of directory scope)

## Notes:

- add_definitions / remove_definitions apply directory-structure wide options, this is rarely useful, but there is one special use case where it is very nice; when you want to add an option to _all_  targets but have one or more  points in the directory structure where the option should be _recursively_ _not_ applied.

## Structure

- use project to declare a project name
- use ${PROJECT_NAME} to refer to it from that point on (DRY)
- multiple projects can be in one CMakeLists.txt
- keep target_link_libraries PRIVATE for shared libraries unless the client needs to know about them (eg when types are used on the library interface.)
- keep target_link_libraries PUBLIC for static libraries so the client automatically links to the correct dependencies. (DRY)

```
project(LibraryName)

add_library(${PROJECT_NAME}
   src/foo.cpp
   src/bar.cpp
)

target_link_libraries(${PROJECT_NAME}
    PUBLIC
        <dependency>
        <dependency>
)
target_include_directories(${PROJECT_NAME} PUBLIC include_dir)

```

## References

https://cliutils.gitlab.io/modern-cmake/

**Comment by bgeller** [comment]
Minimum CMake has been updated to Version 3.8 and all of the CopperSpice build files have been modernized.  Functions to install libraries have been improved and streamlined.
