### ISSUE TITLE
add a .clang-format and .editorconfig file 

### ISSUE THREAD

**Issue by janwilmans** [copperspice/copperspice#112]
I propose to define a consistent white space style.

This begins with tabs/spaces/indent width, [.editorconfig ](https://editorconfig.org/) is a standard supported by many editors and IDEs. It allows to specify whether tabs or spaces are used per file-type and per directory. The editor will automatically switch based on the presence of the editorconfig file at a certains directory level.

I propose we add at least one editorconfig file at the top level that defines what indent width we use and whether or not we use tabs.

My suggestion would be to eliminate tabs all together in favor of spaces.
In my experience, there are some file types that do not allow the use of tabs, such as .rc (resource files). Also there are diff-tools (such as the one build into gitlab) that dont allow you to specify the tab-width and render it as 8 spaces).

In contrast:
- I have never encountered any file format that requires the use of tabs
- If only spaces are used the tab-behavior or settings of any tool is irrelevant

Here is a sample .editorconfig file:
```
# top-most EditorConfig file
root = true

[*]
trim_trailing_whitespace = true
insert_final_newline = true
end_of_line = lf
charset = latin1

[*.cpp]
indent_style = space
indent_size = 3

[*.h]
indent_style = space
indent_size = 3

[*.rc]
indent_style = space
indent_size = 3

[*.yml]
indent_style = space
indent_size = 3
```

**Comment by bgeller** [comment]
We made an attempt to use clang-format a while back and it does not wrap correctly for most of the code base.  We have used astyle and run the majority of the code through it. It actually works a lot better for our code base. 

Tabs have all ready been eliminated.  The only place you will see these are in autotools makefiles and they are required and can not be removed.

We settled on an indent of 3 spaces.

**Comment by janwilmans** [comment]
@bgeller : clang-format does not support wrapping/aligning to a fixed column number

**Comment by janwilmans** [comment]
An example `.clang-format` file that approximates our CS style guide

```
# see https://www.copperspice.com/style_guide/source_code_style.html 
# note: options are case-sensitive!

#BasedOnStyle: LLVM
ColumnLimit:  0
IndentWidth:  3
UseTab:       Never
Language:     Cpp
Standard:     Latest
SortIncludes: false

AccessModifierOffset:              -2
AlignAfterOpenBracket:             DontAlign
AlignConsecutiveAssignments:       true
AlignConsecutiveDeclarations:      false
AlignConsecutiveBitFields:         true
AllowAllArgumentsOnNextLine:       false
AllowShortFunctionsOnASingleLine:  None
AlwaysBreakTemplateDeclarations:   Yes
BinPackArguments: true
BreakConstructorInitializers:      BeforeColon
ConstructorInitializerIndentWidth: 3
ContinuationIndentWidth:           12
IndentCaseLabels:                  true

BreakBeforeBraces:       Custom
BraceWrapping:
  AfterClass:            true
  AfterControlStatement: false
  AfterEnum:             false
  AfterFunction:         true
  AfterNamespace:        false
  AfterObjCDeclaration:  true
  AfterStruct:           false
  AfterUnion:            true
  AfterExternBlock:      false
  BeforeCatch:           false
  BeforeElse:            false
  IndentBraces:          false
  SplitEmptyFunction:    true
  SplitEmptyRecord:      false
  SplitEmptyNamespace:   false


FixNamespaceComments:             true
KeepEmptyLinesAtTheStartOfBlocks: true

PenaltyBreakBeforeFirstCallParameter: 10000
PointerAlignment:                 Right

SpaceAfterCStyleCast:             true
SpacesInCStyleCastParentheses:    false

SpaceAfterLogicalNot:             true
SpaceBeforeAssignmentOperators:   true
SpaceBeforeParens:                ControlStatements
SpaceInEmptyParentheses:          false

# needs a separate setting for namespace
SpacesBeforeTrailingComments:     6
SpacesInAngles:                   false
SpacesInParentheses:              false
SpacesInSquareBrackets:           false

#OperandAlignmentStyle:            DontAlign
#AlignOperands                     false
#BinPackParameters: true
```

**Comment by agserm** [comment]
A few things about our styling have changed, refer to the style guide at the bottom of this page: https://www.copperspice.com/code.html
