### ISSUE TITLE
Install From Source Arch Linux. Package nas not in pacman any more.

### ISSUE THREAD

**Issue by agokjr** [copperspice/copperspice#113]
Can't find a module to satisfy "Audio" 

> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking target system type... x86_64-pc-linux-gnu
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking for special C compiler options needed for large files... no
> checking for _FILE_OFFSET_BITS value needed for large files... no
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports the include directive... yes (GNU style)
> checking whether make supports nested variables... yes
> checking how to create a pax tar archive... gnutar
> checking dependency style of gcc... gcc3
> checking how to print strings... printf
> checking for a sed that does not truncate output... /usr/bin/sed
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for fgrep... /usr/bin/grep -F
> checking for ld used by gcc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572864
> checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
> checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... no
> checking how to associate runtime and link libraries... printf %s\n
> checking for ar... ar
> checking for archiver @FILE support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking command to parse /usr/bin/nm -B output from gcc object... ok
> checking for sysroot... no
> checking for a working dd... /usr/bin/dd
> checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
> checking for mt... no
> checking if : is a manifest tool... no
> checking how to run the C preprocessor... gcc -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if gcc supports -fno-rtti -fno-exceptions... no
> checking for gcc option to produce PIC... -fPIC -DPIC
> checking if gcc PIC flag -fPIC -DPIC works... yes
> checking if gcc static flag -static works... yes
> checking if gcc supports -c -o file.o... yes
> checking if gcc supports -c -o file.o... (cached) yes
> checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> checking for windres... no
> checking for gcc option to accept ISO C99... none needed
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking dependency style of g++... gcc3
> checking how to run the C++ preprocessor... g++ -E
> checking for ld used by g++... /usr/bin/ld -m elf_x86_64
> checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
> checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking for g++ option to produce PIC... -fPIC -DPIC
> checking if g++ PIC flag -fPIC -DPIC works... yes
> checking if g++ static flag -static works... yes
> checking if g++ supports -c -o file.o... yes
> checking if g++ supports -c -o file.o... (cached) yes
> checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking dynamic linker characteristics... (cached) GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking for g++... g++
> checking whether we are using the GNU Objective C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking dependency style of g++... gcc3
> checking whether g++ supports C++14 features with -std=c++14... yes
> checking size of size_t... 8
> checking whether we are using the GNU Objective C++ compiler... (cached) yes
> checking whether g++ accepts -g... (cached) yes
> checking dependency style of g++... (cached) gcc3
> 
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for OPENSSL... yes
> checking for ZLIB... yes
> checking cups/cups.h usability... yes
> checking cups/cups.h presence... yes
> checking for cups/cups.h... yes
> checking features.h usability... yes
> checking features.h presence... yes
> checking for features.h... yes
> checking pthread.h usability... yes
> checking pthread.h presence... yes
> checking for pthread.h... yes
> checking for unistd.h... (cached) yes
> checking dirent.h usability... yes
> checking dirent.h presence... yes
> checking for dirent.h... yes
> checking fcntl.h usability... yes
> checking fcntl.h presence... yes
> checking for fcntl.h... yes
> checking grp.h usability... yes
> checking grp.h presence... yes
> checking for grp.h... yes
> checking pwd.h usability... yes
> checking pwd.h presence... yes
> checking for pwd.h... yes
> checking signal.h usability... yes
> checking signal.h presence... yes
> checking for signal.h... yes
> checking for dlfcn.h... (cached) yes
> checking sys/eventfd.h usability... yes
> checking sys/eventfd.h presence... yes
> checking for sys/eventfd.h... yes
> checking for sys/types.h... (cached) yes
> checking sys/ioctl.h usability... yes
> checking sys/ioctl.h presence... yes
> checking for sys/ioctl.h... yes
> checking sys/ipc.h usability... yes
> checking sys/ipc.h presence... yes
> checking for sys/ipc.h... yes
> checking sys/time.h usability... yes
> checking sys/time.h presence... yes
> checking for sys/time.h... yes
> checking sys/shm.h usability... yes
> checking sys/shm.h presence... yes
> checking for sys/shm.h... yes
> checking sys/socket.h usability... yes
> checking sys/socket.h presence... yes
> checking for sys/socket.h... yes
> checking for sys/stat.h... (cached) yes
> checking sys/wait.h usability... yes
> checking sys/wait.h presence... yes
> checking for sys/wait.h... yes
> checking sys/param.h usability... yes
> checking sys/param.h presence... yes
> checking for sys/param.h... yes
> checking netinet/in.h usability... yes
> checking netinet/in.h presence... yes
> checking for netinet/in.h... yes
> checking for net/if.h... yes
> checking for library containing clock_gettime... none required
> checking for FONTCONFIG... yes
> checking for GLIB... yes
> checking for GSTREAMER... yes
> checking for GSTREAMER_BASE... yes
> checking for GSTREAMER_AUDIO... yes
> checking for GSTREAMER_VIDEO... yes
> checking for GSTREAMER_APP... yes
> checking for GTK... yes
> checking for ALSA... yes
> checking for PULSEAUDIO... yes
> checking for PULSEAUDIO_DEVICE_MANAGER... yes
> checking for PULSEAUDIO_MAINLOOP_GLIB... yes
> checking for xcb/xkb.h... yes
> checking for LIB_XCB... yes
> checking for LIB_ICCCM... yes
> checking for LIB_IMAGE... yes
> checking for LIB_KEYSYMS... yes
> checking for LIB_RANDR... yes
> checking for LIB_RENDR... yes
> checking for LIB_UTIL... yes
> checking for LIB_SHAPE... yes
> checking for LIB_SHM... yes
> checking for LIB_SYNC... yes
> checking for LIB_XFIXES... yes
> checking for LIB_XKB... yes
> checking for LIB_XKB_COMMON... yes
> checking for LIB_COMMON_X11... yes
> checking for library containing IceOpenConnection... -lICE
> checking for library containing AuOpenServer... no
> checking for library containing glClear... -lGL
> checking for library containing pthread_create... -lpthread
> checking for library containing SmcOpenConnection... -lSM
> checking for library containing XcursorImageCreate... -lXcursor
> checking for library containing XShmCreateImage... -lXext
> checking for library containing XFixesQueryVersion... -lXfixes
> checking for library containing XGetExtensionVersion... -lXi
> checking for library containing XineramaQueryExtension... -lXinerama
> checking for library containing XRRSetScreenConfigAndRate... -lXrandr
> checking for library containing XRenderCreateCursor... -lXrender
> checking for library containing XCreateWindow... -lX11
> ------------------------------------------------------------
> The following headers or libraries are missing and must be installed to build CopperSpice
> Refer to the CS Overview documentation for package names or consult your platform package manager
> Audio
> ------------------------------------------------------------
> 
> CopperSpice configuration aborted

https://aur.archlinux.org/packages/nas/

**Comment by agserm** [comment]
Thank you for your report. Currently, we are using a NAS installation build with the trizen tool. The steps we use to install NAS are as follows:

```
git clone https://aur.archlinux.org/trizen.git &&\
    cd trizen &&\
    makepkg -si --noconfirm --asdeps --needed
trizen -S --noconfirm nas
```

We are investigating our options for Arch Linux, and we may be able to solve this by making the NAS dependency optional in the future.

**Comment by vdeurzen** [comment]
As an addition to the above answer, the `nas` package is available in the Arch User Repository (AUR): https://aur.archlinux.org/packages/nas/

**Comment by agserm** [comment]
Closing this ticket since the package is available in AUR and we do have successful builds on Arch.
