### ISSUE TITLE
Issue in  src/core CMakeLists.txt file

### ISSUE THREAD

**Issue by ShamanTcler** [copperspice/copperspice#118]
line 95 

```
if(ZLIB_FOUND)
   target_link_libraries(CsCore
      PUBLIC
      ${ZLIB_LIBRARIES}
   )

else(ZLIB_FOUND)
```

This just doesn't smell right.

This is CandL by the way ... 

Currently I have Conan in the main CMakeLists ... pulling in the 4 libs ... trying to get the includes correct

**Comment by janwilmans** [comment]
Doesn't it make sense to link to zlib only is it is found?

**Comment by ShamanTcler** [comment]
but isn't this equivalent to:

if(TRUE)
    do ...
else (TRUE)
     do ...

if it were:
if(TRUE)
    do ...
else (NOT TRUE)
     do ...

I would see the value ... am I being stupid here? By the way any day I don't do something stupid is a good day.

**Comment by agserm** [comment]
This is an odd artifact of CMake that is really confusing. The parameter of an `else` block is completely ignored. If it were an `elseif` block, the parameter would be meaningful.

We have removed the extraneous parameter for consistency with our other build files.
