### ISSUE TITLE
Regexp issue

### ISSUE THREAD

**Issue by Sp3EdeR** [copperspice/copperspice#119]
The following line contains the `iter != end() - 1` expression:
https://github.com/copperspice/copperspice/blob/fc354a7063e2ac1cb1337dba03a9623ee4c3e03a/src/core/string/qstring8.cpp#L1096the 

`iter` is an iterator into the `after` `QString8` object, while `end() - 1`is an iterator in the `this` `QString8` object. This makes it an invalid expression. Deleting this subexpression is safe and will have no runtime effect.

**Comment by agserm** [comment]
This should be fixed by 74436f1. Thanks for your report.
