### ISSUE TITLE
Please update 1.6.1 document

### ISSUE THREAD

**Issue by topillar** [copperspice/copperspice#127]
The doc says build copperspice using Mingw need msys.
Since the Autotool is removed, msys is not required anymore, I have tried build using Mingw only with success.
So the doc should be updated.

**Comment by bgeller** [comment]
MSys was not used just for the Autotools build system. There are numerous other utilities which are part of MSys which are extremely useful for development purposes.  If you feel this is not required for your project please feel free to remove it.
