### ISSUE TITLE
Possible a bug of QMenu

### ISSUE THREAD

**Issue by hongnod** [copperspice/copperspice#129]
Following pieces of code works on Qt, with Cs ,it will crash in `exec`
Qt:
```
void PortLinkItem::contextMenuEvent(QGraphicsSceneContextMenuEvent *event)
{
   setSelected(true);
    QMenu menu;
    QAction *moveAction = menu.addAction(QStringLiteral("查看相关电路"));
    QAction *actAction = menu.addAction(QStringLiteral("属性"));
    QAction *selectedAction = menu.exec(event->screenPos());
    if(selectedAction == moveAction) {
        setPos(0, 0);
    }

     Q_UNUSED(actAction)
}
```
Cs:
```
void PortLinkItem::contextMenuEvent(QGraphicsSceneContextMenuEvent *event)
{
   setSelected(true);
    QMenu menu;
    QAction *moveAction = menu.addAction(QString("查看相关电路"));
    QAction *actAction = menu.addAction(QString("属性"));
    QAction *selectedAction = menu.exec(/*event->screenPos()*/);
    /*if(selectedAction == moveAction) {
        setPos(0, 0);
    }*/

     //Q_UNUSED(actAction)
}
```

The whole code is in [CsNetpath](https://github.com/topillar/CsNetpath)

**Comment by janwilmans** [comment]
first thing I notice in your project src/CMakeLists.txt is that this is missing:

```
install(TARGETS topNetpath DESTINATION ${CMAKE_INSTALL_PREFIX})

# Copy the libraries and plugins necessary for our application to our install path.
cs_copy_library(CsCore)
cs_copy_library(CsGui)
cs_copy_library(CsNetwork)
cs_copy_library(CsOpenGL)
cs_copy_library(CsScript)
cs_copy_library(CsSvg)
cs_copy_library(CsXmlPatterns)
cs_copy_library(CsSql)

cs_copy_plugins(CsGui)
```

This add an 'install' target to put all the files in the right place. 
```
> cmake -DCMAKE_INSTALL_PREFIX=install -DMSVC_TOOLSET_VERSION=142 -DCMAKE_BUILD_TYPE=Debug -G Ninja ..`
> ninja install
```

Installs the everything together in one place so its easy to execute. This also integrates well with visual studio.

**Comment by topillar** [comment]
thank you very much！

**Comment by topillar** [comment]
Is this the same thing?
https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-29480

**Comment by bgeller** [comment]
Thanks for the information.  As we post comments we should only show a reference to an issue rather than something which requires a log in.  It is also important to be aware that no issues or code can refer to anything which is not available as an LGPL 2 license.  Since this issue was before 5.7 there were no problems here. 

Barbara

**Comment by agserm** [comment]
Closing this ticket due to no response. Please test with the current branch as UTF8 changes have been implemented.
