### ISSUE TITLE
Is CopperSpice relocatable?

### ISSUE THREAD

**Issue by NeroBurner** [copperspice/copperspice#132]
Qt announced, that Qt 5.14 libraries are relocatable now. Up until to now you can't compile Qt on one machine and copy the installation to another directory and expect everything to work fine

Has a CopperSpice installation hard coded paths? Or is the installation relocatable?

Edit: link to Qt blog: https://www.qt.io/blog/qt-is-relocatable

**Comment by agserm** [comment]
Good question. Yes, a binary build of CopperSpice is fully relocatable. The CMake exports for CopperSpice use a relative path and the executables are built to find the runtime libraries with a relative path. If you run into any issues with relocation please let us know.
