### ISSUE TITLE
Signal/slot mechanism

### ISSUE THREAD

**Issue by bjaraujo** [copperspice/copperspice#133]
First of all congratulations on this project. Seems to address many issues in Qt and to reunite the C++ developers.
I have question about signal/slot mechanism.
Looking at your kitchensink code seems you still use macro based signal/slot mechanism:

connect(grabFrameBufferAct, SIGNAL(triggered()), this, SLOT(grabFrameBuffer()));

https://wiki.qt.io/New_Signal_Slot_Syntax
Is the new also supported? 

I would say even drop old macro system which was a big source of bugs anyway. The string-based SIGNAL and SLOT syntax would only detect type mismatches at runtime.

**Comment by agserm** [comment]
Thanks for asking. Both forms of signal/slot connection syntax are supported in CopperSpice, so we wanted to show both of them in KitchenSink.
