### ISSUE TITLE
C++20 removed std::uncaught_exception

### ISSUE THREAD

**Issue by QuellaZhang** [copperspice/copperspice#134]
std::uncaught_exception was deprecated in C++17 and removed in C++20. In /std:c++17 mode, this triggers a deprecation warning in recent versions of MSVC. In /std:c++latest mode, now that microsoft/STL#380 has been merged, this will trigger an error in VS 2019 16.6 Preview 2.

**The next release msvc toolset will emit the following error under /std:c++latest mode:**
F:\gitP\copperspice\copperspice\src\core\global\qlog.cpp(178): error C2039: 'uncaught_exception': is not a member of 'std' 
F:\gitP\copperspice\copperspice\src\core\global\qlog.cpp(178): error C3861: 'uncaught_exception': identifier not found
F:\gitP\copperspice\copperspice\src\core\signal\cs_signal.cpp(58): error C2039: 'uncaught_exception': is not a member of 'std’
F:\gitP\copperspice\copperspice\src\core\signal\cs_signal.cpp(58): error C3861: 'uncaught_exception': identifier not found
F:\gitP\copperspice\copperspice\src\core\signal\cs_slot.cpp(57): error C2039: 'uncaught_exception': is not a member of 'std’
F:\gitP\copperspice\copperspice\src\core\signal\cs_slot.cpp(57): error C3861: 'uncaught_exception': identifier not found

**Comment by agserm** [comment]
Thank you for this report. By coincidence we were working recently on cleaning up warnings, and a fix for this has just been pushed in d1e016a. Can you re-test and ensure the build is now successful? This commit is on the `master` branch, not the `cs-1.5` branch which is now in maintenance.

**Comment by QuellaZhang** [comment]
Thank you for letting me know this. I have updated the sha and submitted testing, but it will take a while. I will post a comment once the results are obtained.

**Comment by agserm** [comment]
Please reopen if this issue is still present.
