### ISSUE TITLE
Code in qtconcurrentexception.cpp

### ISSUE THREAD

**Issue by bjaraujo** [copperspice/copperspice#135]
Code in qtconcurrentexception.cpp

line: 150
```
   if (base->refCount.deref() == false) {
      delete base;
   }
```

It is comparing a bool to int:
line: 160
```
   if (base->refCount.deref() == 0) {
      delete base;
   }
```

deref() seems to already return bool so they both would be:

```
   if (!(base->refCount.deref())) {
      delete base;
   }
```

or

```
   if (base->refCount.deref() == false) {
      delete base;
   }
```
thus consistent. I see there are many places in Qt code where it was written as (boolean == false).

**Comment by agserm** [comment]
Thank you for noticing this. This has been fixed in b8127ae.
