### ISSUE TITLE
Vc++ compilation errors

### ISSUE THREAD

**Issue by mediabuff** [copperspice/copperspice#136]
https://github.com/janwilmans/copperspice-gettingstarted/issues/11#issue-568731974

How did you build 1.6 ? I trying to build using cmake and VS2019, get ton of errors because of winsock2.h . As you know this conflicts with winsock.h in windows.h (and dshow.h which indirectly includes windows.h)- which is used profusely in copperspice code base.

**Comment by janwilmans** [comment]
I do not see the seem problem, I strongly suspect your environment is finding libraries that are by default not present on windows.h (that happens for example using vcpkg, but could also be caused by manually adding libraries).  I can work this out with you, do you want to chat on slack? find my on cpplang slack #ug-nl-eindhoven, name: Jan (skyhawk)

**Comment by mediabuff** [comment]
You script works well. So, u were able to combine using IDE with errors ? Will connect with slack. Also, do u happen have a script for the kitchensink app?

**Comment by janwilmans** [comment]
The script works for kitchensink as well. Happy to talk on slack tomorrow if you feel like it.

**Comment by mediabuff** [comment]
Ok, will do. I meant to ask "were you able to compile using IDE without errors"

**Comment by janwilmans** [comment]
For me just opening the copperspice directory with 'open folder' functionality in VS2019 works. I can build without errors. Can you show me the output of the cmake 'configure' step (just do a fresh git clone and 'open folder' in vs2019, and copy the log windows? That may help me understand what you are seeing.

**Comment by mediabuff** [comment]
Was able for going after I removed vcpkg. Let me try kitchensink

**Comment by mediabuff** [comment]
copperspice location:  `D:\MyDevProjects\MyProjectsThirdPartyLibs\copperspice3\cmake`
kitchensink location: `D:\MyDevProjects\MyProjectsThirdPartySamples\copperspice\kitchensink`

I set to Copperspice_DIR to `D:\MyDevProjects\MyProjectsThirdPartyLibs\copperspice3\cmake (in kitchensink configuration)`

Is this correct ?

I get these errors

> 

`
CMake generation started for configuration: 'x86-Debug'.
1> Command line: "cmd.exe" /c ""C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="D:\MyDevProjects\MyProjectsThirdPartySamples\copperspice\kitchensink\out\install\x86-Debug" -DCopperSpice_DIR:PATH="D:/MyDevProjects/MyProjectsThirdPartyLibs/copperspice3/cmake" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.24.28314/bin/HostX86/x86/cl.exe" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.24.28314/bin/HostX86/x86/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "D:\MyDevProjects\MyProjectsThirdPartySamples\copperspice\kitchensink" 2>&1"
1> Working directory: D:\MyDevProjects\MyProjectsThirdPartySamples\copperspice\kitchensink\out\build\x86-Debug
1> [CMake] CMake Error at D:/MyDevProjects/MyProjectsThirdPartyLibs/copperspice3/cmake/CopperSpiceConfig.cmake:36 (include):
1> [CMake]   include could not find load file:
1> [CMake] 
1> [CMake]     D:/MyDevProjects/MyProjectsThirdPartyLibs/copperspice3/cmake/CopperSpiceLibraryTargets.cmake
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:22 (find_package)
1> [CMake] CMake Error at D:/MyDevProjects/MyProjectsThirdPartyLibs/copperspice3/cmake/CopperSpiceConfig.cmake:37 (include):
1> [CMake]   include could not find load file:
1> [CMake] 
1> [CMake]     D:/MyDevProjects/MyProjectsThirdPartyLibs/copperspice3/cmake/CopperSpiceBinaryTargets.cmake
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:22 (find_package)
1> [CMake] CMake Error at D:/MyDevProjects/MyProjectsThirdPartyLibs/copperspice3/cmake/CopperSpiceDeploy.cmake:19 (get_target_property):
1> [CMake]   get_target_property() called with non-existent target
1> [CMake]   "CopperSpice::CsCore".
1> [CMake] Call Stack (most recent call first):
1> [CMake]   D:/MyDevProjects/MyProjectsThirdPartyLibs/copperspice3/cmake/CopperSpiceConfig.cmake:41 (include)3
`

**Comment by janwilmans** [comment]
You have to set Copperspice_DIR to `................./cmake/CopperSpice`, the directory that contains CopperSpiceConfig.cmake

**Comment by mediabuff** [comment]
That's exactly what it's set to `D:\MyDevProjects\MyProjectsThirdPartyLibs\copperspice3\cmake`

**Comment by janwilmans** [comment]
I can't see your directory structure, but here there is another level:
cmake\CopperSpice\CopperSpiceConfig.cmake
not
cmake\CopperSpiceConfig.cmake

is that different for you?

**Comment by mediabuff** [comment]
Please let us connect at

> https://join.slack.com/t/adsoft-talk/shared_invite/enQtOTY1MjIyNjYwMDM3LWI5OTcyMDdiN2U2NDJlZmE3YWQ2NzRlMjA3NWZiMzY3NGY0ZTNjM2UxODg4NWY2ZDVkNmZiN2FmZGE5ZGU0OWU

**Comment by mediabuff** [comment]
I don’t have the next level ‘CopperSpice’

**Comment by mediabuff** [comment]
Thank you for your online support. Was able to successfully build copperspice and kitchensink using VS2019 IDE based cmake !!
