### ISSUE TITLE
Shadowed variables

### ISSUE THREAD

**Issue by bjaraujo** [copperspice/copperspice#137]
copperspice\src\core\io\qfileinfo.cpp:145:9: warning: declaration shadows a field of 
'QFileInfoPrivate'

```   
 uint cachedFlags = 0;
      ^
```

qfileinfo_p.h:125 
```
mutable uint cachedFlags : 30;
```
========================

copperspice\src\core\io\qdatastream.cpp:365:14: warning: declaration shadows a field of 'QDataStream'

```
      double d;
             ^
```

copperspice\src\core\io\qdatastream.cpp:410:13: warning: declaration shadows a field of 'QDataStream'
```
      float d;
            ^
```

qdatasream.h:164
```
   QScopedPointer<QDataStreamPrivate> d;
```

**Comment by bgeller** [comment]
Thanks for submitting this information. We have redesigned parts of QDataStream and fixed the names here and in QFileInfo. These commits will be part of our next release which is scheduled for the first week in February.
