### ISSUE TITLE
Inconsistent use of GL_TRUE, true and GL_FALSE, false

### ISSUE THREAD

**Issue by bjaraujo** [copperspice/copperspice#141]
These places in Opengl it uses true/false.

D:\Programming\copperspice\src\gui\opengl\qopenglpaintengine.cpp:2282:44
```
    funcs.glColorMask(false, false, false, false);
```

D:\Programming\copperspice\src\gui\opengl\qopenglpaintengine.cpp:2314
```
funcs.glColorMask(true, true, true, true);
```

other places it uses:
funcs.glColorMask(GL_FALSE, GL_FALSE, GL_FALSE, GL_FALSE); // Disable color writes

I think this should be consistent. In my opinion, since this is opengl GL_TRUE, GL_FALSE should be used to avoid implicit cast.

**Comment by agserm** [comment]
Thanks for reporting this. This has been committed in f417a31.
