### ISSUE TITLE
About QChart..

### ISSUE THREAD

**Issue by systembug** [copperspice/copperspice#145]
Do you have a plan to support QChart?
Or, If you already have supported or prepared this, how can I follow up the latest news about QChart?

**Comment by bgeller** [comment]
This library was originally only available under a Commercial License. Some time around 2016 they added the GPL 3.0 license.  There is sadly no LGPL license available.  

If you would like to contribute some portion of an LGPL 2.1 or BSD Chart library the team would be happy to test and maintain it. Please let us know if you are interested in working with us.

**Comment by systembug** [comment]
> This library was originally only available under a Commercial License. Some time around 2016 they added the GPL 3.0 license. There is sadly no LGPL license available.
> 
> If you would like to contribute some portion of an LGPL 2.1 or BSD Chart library the team would be happy to test and maintain it. Please let us know if you are interested in working with us.

Sure. It is interesting for me to contribute QChart as that license.
But, as you know, I don't know what's your specific plan to apply QChart or which is the rules such as coding style, naming, and so on. I wonder that I just contribute some part of the chart on the Cooperspice after forking the master of the Cooperspice with free style or obey some rules to control the whole codes of this.

**Comment by bgeller** [comment]
No one outside of the vendor can contribute to a commercial library.  However there are two other issues. QChart has a a GPL license and not LGPL so we can not use it with CopperSpice.  The other problem is the license they selected is version 3.0 which is very restrictive.  

Neither you nor anyone are legally allowed to change their license. 

We are interested in adding charting to CopperSpice and will need to be based on original work or some existing LGPL 2.1 or BSD licensed library.

**Comment by systembug** [comment]
> No one outside of the vendor can contribute to a commercial library. However there are two other issues. QChart has a a GPL license and not LGPL so we can not use it with CopperSpice. The other problem is the license they selected is version 3.0 which is very restrictive.
> 
> Neither you nor anyone are legally allowed to change their license.
> 
> We are interested in adding charting to CopperSpice and will need to be based on original work or some existing LGPL 2.1 or BSD licensed library.

You're right. 
I was saying that I just want to contribute a chart module based on the Cooperspice similar to QChart on the Qt, Not applying on the QChart directly. I think it's quite different. Even though someone tries to attach QChart on the Cooperspice direclty, it will be failed because the difference of the basis as aspect of the API.

**Comment by bgeller** [comment]
I just want to be very clear.  No one can use QChart with CopperSpice and the reason is strictly about the licenses. This is not an API issue. 

If you would like to contribute a brand new chart library to our project we are happy to do a code review. Please make very sure you do not look at the QChart source code and all of your work is original. Feel free to email us directly about any coding practice questions you may have. 

Barbara
