### ISSUE TITLE
setClearButtonEnabled

### ISSUE THREAD

**Issue by steavebba** [copperspice/copperspice#148]
setClearButtonEnabled(true) in QLineEdit makes the applications crash (segmentation fault) immediately after typing in the QLineEdit

**Comment by bgeller** [comment]
Can you let us know the following information:

1  What version of CopperSpice are you using
2  Did you build from source or use a binary from our download page
3  What platform are you running on  ( if Windows are you using MSVC )
4  Can you provide a small code sample for testing

**Comment by steavebba** [comment]
Copperspice v 1.6 build from source.
gcc (Ubuntu 9.3.0-11ubuntu0~18.04.1) 9.3.0   (linux mint)

```
#include <QApplication>
#include <QLineEdit>
int main(int argc, char** argv) {
  QApplication app(argc, argv);
  QLineEdit line;
  line.setClearButtonEnabled(true);
  line.show();
  return app.exec();
}
```

**Comment by bgeller** [comment]
Thanks so much for your setup details and the sample code.  We did a bit of digging around and found a call to connect( ) that was incorrect. We will push this change to github shortly. 

Barbara

**Comment by steavebba** [comment]
Thank you.
