### ISSUE TITLE
 Move CS_ReturnType::getName() implementations to inline code - breaks MSVC build 

### ISSUE THREAD

**Issue by ThomasKrenn** [copperspice/copperspice#151]
The commit from:
Jun 17, Move CS_ReturnType::getName() implementations to inline code 
in src/core/kernel/csmeta.h
breaks the MSVC build due to inconsistent DLL interface warnings and linker errors.

I am not really sure what the intention of the change was, because
the template will be instantiated on the client side anyway.

Only if the dll has e.g. something like the code below in a .cpp it will be linked in from the DLL:
`
template class __declspec(dllexport) MyGreatTemplate<double>;
`
(Even then you must hide the mygreattemplate_impl.h from the client.)

https://docs.microsoft.com/en-us/cpp/cpp/dllexport-dllimport?view=vs-2019

(The code before the commit seems to be correct.)

Best regards
Thomas Krenn

**Comment by ThomasKrenn** [comment]
Here is the link to the commit:
https://github.com/copperspice/copperspice/commit/3652cd7c7c3c6cf1969d8f913eaf96c5d2e8e18c?branch=3652cd7c7c3c6cf1969d8f913eaf96c5d2e8e18c&diff=split

**Comment by agserm** [comment]
Can you please rebuild using the current master branch of CopperSpice? I just did a clean build with MSVC and had no errors. Can you let us know what errors you are experiencing and what version of MSVC you are using?

**Comment by ThomasKrenn** [comment]
Unfortunately the issue still persists.

Microsoft Visual Studio Community 2019
Version 16.7.0
VisualStudio.16.Release/16.7.0+30330.147
Microsoft .NET Framework
Version 4.8.03752

Below is the output for qimage.

1>------ Build started: Project: CsGui, Configuration: Debug x64 ------
1>qimage.cpp
1>M:\cs\csm_build\include\QtCore\csmeta_internal_2.h(114,1): warning C4273: 'CS_ReturnType<T1,void>::getName': inconsistent dll linkage
1>        with
1>        [
1>            T1=R
1>        ]
1>M:\cs\csm_build\include\QtCore\csmeta.h(362,26): message : see previous definition of 'getName'
1>M:\cs\csm_build\include\QtCore\csmeta_internal_2.h(114): message : while compiling class template member function 'const QString &CS_ReturnType<T1,void>::getName(void)'
1>        with
1>        [
1>            T1=R
1>        ]
1>M:\cs\csm_build\include\QtCore\csmeta.h(424): message : see reference to function template instantiation 'const QString &CS_ReturnType<T1,void>::getName(void)' being compiled
1>        with
1>        [
1>            T1=R
1>        ]
1>M:\cs\csm_build\include\QtCore\csmeta.h(424): message : see reference to class template instantiation 'CS_ReturnType<T1,void>' being compiled
1>        with
1>        [
1>            T1=R
1>        ]
1>M:\cs\csm\src\gui\kernel\qinputmethod.h(57): message : see reference to function template instantiation 'const QString &cs_typeToName<R>(void)' being compiled
1>M:\cs\csm_build\include\QtCore\csmeta_internal_2.h(130,1): warning C4273: 'CS_ReturnType<T1,void>::getName': inconsistent dll linkage
1>        with
1>        [
1>            T1=R
1>        ]
1>M:\cs\csm_build\include\QtCore\csmeta.h(369,26): message : see previous definition of 'getName'
1>M:\cs\csm_build\include\QtCore\csmeta_internal_2.h(130): message : while compiling class template member function 'const QString &CS_ReturnType<T1,void>::getName(void)'
1>        with
1>        [
1>            T1=R
1>        ]
1>M:\cs\csm_build\include\QtCore\csmeta.h(424): message : see reference to function template instantiation 'const QString &CS_ReturnType<T1,void>::getName(void)' being compiled
1>        with
1>        [
1>            T1=R
1>        ]
1>M:\cs\csm_build\include\QtCore\csmeta.h(424): message : see reference to class template instantiation 'CS_ReturnType<T1,void>' being compiled
1>        with
1>        [
1>            T1=R
1>        ]
1>M:\cs\csm\src\gui\kernel\qwindow.h(84): message : see reference to function template instantiation 'const QString &cs_typeToName<R>(void)' being compiled

Best regards
Thomas Krenn

**Comment by ThomasKrenn** [comment]
In csmeta.h there is a __declspec(dllexport) for the CS_ReturnType for:
template <class T, class = void>

`
template <class T, class = void>
class Q_CORE_EXPORT CS_ReturnType
{
   public:
      static const QString &getName() {
         static_assert(! std::is_same_v<T, T>, "Requested type name has not been registered.");
         static const QString retval;
         return retval;
      }
};
`

**Comment by agserm** [comment]
This looks like a warning. Are you getting any errors when you build CopperSpice?

**Comment by ThomasKrenn** [comment]
> This looks like a warning. Are you getting any errors when you build CopperSpice?
From my first comment:
breaks the MSVC build due to inconsistent DLL interface warnings and linker errors.


All warnings are causing linker errors in csgui. You have to remove the Q_CORE_EXPORT from
template <class T, class = void> CS_ReturnType 
(or add Q_CORE_EXPORT to all CS_ReturnType in csmeta.h, but then you might have to deal with implicit, explicit template instantiation issues)

> I just did a clean build with MSVC and had no errors. 
This is hard to believe, because consistent 'visibility' for MSVC is not optional.
Maybe this helps to understand the issue:
https://gcc.gnu.org/wiki/Visibility

**Comment by ThomasKrenn** [comment]
Thanks for your feedback Jan. I restarted from scratch with MSVC 16.7.0 and this time the linker didn't complain. Mea culpa.

The kitchensink and diamond compilation also completed. 
Memory consumption was around 13GB at link time (without parallel compilation) and the .ilk file is 3.6 GB for csgui (debug compilation).

**Comment by janwilmans** [comment]
ok, thanks for the feedback.
