### ISSUE TITLE
Compiling copperspice with mingw-w64/gcc

### ISSUE THREAD

**Issue by ZachBacon** [copperspice/copperspice#153]
I'm running into an issue where I'm trying to compile copperspice via mingw-w64 that is built from binary gcc packages from the msys2 repository and it seems it has a build error when it gets to here.

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles/CsGui.dir/accessible/qaccessiblewidget_common.cpp.obj: section .text$_ZNSt8__detail9__variant5__getILy3ERKNS0_15_Variadic_unionIJdf7QChar328QString8P7QObjectPvSt10shared_ptrIN8QVariant10CustomTypeEEEEEEEDcSt16in_place_index_tIXT_EEOT0_: string table overflow at offset 10000096
C:\msys64\tmp\cchLidqV.s: Assembler messages:
C:\msys64\tmp\cchLidqV.s: Fatal error: can't close CMakeFiles/CsGui.dir/accessible/qaccessiblewidget_common.cpp.obj: file too big
```

**Comment by ZachBacon** [comment]
Bump

**Comment by bgeller** [comment]
As a notation we use MingGW not MSys2 for our non-MSVC windows builds.  

**1)**  Please let us know how much memory and swap space you have. 

**2)**  Are you doing a debug build?  I would suggest you try using the following commands to build in release mode.

* configure script

```
cmake -G "Ninja"  -DCMAKE_BUILD_TYPE=Release  \
                  -DCMAKE_INSTALL_PREFIX=<path_to_install> <path_to_source> 

```
* build script
 
```
ninja
ninja install
```

**3)**  Another alternative is to pass `-DCMAKE_CXX_FLAGS='-Wa,-mbig-obj'`

Let us know how this works out for you.

Barbara

**Comment by ZachBacon** [comment]
@bgeller MSYS2 just provides the environment for windows to which provides binary packages via pacman mingw-w64 compiler packages so that shouldn't cause issues.

As for memory and space, well I'm compiling this on top of windows, on a i7 kabylake with 24GB of ram and 3TB of hard disk space so swap isn't really needed.

Anyways I've tried the Flags you recommended for CXX Flags and trying it, so far it's working.
