### ISSUE TITLE
QT_NO_DEBUG - not set in release build?

### ISSUE THREAD

**Issue by ThomasKrenn** [copperspice/copperspice#154]
I have done a fulltext search over the cmake files and it seems it is not set.

**Comment by bgeller** [comment]
This macro actually has nothing to do with release or debug mode.  

It was used to guard some debug messages. We are actually working to change how and when debug messages are displayed.  This will be something you can turn on or off even in release mode.

**Comment by bgeller** [comment]
Seems like this issue has been addressed. If you have more questions please feel free to reopen.  Thanks so much.
