### ISSUE TITLE
CMake build error

### ISSUE THREAD

**Issue by bjaraujo** [copperspice/copperspice#158]
CMake Error at D:/Libraries/CopperSpice/copperspice-1.7.0/release/cmake/CopperSpice/CopperSpiceLibraryTargets.cmake:159 (message):
  The imported target "CopperSpice::CsCore" references the file

     "D:/Libraries/CopperSpice/copperspice-1.7.0/release/release/lib/CsCore1.7.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

I had to copy the files manually to release/release for it work properly. I think the windows installer might not be copying the files to the correct location.

**Comment by bgeller** [comment]
I am not sure where your path to "release/release" came from.  Dis you enter this somewhere? Maybe a CMake parameter? 

You mentioned a "windows installer" however you did not specify if this was MinGW or MSVC.  Let us know since the platforms are different. 

Did you get this error installing CopperSpice, building your own application, or installing some CS application? Let us now the full details.

**Comment by bjaraujo** [comment]
Hi, I installed the MSVC and installed it in a custom directory. Not sure why it picked up the release/release. I don't believe it was my CMake script.

**Comment by bgeller** [comment]
So you are saying there was an error when you ran the MSVC installer?  What did it say?

There is no CMake script to run an installer, you just run it. Running an installer will also not cause files to be put in random folders.  Is there a chance your error happened when building your application?  

Just to be sure, I ran the MSVC installer and had zero issues. I used a custom path of "D:\MyPrograms".  The CopperSpice target cmake files are located exactly where we expect which is the folder named "release\cmake\CopperSpice\"

**Comment by janwilmans** [comment]
@bjaraujo question: did you install like this: 
![image](https://user-images.githubusercontent.com/5933444/102697873-3847ea80-4231-11eb-929a-a62e2bccc0af.png)
?

And could you please post the cmake commandline for your project and show how you reference Copperspice ?

**Comment by bjaraujo** [comment]
I installed it in D:/Libraries/CopperSpice/copperspice-1.7.0

![image](https://user-images.githubusercontent.com/5067963/102699257-54e92000-423b-11eb-920f-cbdd976534f0.png)

project(GUI)

set(GUI_HEADERS
    Color.h
    LineData.h
    PointData.h
    Primitive.h
    TriangleData.h
    VertexData.h
    MainWindow.ui
    MeshDialog.ui
    MainWindow.h
    MeshDialog.h
    MeshThread.h
    GLWidget.h
)

set(GUI_SOURCES
    LineData.cpp
    PointData.cpp
    Primitive.cpp
    main.cpp
    GLWidget.cpp
    MainWindow.cpp
    MeshDialog.cpp
    MeshThread.cpp
    TriangleData.cpp
    VertexData.cpp
    qrc_MainWindow.cpp
)

source_group("Form Files" FILES ${GUI_UI_HEADERS})
source_group("Header Files" FILES ${GUI_HEADERS})
source_group("Source Files" FILES ${GUI_SOURCES})

find_package(OpenGL REQUIRED)
find_package(CopperSpice REQUIRED)

COPPERSPICE_RESOURCES(${CMAKE_CURRENT_SOURCE_DIR}/resources/MainWindow.qrc)
COPPERSPICE_RESOURCES(${CMAKE_CURRENT_SOURCE_DIR}/MainWindow.ui)
COPPERSPICE_RESOURCES(${CMAKE_CURRENT_SOURCE_DIR}/MeshDialog.ui)

set(Boost_USE_STATIC_LIBS    ON)
set(Boost_USE_MULTITHREADED  ON)
set(Boost_USE_STATIC_RUNTIME OFF)

find_package(Boost REQUIRED)

include_directories(
  ${CMAKE_CURRENT_BINARY_DIR}
  ${Boost_INCLUDE_DIR}
  ${OPENGL_INCLUDE}
)
add_definitions("-DHAS_BOOST")

add_executable(GUI ${GUI_HEADERS} ${GUI_SOURCES})

target_link_libraries(GUI 
  ${OPENGL_LIBRARIES}
  CopperSpice::CsCore
  CopperSpice::CsGui
  CopperSpice::CsOpenGL
)

install(TARGETS GUI DESTINATION .)

cs_copy_library(CsCore)
cs_copy_library(CsGui)
cs_copy_library(CsOpenGL)

# installs the platform Gui plugin
cs_copy_plugins(CsGui)

**Comment by bgeller** [comment]
Let's try this again. What we need to know just the following and I am sure we can figure this all out. 

(1)   Did you get an error when running the MSVC installer? If so, please give us the full error message. 

(2)  I would suggest you delete your installed copy of CS and try again using your exact path of 
--> "D:/Libraries/CopperSpice/copperspice-1.7.0". 

(3)  Do not move any files around. We want to make sure this step works for you. 

Once CS is installed then we can work with you to figure out the next issue.  Thanks.

**Comment by bjaraujo** [comment]
1) No, the installer worked fine until the end
2) I will try that but it is second time I did it.
3) Sure, I didn't want to move files around.

**Comment by bjaraujo** [comment]
Adding print messages to CopperSpice CMake:

```
message(STATUS "1 =========================> ${_IMPORT_PREFIX}")

### nuget specific addition
if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    set (_IMPORT_PREFIX "${_IMPORT_PREFIX}/debug")
else()
    set (_IMPORT_PREFIX "${_IMPORT_PREFIX}/release")
endif()
### nuget specific addition

message(STATUS "2 =========================> ${_IMPORT_PREFIX}")
```

I get:

```
1 =========================> D:/Libraries/CopperSpice/copperspice-1.7.0/release
2 =========================> D:/Libraries/CopperSpice/copperspice-1.7.0/release/release
CMake Error at D:/Libraries/CopperSpice/copperspice-1.7.0/release/cmake/CopperSpice/CopperSpiceLibraryTargets.cmake:162 (message):
  The imported target "CopperSpice::CsCore" references the file

     "D:/Libraries/CopperSpice/copperspice-1.7.0/release/release/lib/CsCore1.7.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "D:/Libraries/CopperSpice/copperspice-1.7.0/release/cmake/CopperSpice/CopperSpiceLibraryTargets.cmake"

  but not all the files it references.
```

The ${_IMPORT_PREFIX} variable already has "/release" and then it is added again.

**Comment by bgeller** [comment]
We are very confused and really need to do this in order. Please work with us and follow our directions. 

If the installer failed **at the end** then it did not work for you. We need to know what you did so we can repeat everything. Please do not edit any files or change things right now. 

(1) Did you run the MSVC installer and change the default install path to EXACTLY  --> **"D:/Libraries/CopperSpice/copperspice-1.7.0"**   It is very critical that we know the exact path you used otherwise helping out gets tricky.

(2) Did the MSVC installer ( just the installer ) complain? 

(3) We do need any pictures or images.

**Comment by bjaraujo** [comment]
Here are the images:

![image](https://user-images.githubusercontent.com/5067963/102699807-bca16a00-423f-11eb-8b51-0a8d46e9953e.png)
![image](https://user-images.githubusercontent.com/5067963/102699816-dc389280-423f-11eb-97e5-3b81f727c9f6.png)
![image](https://user-images.githubusercontent.com/5067963/102699824-e8245480-423f-11eb-9c7e-fe65724d1792.png)
![image](https://user-images.githubusercontent.com/5067963/102699860-2e79b380-4240-11eb-9370-fd1de279b6b3.png)

**Comment by bjaraujo** [comment]
![image](https://user-images.githubusercontent.com/5067963/102699925-af38af80-4240-11eb-8d70-40034686995e.png)

**Comment by bjaraujo** [comment]
1) Yes
2) No, it didn't complain.

**Comment by bgeller** [comment]
Again,  you are giving us very conflicting information. The installer **either** ran perfectly with no errors or it had an error. There is no way for it to do both.  

You have said multiple time the MSVC installer did not complain. That means it ran and installed the files.  
If it ran and then had an ERROR at the end, then the installer failed to install.  

We need to know just this one thing:  did the INSTALLER run and give an error or not.

**Comment by bjaraujo** [comment]
I never said the installer gave an error, please my messages again.

**Comment by bgeller** [comment]
` It ran fine **until the end.**`

Yes you have said multiple times the MSVC installer **had** an issue "at the end".  If the installer ran with no errors than we just spent hours debugging something which is not broken. The phrase "at the end" means the installer crashed at the end. 

Please, we need to solve thing in order and ensure the installer ran. I have had multiple people test this and no one can repeat your installer issue.  If this is not an installer issue then you will need to say so. 

Then we can move forward and talk about your real issue.

**Comment by bjaraujo** [comment]
There were no issues with the installer. Sorry for the misunderstanding.

**Comment by bjaraujo** [comment]
I also I narrowed down the problem to IMPORT_PATH variable in CMake and that comment was deleted.

**Comment by bgeller** [comment]
Thank you for confirming the installer did not have any problem and it completed successfully.  As you can see clarity and accurate reporting is very important.  I would suggest next time just let us know step A worked and I have an issue at step B.  Then tell us what you did and what you expected.

**Comment by bgeller** [comment]
In your recent comment you have said the problem is with a variable in CMake. Again lots of information is missing and this makes it extremely hard to help.

We are available to help users however we would like to encourage everyone to submit concise reporting so the process is more effective and productive.

1  I am compiling my application  or maybe this is KitchenSink ? 

2  If everything compiles and you are linking state this information.

3  These are the commands I used to configure and compile the application. <list command>

4  I have CMake file <supply name> and the error is < just list the very minimum, we may ask for more >

You have not told us if this is your application or from the CS project.
You did not mention if this was a compile problem, linking problem, or run time issue.
You did not tell us if removing the variable resolved your issue. 
You did not indicate what affect removing the CMake variable had on your compile.

**Comment by bjaraujo** [comment]
1) This is my application so it is my own CMake but I based it on:
https://www.copperspice.com/docs/cs_overview/sample-cs-cmake.html
I can try some other project if you want. Also I am compiling on Windows 10 using MSVC compiler. 

2) This is a CMake configure problem. 

3) I use CMake-GUI to configure CMake.
CopperSpice_DIR -> D:/Libraries/CopperSpice/copperspice-1.7.0/release/cmake/CopperSpice
This is entered in the CMake-GUI

4) CMake Error at D:/Libraries/CopperSpice/copperspice-1.7.0/release/cmake/CopperSpice/CopperSpiceLibraryTargets.cmake:159 (message):
The imported target "CopperSpice::CsCore" references the file

 "D:/Libraries/CopperSpice/copperspice-1.7.0/release/release/lib/CsCore1.7.lib"

My workaround was just to move the bin and lib to a release directory like so:

![image](https://user-images.githubusercontent.com/5067963/102813760-504e7400-43c1-11eb-87aa-b54ea45dbfa6.png)

With this last change it all works fine.

**Comment by bgeller** [comment]
Moving the install setup for CopperSpice is not the best solution and we do advise against it.  It would be better to figure out the actual issue.

**Comment by bgeller** [comment]
Not sure if there is still an issue or if you are happy with the solution you found. If you want to revisit anything please reopen this issue or start a new one. Thanks!
