### ISSUE TITLE
How to learn using copperspice the right way

### ISSUE THREAD

**Issue by stefanos82** [copperspice/copperspice#159]
Hello,

I hope you are doing well.

I have no idea how Qt works, but I would like to start using copperspice as a complete newcomer.

I have experience with wxWidgets, but for a number of years now I'm dealing with web development and I really miss C++ like crazy.

Is there any article or book I could read to build a couple of demos to make myself feel right at home?

Thank you very much.

Keep up the good work :+1:

Regards,

Stefanos

P.S.: wxWidget has a [wxQt](https://wiki.wxwidgets.org/WxQt) project; I wonder how copperspice could be used in place of Qt as its backend; that would be really interesting to see!

**Comment by bgeller** [comment]
Thank you for your interest in CopperSpice. For an nice introduction on why we created the project I would suggest you watch the following youtube video.  

https://www.youtube.com/watch?v=jvxWitw00CU

Since it sounds like you might be coming back to the language, we would like to mention there are over 55 videos about C++ on our youtube channel.  These videos cover topics related to what was added in modern C++.

In terms of a demo please have a look at KitchenSink. You can download a binary executable on our download page as well as the full source code. The source code is also available here on github. You can also have a look at Diamond which is a programmers editor written in C++ and it uses the CopperSpice libraries. 

https://download.copperspice.com/kitchensink/binary/
https://download.copperspice.com/diamond/binary/

The readme.md file on the github copperspice project has links to the "CS Overview Documentation" and the "CS API documentation".

**Comment by stefanos82** [comment]
> Thank you for your interest in CopperSpice. For an nice introduction on why we created the project I would suggest you watch the following youtube video.
> 
> https://www.youtube.com/watch?v=jvxWitw00CU
> 

I already saw it :smile: 

> Since it sounds like you might be coming back to the language, we would like to mention there are over 55 videos about C++ on our youtube channel. These videos cover topics related to what was added in modern C++.
> 

Yep, that's a good advice; thank you! :+1: 

> In terms of a demo please have a look at KitchenSink. You can download a binary executable on our download page as well as the full source code. The source code is also available here on github. You can also have a look at Diamond which is a programmers editor written in C++ and it uses the CopperSpice libraries.
> 
> https://download.copperspice.com/kitchensink/binary/
>

That was the demo I played with and loved CopperSpice.

The whole GUI experience felt so familiar to me and to be honest with you, some applications I am using for ages now are implemented in Qt and have some annoying bugs that have been waiting for years to fix them but because no one does for some peculiar reason, I need to learn how Qt behaves and so I can fork them and migrate them to CopperSpice for my own personal use while retaining their original license.

It will be a fun time, I'm sure :smiley: 

> https://download.copperspice.com/diamond/binary/

I have already placed it at its own directory and symlinked it accordingly.

I haven't checked whether it supports auto-completion or not yet; still it's a good looking editor. Thank you for the suggestion :+1: 

> The readme.md file on the github copperspice project has links to the "CS Overview Documentation" and the "CS API documentation".

That's very nice; thank you for the detailed reply.

I really appreciate it.

Kind suggestion: can we add a "newcomers' section" in README and let them know how they could follow the same path?

I'm sure others need more information, let alone screenshots to attract candidate users.

Other than that, that's all for now.

I'll keep an eye on this project; it's already starred and I plan to use it as my standard C++ GUI library.

Cheers :tropical_drink:

**Comment by bgeller** [comment]
One other suggestion for you.  Have a look at our migration notes in the CS Overview docs. 

https://www.copperspice.com/docs/cs_overview/cs-migration.html

**Comment by stefanos82** [comment]
Nice.

By the way, are these header names opened on purpose, that is are not closed with `>` for a reason?
![image](https://user-images.githubusercontent.com/1777466/103043339-3c536f80-4585-11eb-8f21-17888c9dd713.png)

**Comment by agserm** [comment]
> Nice.
> 
> By the way, are these header names opened on purpose, that is are not closed with `>` for a reason?

We were updating docs today, the '>' was adjusted.

**Comment by stefanos82** [comment]
Excellent job @agserm and @bgeller 

Time to get some action :eyeglasses: 

Thank you both!

**Comment by bgeller** [comment]
If you have any other comments please feel free to reopen this ticket.  Thanks for your interest in CopperSpice.
