### ISSUE TITLE
Time to move to CopperSpice

### ISSUE THREAD

**Issue by v3ss0n** [copperspice/copperspice#160]
QT is done , they are going the way of DoDo
Its time for big QT Opesnource users like KDE to move to CopperSpice.

**Comment by bgeller** [comment]
We understand they have made choices which may not be in the best interest of the open source community. Our CopperSpice team is here to welcome users and offer a true open source solution.  

Our "CS Overview" contains migration documentation and information about the PepperMill translation utility.  
https://www.copperspice.com/docs/cs_overview/migration.html

API documentation: https://www.copperspice.com/docs/cs_api/index.html

Barbara
Co Founder of CopperSpice and DoxyPress

**Comment by DominionSoftware** [comment]
Would like to know if there's a plan to support VTK and other scientific libraries?

**Comment by bgeller** [comment]
@DominionSoftware  

We have had a few CS users ask us about porting VTK to CopperSpice.  I believe someone is looking at doing a port and we are more than happy to lend a hand.  Would you like to be involved?  If so we can connect users.

**Comment by ShamanTcler** [comment]
Agreed, having the VTK port is on my todo list. 

I should be retiring next month, so I should have more time. My focus will be the libs/tools that get layered on top of Qt.

So my list will include:

- Qwt
- Vtk
- QXlsx
- qtcsv
- etc etc etc

I will likely be focusing on Win 10 , then migrating to a Linux or two.

**Comment by DominionSoftware** [comment]
I can help, my time is somewhat limited but I’ll do what I can.

Rick Frank

**Comment by ShamanTcler** [comment]
My current tool chain looks something like:

- Win 10
- VS Code (editor / ide)
- Cmake / Ninja
- Conan
- MSVS 2019 community
  - though I am looking at Intel's FREE icl compiler (Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.1)  ... it is free even for commercial use
- Copperspice 1.7 

Is this something you can use too?

**Comment by DominionSoftware** [comment]
On Windows my typical current setup is

CMAKE
MSBuild - Microsoft 64 bit compiler
- builds as needed VTK, ITK, Armadillo, various other (I.e.  copperspice)

CMakeLists.txt for my app outputs app.sln
Use Visual Studio Professional for development

Any automation ( Jenkins etc ) done through .bat files.

For Linux in the past I've used codeblocks for ide
Maybe consider CLion for future



Rick Frank
Dominion Software, Inc.
825 Beacon Street
Newton, MA 02459
Medical, Scientific, and Industrial Software

On Jan 7, 2021, at 8:24 AM, ShamanTcler <notifications@github.com> wrote:

﻿

My current tool chain looks something like:

  *   Win 10
  *   VS Code (editor / ide)
  *   Cmake / Ninja
  *   Conan
  *   MSVS 2019 community
     *   though I am looking at Intel's FREE icl compiler (Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.1) ... it is free even for commercial use
  *   Copperspice 1.7

Is this something you can use too?

**Comment by janwilmans** [comment]
Hi guys,

I use:
* Windows 10 and Debian 10
* Visual Studio 2019 community edition (msvc x64 compiler) - I mostly use the debugging and the compiler, I do not use the IDE for editing
* CMake + msbuild + nuget for tutorials / explaining the basics
* CMake + ninja for fast development / debugging
* Visual Visual Code on both windows and linux 
* gcc10 and clang10 on debian10
* I'm looking into using Conan for both work and private projects

I have used XCode on MacOS inside VirtualBox on windows ;) but only for testing if compilation works.

**Comment by agserm** [comment]
Closing this ticket. If someone would like to pick this task up the development team is happy to work with you.
