### ISSUE TITLE
Mutating iterator

### ISSUE THREAD

**Issue by hs-apotell** [copperspice/copperspice#166]
Following line of code asserts in debug builds when the `popupWidgets' list is empty.

https://github.com/copperspice/copperspice/blob/e3d2b7b5f98e0a7c00cae4c688953f878674cfbf/src/gui/graphicsview/qgraphicsscene.cpp#L3491

**Comment by agserm** [comment]
Resolution for this issue required additional changes. This has been committed as 9ff3ed0.
