### ISSUE TITLE
Build fails on Debian 10

### ISSUE THREAD

**Issue by bjoekeldude** [copperspice/copperspice#168]
After inspecting a few missing libs I figured it wouldn't make a difference for the build process, but building stopps.
Any suggestions on how to proceed? Logs' attached 

[build.log](https://github.com/copperspice/copperspice/files/5939071/build.log)

[cmake.log](https://github.com/copperspice/copperspice/files/5939045/cmake.log)

**Comment by janwilmans** [comment]
The logs show that the compiler was killed, I suspect that its running out of memory. 
You can verify this by checking dmesg, for example as root do : "dmesg | grep killed"

In my experience this happens with 16GB or less. I personally use 32GB and don't see this problem.

**Comment by bjoekeldude** [comment]
Jan,

thanks for the suggestion.

`[67664.932863] Out of memory: Kill process 19463 (cc1plus) score 81 or sacrifice child`

so apparently 16GB isn't enough. I'd probably upgrade my machine.
Any workarounds for errors like this?

**Comment by janwilmans** [comment]
You didn't specify your CMake commandline that you used, but if you used ninja, you could try to compile using `ninja -j 2` this spawns only 2 paralel build processes?

**Comment by janwilmans** [comment]
you can also find me on twitter at https://twitter.com/janwilmans if you DM me we can chat

**Comment by bjoekeldude** [comment]
`ninja -j2` seems to get rid of the problem, but it of course takes WAY MORE time.

Thanks for the support!

**Comment by janwilmans** [comment]
no problem, you can experiment with -j 4 or -j8 
![image](https://user-images.githubusercontent.com/5933444/107151188-8b9d0600-6961-11eb-86fb-f88dbbd2fd12.png)

using `ninja --version` you can see the default at the line  `run N jobs in parallel (0 means infinity) [default=8 on this system]` 

here it is '8' in my VM.
