### ISSUE TITLE
Coexisting with system qt

### ISSUE THREAD

**Issue by ZachBacon** [copperspice/copperspice#173]
I don't suppose it's possible to have copperspice coexist with qt? And if not, are there plans to eventually allow for such a thing to happen?

**Comment by bgeller** [comment]
It is unclear what you mean by "coexist", please elaborate a bit more. 

Are you asking if you can install both on the same computer? Then the answer is yes as long as they are located in different folders. 

Is your question about linking a C++ application with both the Qt framework and the CS libraries into one executable?  If so then the no, this is not possible and  does not make sense.  

This is sort of like wanting to compile a given program with both C++11 and C++17, it simply does not work. If you could which version of std::vector would be used? The conflicts would be impossible for the compiler to resolve. 

The CS version of QString was redesigned to support UTF-8 which is the industry standard. The Qt implementation uses UCS-2, similar to UTF-16.  In CS we have improved many other classes in similar ways. 

So the real question is what do you believe you need from Qt and then how we add that functionality to CS if it will benefit other users. 

Barbara
Co-Founder of CopperSpice

**Comment by ZachBacon** [comment]
I'm talking about coexisting on a file system, I'm sorry if I wasn't clear on that matter, because with how I'm seeing things are, the header files will conflict with Qt headers making a packagers nightmare.

**Comment by bgeller** [comment]
Thanks for clarifying your question. You can of course install CS to any location on your computer, which I am sure you knew.

In terms of a packages for Linux this is on our road map and yes will enure this does not conflict with installations of Qt.  Great question.

**Comment by ZachBacon** [comment]
Alright, perfect, that's good to know, and I do apologize for wording my question poorly the first time around. Seems I shouldn't be asking questions until I had my first cup of coffee for the day!
