### ISSUE TITLE
Caching signal/slot indexes in QGraphicsScene doesn't work

### ISSUE THREAD

**Issue by hs-apotell** [copperspice/copperspice#178]
Three different cached indexes in QGraphicsScenePrivate
* int changedSignalIndex;
* int processDirtyItemsIndex;
* int polishItemsIndex;

When initialized in QGraphicsScenePrivate::init, the metaObject() is from QGraphicsScene but when used in other member functions later, the metaObject() is from sub-class making those indexes wrong.

This issue resulted in clearing the whole scene (because processDirtyItemsIndex ended up pointing to clear() instead of _q_processDirtyItems).

**Comment by agserm** [comment]
We looked at your proposed PR and we discovered the indexes were a bit slow. We rewrote QGraphicsScene to use QMetaMethod. It was really nice to have your PR so we knew exactly what sections to modify. This change has been committed in 2adf1837. Please have a look and see if there are any additional outstanding problems in this area.

Thanks for your help, and we look forward to additional suggestions.

**Comment by agserm** [comment]
Issue resolved.
