### ISSUE TITLE
Build Error, but No Msgs

### ISSUE THREAD

**Issue by wwderw** [copperspice/copperspice#183]
Recently discovered the project.  Been a huge Qt/KDE fan.  Created a couple of Qt based programs, always used QMake though instead of CMake, so I'm kinda lost in the woods.

In the process of trying to do one of the programs from the ground up in CS as I did in Qt (with some treaks), however having a build problem.

Specs:

Using a VM:

Win 8.1 64bit
Latest CopperSpice
CMake/Ninja
Qt Creator

I run the build and not getting any feedback from Creator as to what the issue could be, which leads me to suspect my CMake file, especially since I really have no experience with CMake, so I'm sure I am missing something, is the culprit.

I tried to make sure I followed the one in the documentation, but with tweaks as the file structure is also different.

My CMake file reads as:

`cmake_minimum_required(VERSION 3.8 FATAL_ERROR)
project(program)

include(CheckCXXCompilerFlag)
include(CheckCXXSourceCompiles)
include(CheckIncludeFile)
include(CheckIncludeFiles)
include(CheckTypeSize)
set(CopperSpice_DIR "C:/CopperSpice/cmake/copperspice")

find_package(CopperSpice REQUIRED)

set(PACKAGE "program")
set(PACKAGE_NAME "program")

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_INCLUDE_DIRECTORIES_BEFORE ON)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)

list(APPEND program_INCLUDES
    programcontrols.h)

list(APPEND program_SOURCES
    main.cpp
    programcontrols.cpp
    programcontrols.ui
    )

COPPERSPICE_RESOURCES(
   programcontrols.ui
)

add_executable(program ${program_SOURCES} )

target_link_libraries(program
    CopperSpice::CsCore
    CopperSpice::CsGui
    CopperSpice::CsMultimedia
  )

cs_copy_library(CsCore)
cs_copy_library(CsGui)
cs_copy_library(CsMultimedia)

install(TARGETS program DESTINATION .)`

**Comment by janwilmans** [comment]
If you're getting no feedback, there is not much for me to work with, I recommend running cmake from the commandline and once you have that working, move to an IDE.

**Comment by wwderw** [comment]
Thanks, I'll give that a try later on and see if that provides anything helpful.

I just didn't know if there was a glaring issue with my CMake file that would have popped out regardless of any project specific issue.  First experience with CMake so I'm definitely in the thick of it.

**Comment by wwderw** [comment]
Ok, so I tried to build it on my Ubuntu Studio 21.04 rig and I get:

ninja: error: path/to/libz.so, needed by program, missing and no known rule to make it

However, I look in that directory and I have:

libz.so.1
libz.so.1.2.11

I would think that I would be covered or am I wrong?

**Comment by bgeller** [comment]
Need to ask a few questions so we are on the same page.  

1)  Are you trying to build CopperSpice from source or did you download our binary files?

2)  If you are building CS from source did you install all the packages? There is a `apt-get` install under the table. 
https://www.copperspice.com/docs/cs_overview/requirements-unix.html#ubuntu20-cs-dev

3)  If you did install the CS binary files, did you build KitchenSink from source?  
You can clone of course from github or download source from here: https://download.copperspice.com/kitchensink/source/

4)  What were you doing when you got  "needed by program, missing and no known rule to make it"?

**Comment by wwderw** [comment]
1. Used the binaries and put them on PATH as well.
2. N/A
3. I did not build KitchenSink, but do have the source files
4. Executing this command: cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=[target_path] -DCMAKE_PREFIX_PATH=[path_to_copperspice] .

With the appropriate locations where needed.

**Comment by bgeller** [comment]
So you downloaded our CS binary files for Ubuntu 20.04? 

Normally you will still need to install the Ubuntu packages to build an application which links with CopperSpice. Keep in mind we have not tested Ubuntu 21.04 nor have we tested with any "Studio" version of Ubuntu.  We can, but these are not on our supported platform list.  https://www.copperspice.com/docs/cs_overview/supported-platforms.html

You mentioned you are new to CMake so here is a quick introduction. There are  three steps and you can combine 2 and 3 into one step.
 
(1) run `CMake` to generate the build files  (2)  run `Ninja` to build  (3)  run` Ninja install`  

We are wondering if you saw this error running CMake or Ninja. 

Since it seems like you get this error building your application, I would like to suggest you build KS so we an ensure yout setup is working correctly.

**Comment by wwderw** [comment]
Probably running a Beta of anything isn't helping either.

Sounds like I'll be spinning up an Ubuntu VM to keep everything on equal footing.

The joys of being at that glorious/dangerous stage of just knowing enough to cause damage.

Thanks for the help and patience with this newb.

**Comment by bgeller** [comment]
We do our best to support all users in the same fashion regardless of their level of experience. Our idea is to provide the type of support we would want to receive.  We may falter a little but then we regroup and try again.

Thank you for being willing to step back and use a standard Ubuntu VM.  Once this is set and working we can go back and see why your other setup had some issues.

**Comment by wwderw** [comment]
So I built KitchenSink and running it via GUI, I got a "shared library" error, but running it via terminal I get "Requested Plugin Key: 'xcb' "

Just for giggles, I tried to build my original program and get msgs related to the .cpp file for the ui.  incomplete type class and forward declaration of same class.

I know that I had to change the header files by using PepperMill, is there anything that I needed to do with the cpp/ui files as well since they are targeting CS instead of Qt.

**Comment by bgeller** [comment]
(1)  So you built KS. Did you run `ninja install`?  This step will copy the so or dll files to the appropriate folder under your application. 

Please have a look at our documentation under, "Building KitchenSink From Source".  You need to install and then run from the deploy folder.   https://www.copperspice.com/docs/cs_overview/demo-ks.html


(2)  We will assume there were no errors when you ran PepperMill. There are no specific changes you need to make to the CPP or UI files, unless you have compiler errors.  This page may be of some help and shows where CS differs. Like how to change your calls from QRegExp to  QRegularExpression.
 
https://www.copperspice.com/docs/cs_overview/cs-migration.html

An incomplete type typically means you have a forward declaration and will need to actually include the header.  Can you give us just one example so we can look at this together.

**Comment by gvanem** [comment]
> (2) We will assume there were no errors when you ran PepperMill. 

I'm curious about this tool. Where is it? The above migration did not have a link too it?!

**Comment by bgeller** [comment]
Additional information about the directions to run PepperMill. This is a utility run one time on your C++ header files. It will convert your application header files to CopperSpice header files and change the syntax of Signal and Slot declarations, properties, enums, and several other constructs which involve registration. The conversion will update your existing source to work with CopperSpice.

https://www.copperspice.com/docs/cs_overview/cs-peppermill.html

**Comment by agserm** [comment]
CopperSpice and PepperMill are working, please reopen if you have a new question.
