### ISSUE TITLE
Iterator validity check and std::vector::erase 

### ISSUE THREAD

**Issue by ThomasKrenn** [copperspice/copperspice#184]
QtCore\cs_string.h

```cpp
template <typename E, typename A>
CsBasicString<E, A> &CsBasicString<E, A>::replace(const_iterator first, const_iterator last, const CsBasicString &str)
{
   auto iter = erase(first, last);
   insert(iter, str);

   return *this;
}
```

The vector member function 'erase' invalidates iterators.
The tests below fail in MSVC/debug configuration with a debug assertion for iterator validity.

   CsCoreTest:QDebug basic (SEGFAULT)
   CsCoreTest:QDebug operators (SEGFAULT)
   CsCoreTest:QDir entry_list (SEGFAULT)
   CsCoreTest:QFile size (SEGFAULT)
   CsCoreTest:QFile read (SEGFAULT)
   CsCoreTest:QFileInfo base_name (SEGFAULT)
   CsCoreTest:QFileInfo file (SEGFAULT)
   CsCoreTest:QTemporaryFile fname_a (SEGFAULT)
   CsCoreTest:QTemporaryFile fname_b (SEGFAULT)
   CsCoreTest:QTemporaryFile fname_c (SEGFAULT)
   CsCoreTest:QTemporaryFile fname_d (SEGFAULT)
   CsCoreTest:QTemporaryFile fname_e (SEGFAULT)
   CsCoreTest:QTemporaryFile file_template (SEGFAULT)

Backtrace:

    CsCore1.7d.dll!std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned char>>>::operator--() Line 89	C++	Non-user code. Symbols loaded.
    CsCore1.7d.dll!CsString::utf8::walk(__int64 len, std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned char>>> iter) Line 132	C++	Symbols loaded.
    CsCore1.7d.dll!CsString::CsStringIterator<CsString::utf8,std::allocator<unsigned char>>::operator--() Line 215	C++	Symbols loaded.
    CsCore1.7d.dll!QString8::iterator::operator--() Line 120	C++	Symbols loaded.
    CsCore1.7d.dll!createFileName(QString8 fName, unsigned __int64 pos, unsigned __int64 length) Line 75	C++	Symbols loaded.
    CsCore1.7d.dll!createFileFromTemplate(void * & fHandle, QString8 & fName, unsigned __int64 pos, unsigned __int64 length, unsigned int mode, QSystemError & error) Line 86	C++	Symbols loaded.
    CsCore1.7d.dll!QTemporaryFileEngine::open(QFlags<enum QIODevice::OpenModeFlag> openMode) Line 234	C++	Symbols loaded.
    CsCore1.7d.dll!QFile::open(QFlags<enum QIODevice::OpenModeFlag> mode) Line 605	C++	Symbols loaded.
    CsCore1.7d.dll!QTemporaryFile::open(QFlags<enum QIODevice::OpenModeFlag> flags) Line 488	C++	Symbols loaded.
    CsCore1.7d.dll!QTemporaryFile::open() Line 61	C++	Symbols loaded.
    CsCoreTest.exe!____C_A_T_C_H____T_E_S_T____4() Line 58	C++	Symbols loaded.

**Comment by agserm** [comment]
Thanks for reporting this, fixed in 47427b3.
