### ISSUE TITLE
Folder for predefined CMAKE targets

### ISSUE THREAD

**Issue by ThomasKrenn** [copperspice/copperspice#185]
Please add to the code below to the root CMakeLists.txt
This organizes the predefined CMakeTargets (BUILD,INSTALL,RUN_TESTS,...) in a folder, for IDEs (XCODE,MSVC) that support the feature.

    set_property(GLOBAL PROPERTY USE_FOLDERS ON)
    set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMakePredefinedTargets")

**Comment by bgeller** [comment]
IDE support not provided at this time. We will consider adding at a future time.
