### ISSUE TITLE
Why is harfbuzz compiled in CsCore and CsGui?

### ISSUE THREAD

**Issue by ThomasKrenn** [copperspice/copperspice#188]
Seems to me that the code in 
.\core\tools\qharfbuzz_core.cpp
does nothing special. 
Can the code moved to CsGui (src\gui\text)?

**Comment by bgeller** [comment]
This is something we need to leave in place and HB will be updated to a newer version in the next few months.

**Comment by bgeller** [comment]
CopperSpice was updated to use a more recent version of Harfbuzz. In this redesign it was removed from CsCore and it only linked with CsGui.
