### ISSUE TITLE
kitchensink compile error on linux

### ISSUE THREAD

**Issue by michkrom** [copperspice/copperspice#193]
I get this error below while building kitchensing against the latest CS librariy (as Apr 2 11:10 ca529aea5404869b740087e8e7e10786851a7b53). 

Ubuntu 20.04/cmake 3.17.2/gcc 9.3

[  1%] Building CXX object src/CMakeFiles/KitchenSink.dir/graphics/animated_tiles.cpp.o
In file included from /usr/local/include/QtCore/csobject_macro.h:29,
                 from /usr/local/include/QtCore/qobject.h:27,
                 from /usr/local/include/QtGui/qgraphicsscene.h:27,
                 from /usr/local/include/QtGui/QGraphicsScene:1,
                 from /home/m/git/kitchensink/src/graphics/animated_tiles.h:23,
                 from /home/m/git/kitchensink/src/graphics/animated_tiles.cpp:20:
/home/m/git/kitchensink/src/graphics/animated_tiles.cpp: In constructor ‘AnimatedTiles::AnimatedTiles(QWidget*)’:
/home/m/git/kitchensink/src/graphics/animated_tiles.cpp:106:25: error: cannot convert ‘const char*’ to ‘const QString&’ {aka ‘const QString8&’}
  106 |    view->setWindowTitle(QT_TRANSLATE_NOOP(QGraphicsView, "Animated Tiles"));
      |                         ^~~~~~~~~~~~~~~~~
      |                         |
      |                         const char*
In file included from /usr/local/include/QtCore/qobject.h:27,
                 from /usr/local/include/QtGui/qgraphicsscene.h:27,
                 from /usr/local/include/QtGui/QGraphicsScene:1,
                 from /home/m/git/kitchensink/src/graphics/animated_tiles.h:23,
                 from /home/m/git/kitchensink/src/graphics/animated_tiles.cpp:20:
/usr/local/include/QtGui/qwidget.h:473:4: note:   initializing argument 1 of ‘void QWidget::setWindowTitle(const QString&)’
  473 |    GUI_CS_SLOT_1(Public, void setWindowTitle(const QString &title))
      |    ^~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/KitchenSink.dir/build.make:624: src/CMakeFiles/KitchenSink.dir/graphics/animated_tiles.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:114: src/CMakeFiles/KitchenSink.dir/all] Error 2
make: *** [Makefile:172: all] Error 2

**Comment by janwilmans** [comment]
Could you send us the cmake command line you used and the output of that
command?

**Comment by bgeller** [comment]
We have not pushed the changes to KitchenSink for the new translation changes. This was already set to happen later today.

**Comment by michkrom** [comment]
A simple fix was to remove the macro: 
view->setWindowTitle("Animated Tiles");

Now on to:
build/bin/kitchensink 
The application failed to start because the platform plugin was not found or did not load.
Requested Plugin Key: "xcb"

Reinstalling the application may resolve this problem.
Aborted (core dumped)

**Comment by bgeller** [comment]
After you built KitchenSink did you install?  
https://www.copperspice.com/docs/cs_overview/demo-ks.html#ks-build-script

This is usually the reason why the Platform plugin can not be found. Once you run "ninja install" as indicated in the docs you will see a folder called "platforms" in the same location as your exe file.  The platforms folder is where the plugin will be located.

**Comment by michkrom** [comment]
Ah, thanks! And also then run it from 'deploy' dir. Thanks!

**Comment by bgeller** [comment]
Commit was pushed to correct the translation issue. I will close this ticket since both issues are resolved.
