### ISSUE TITLE
QRC resources: documentation

### ISSUE THREAD

**Issue by bjaraujo** [copperspice/copperspice#194]
In your documentation:
https://www.copperspice.com/docs/cs_api/resources-c.html
https://www.copperspice.com/docs/cs_overview/cs-migration.html

I think you should mention that you need to add qrc_application.cpp to the project build. I know it is in CMake example but I missed that and didn't know why my icons weren't loading.

**Comment by bgeller** [comment]
We suggest users review the CMake build files for the KitchenSink application or the Diamond project.  We will be adding some extended examples in a future blog entry on our CopperSpice Journal. 

[journal.copperspice.com](url)
