### ISSUE TITLE
Run-time check failure in QTimeZone

### ISSUE THREAD

**Issue by jvoosten** [copperspice/copperspice#196]
Hello,

Environment: CopperSpice 1.7.1-debug (self-built), Windows 10, Visual Studio 2019

I was trying to display timestamps that were recorded as UTC in a user-selectable timezone, using QDateTime and QTimeZone. With some timezones I would get this exception:

    Run-Time Check Failure #3 - The variable 'dstMSecs' is being used without being initialized.

upon calling this code:
    
    QDateTime when = QDateTime::fromTime_t (ev.timestamp.sec, m_timezone);

Some further testing revealed this only happened with timezones that do not have daylight savings (like Africa/Addis_Ababa), except the UTC timezones, which don't have daylight saving but also do not generate the exception.

Using the PDB files I found the exception is thrown in qtimezone_p_win.cpp, function QWinTimeZonePrivate::date(), line 613. Indeed, dstMSecs is used there, but why is not initialized? 

Because it isn't. The variable is declared on line 587 but not initialized, and due to the if-statement on line 593 the call to calculateTransitionsForYear can be skipped.

Considering that regions that do not observe day light savings only have standard time, it would make sense to initialize dstMSecs to somethat that is not equal to 'next', so the final line in this function will use QTimeZone::StandardTime (and while you're at it, initialize *all* variables).

Note that the same error is repeated in the next function, QWinTimeZonePrivate::nextTransition().

**Comment by janwilmans** [comment]
Thank you for your detailed report!

**Comment by janwilmans** [comment]
Could you provide a reproduction scenario, I can probably create one from your information, but it sounds you already might have one handy?

**Comment by jvoosten** [comment]
It's literally as simple as:
    
    #include <QDateTime>
    #include <QTimeZone>

    int main(int argc, char *argv[])
    {
        QTimeZone timezone("Africa/Addis_Ababa");
        QDateTime dt = QDateTime::fromTime_t (1615141312, timezone); //< runtime failure here
        return 0;
    }

But you may have to enable Run-time checks in your build of CopperSpice (one of the /RTC flags) if not done automatically. We built CopperSpice ourselves because we wanted the PDB files, then packaged it into a Conan file.

**Comment by janwilmans** [comment]
thanks!

**Comment by agserm** [comment]
This has been resolved in b9b2b23. Thanks for reporting!
