### ISSUE TITLE
GUI_CS_SLOT_1 and CS_SLOT_1

### ISSUE THREAD

**Issue by hongnod** [copperspice/copperspice#200]
Some of my testing code(see following ) need  GUI_CS_SLOT_1 to compile, the doc of GUI_CS_SLOT_1 can't be found. Wondering what's the difference between both.
```
class PieView : public QAbstractItemView
{
    CS_OBJECT(PieView)
public:
    PieView(QWidget *parent = nullptr);

    QRect visualRect(const QModelIndex &index) const override;
    void scrollTo(const QModelIndex &index, ScrollHint hint = EnsureVisible) override;
    QModelIndex indexAt(const QPoint &point) const override;
    void setModel(QAbstractItemModel * model) override;
protected :
    GUI_CS_SLOT_1(Protected, void dataChanged(const QModelIndex & topLeft,const QModelIndex & bottomRight,const QVector <int> & roles = QVector<int>())override)
    GUI_CS_SLOT_2(dataChanged)
    GUI_CS_SLOT_1(Protected, void rowsInserted(const QModelIndex & parent,int start,int end)override)
    GUI_CS_SLOT_2(rowsInserted)
    GUI_CS_SLOT_1(Protected, void rowsAboutToBeRemoved(const QModelIndex & parent,int start,int end)override)
    GUI_CS_SLOT_2(rowsAboutToBeRemoved)
```

**Comment by bgeller** [comment]
Macros with a prefix such as CORE_CS_SLOT_X, GUI_CS_SLOT_X, etc are not documented since they are for internal use only.  

If you run PepperMill (which is our migration tool) on your source code then none of your macros would contain a prefix.  Another example is the source for KitchenSink or Diamond as user applications do not have a prefix.  Did you do the migration by hand or is this new code?

The documentation for these macros is located in our CS Overview docs: 
https://www.copperspice.com/docs/cs_overview/m_macros_metaobj.html

As side note, if you are using method pointers in your calls to connect() then you do not need to use the CS_SLOT_X macro.  You can simply declare the method as a normal method.  

Does your code not compile?  If so please give as a short description of the compiler error you are seeing, the platform you are running on, and the which version of CS you are using. 

Barbara

**Comment by hongnod** [comment]
“Did you do the migration by hand or is this new code?”
by hand, in attach.
"Does your code not compile? If so please give as a short description of the compiler error you are seeing, the platform you are running on, and the which version of CS you are using."
Compiled with Mingw8.1 and Msvc2019 both with success, but can't start the binary output.  with prefix GUI_ build and run will work.    CS ver : official release 1.7.1 on Win10

[JotDataView.zip](https://github.com/copperspice/copperspice/files/6486960/JotDataView.zip)

**Comment by bgeller** [comment]
Please let us know the run time error you are seeing.

Thanks, 

Barbara

**Comment by hongnod** [comment]
None run time error I can see.

**Comment by bgeller** [comment]
Very confused.  If there are no errors then how do you know it is not working. We really need a lot more information. 

1   If you have no run time issue, than what do you expect to see?  
2   What is this code supposed to do? 
3   Are you making changes to the CopperSpice Gui library?
4   Is this a user application?  e 
5   Is this a demo of something? 

Can you please send us a zip of the CMake files you used to build this project.

**Comment by hongnod** [comment]
> Very confused. If there are no errors then how do you know it is not working? We really need a lot more information.
> 
> 1 If you have no run time issue, than what do you expect to see?
   It Just start without a window,
> 2 What is this code supposed to do?
    Just for testing.
> 3 Are you making changes to the CopperSpice Gui library?
   No, I used the official release package.
> 4 Is this a user application? 
   No, I made it for learning, I will upload it to github for investigation.
> 5 Is this a demo of something?
  
[CsJotPath.zip](https://github.com/copperspice/copperspice/files/6490229/CsJotPath.zip)



> 
> Can you please send us a zip of the CMake files you used to build this project.

**Comment by bgeller** [comment]
We believe you are creating a User Application to test CopperSpice, which is wonderful. 

I can guarantee 100% that you must **not** use the GUI prefix in your user application.  Once you remove it then compile and let us know exactly what error you get at run time.  If you are not getting an error then you will need to debug your project by adding some test messages. Find out where your program stops working. 

We suggest that you start by building a current version of our KitchenSink demo and verify it starts and all the demos work.  Then change a smaller part of KS to test sections of your application. 

If sounds like you may have some general C++ programming questions and our team is very happy to assist or even debug your application for you.  If you would like to go this route please let us know and we can set up a support subscription. 

Barbara

**Comment by hongnod** [comment]
It's a stupid mistake: override member can not be a CS_SLOT.
