### ISSUE TITLE
Unit test CsCoreTest:QTIme failing (but perhaps it just depends on locale)

### ISSUE THREAD

**Issue by j-silver** [copperspice/copperspice#203]
Follow up from [issue 198](https://github.com/copperspice/copperspice/issues/198).

On Fedora 34, after building Copperspice with its default compiler gcc (GCC) 11.1.1 20210531 (Red Hat 11.1.1-3), just one of the 478 tests fails with the following output:

```
The following tests FAILED:
	145 - CsCoreTest:QTime to_string (Failed)
Errors while running CTest
Output from these tests are in: /home/giuseppe/Downloads/sources/copperspice/cmake-build-release/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
FAILED: CMakeFiles/test.util 
cd /home/giuseppe/Downloads/sources/copperspice/cmake-build-release && /usr/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
```

By running `ctest --rerun-failed --output-on-failure` I get the more detailed output:

```
Test project /home/giuseppe/Downloads/sources/copperspice/cmake-build-release
    Start 145: CsCoreTest:QTime to_string
1/1 Test #145: CsCoreTest:QTime to_string .......***Failed    0.01 sec
Filters: QTime to_string

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CsCoreTest is a Catch v2.13.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
QTime to_string
-------------------------------------------------------------------------------
../test/core/datetime/qtime.cpp:75
...............................................................................

../test/core/datetime/qtime.cpp:86: FAILED:
  REQUIRE( str == QString("3:9:05 PM") )
with expansion:
  3:9:05 P.M. == 3:9:05 PM

===============================================================================
test cases: 1 | 1 failed
assertions: 2 | 1 passed | 1 failed



0% tests passed, 1 tests failed out of 1

Label Time Summary:
CsCoreTest    =   0.01 sec*proc (1 test)
qtime         =   0.01 sec*proc (1 test)

Total Test time (real) =   0.03 sec

The following tests FAILED:
	145 - CsCoreTest:QTime to_string (Failed)
Errors while running CTest
```

I've tried running it with the LC_ALL environment variable set to "C":

`env LC_ALL=C ctest --rerun-failed --output-on-failure`

```
Test project /home/giuseppe/Downloads/sources/copperspice/cmake-build-release
    Start 145: CsCoreTest:QTime to_string
1/1 Test #145: CsCoreTest:QTime to_string .......   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
CsCoreTest    =   0.01 sec*proc (1 test)
qtime         =   0.01 sec*proc (1 test)

Total Test time (real) =   0.05 sec
```

Note that my LC_ALL is unset in my terminal, while other related environment variables are set to en_GB.UTF-8

```
locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

So perhaps this is not a bug, just something arising from a specific locale.

**Comment by bgeller** [comment]
Thanks so much for the detailed report.  This was great detective work and it does appear to be a locale dependent issue.  We were able to repeat this and now we need to modify the unit test to explicitly state the locale.

**Comment by agserm** [comment]
We have made several changes to the CopperSpice locale system. Can you please retest this issue using CopperSpice 1.8.2?

**Comment by j-silver** [comment]
Hello, I'm now using Fedora 38 with bundled gcc and standard libraries:

gcc (GCC) 13.1.1 20230511 (Red Hat 13.1.1-2)

The build stops with the same error mentioned in issue https://github.com/copperspice/copperspice/issues/269: not finding the declaration of `intmax_t`

See below:


FAILED: src/core/CMakeFiles/CsCore.dir/xml/qxmlutils.cpp.o 
/usr/lib64/ccache/c++ @src/core/CMakeFiles/CsCore.dir/xml/qxmlutils.cpp.o.rsp -MD -MT src/core/CMakeFiles/CsCore.dir/xml/qxmlutils.cpp.o -MF src/core/CMakeFiles/CsCore.dir/xml/qxmlutils.cpp.o.d -o src/core/CMakeFiles/CsCore.dir/xml/qxmlutils.cpp.o -c /home/giuseppe/Downloads/sources/copperspice/src/core/xml/qxmlutils.cpp
In file included from /home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/regex_traits.h:33,
                 from /home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/regex.h:36,
                 from /home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/qregularexpression.h:27,
                 from /home/giuseppe/Downloads/sources/copperspice/src/core/xml/qxmlutils.cpp:24:
/home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/regex_traits_defaults.h:133:1: error: ‘intmax_t’ does not name a type; did you mean ‘int8_t’?
  133 | intmax_t global_toi(typename traits::string_type::const_iterator &p1, const typename traits::string_type::const_iterator p2,
      | ^~~~~~~~
      | int8_t
/home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/regex_traits.h:82:4: error: ‘intmax_t’ does not name a type; did you mean ‘int8_t’?
   82 |    intmax_t toi(typename string_type::const_iterator &p1, const typename string_type::const_iterator p2, int radix) const {
      |    ^~~~~~~~
      |    int8_t
In file included from /home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/regex.h:40:
/home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/basic_regex_parser.h: In instantiation of ‘bool cs_regex_ns::cs_regex_detail_ns::basic_regex_parser<charT, traits>::parse_extended_escape() [with charT = QChar32; traits = QRegexTraits<QString8>]’:
/home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/basic_regex_parser.h:339:17:   required from ‘bool cs_regex_ns::cs_regex_detail_ns::basic_regex_parser<charT, traits>::parse_extended() [with charT = QChar32; traits = QRegexTraits<QString8>]’
/home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/basic_regex_parser.h:140:26:   required from ‘void cs_regex_ns::cs_regex_detail_ns::basic_regex_parser<charT, traits>::parse(typename traits::string_type::const_iterator, typename traits::string_type::const_iterator, unsigned int) [with charT = QChar32; traits = QRegexTraits<QString8>; typename traits::string_type::const_iterator = QString8::const_iterator; typename traits::string_type = QString8]’
/home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/basic_regex.h:230:19:   required from ‘void cs_regex_ns::cs_regex_detail_ns::basic_regex_implementation<charT, Traits>::assign(typename Traits::string_type::const_iterator, typename Traits::string_type::const_iterator, flag_type) [with charT = QChar32; Traits = QRegexTraits<QString8>; typename Traits::string_type::const_iterator = QString8::const_iterator; typename Traits::string_type = QString8; flag_type = unsigned int]’
/home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/basic_regex.h:558:16:   required from ‘cs_regex_ns::basic_regex<charT, traits>& cs_regex_ns::basic_regex<charT, traits>::do_assign(typename traits::string_type::const_iterator, typename traits::string_type::const_iterator, flag_type) [with charT = QChar32; Traits = QRegexTraits<QString8>; typename traits::string_type::const_iterator = QString8::const_iterator; typename traits::string_type = QString8; flag_type = unsigned int]’
/home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/regex/basic_regex.h:367:14:   required from ‘cs_regex_ns::basic_regex<charT, traits>& cs_regex_ns::basic_regex<charT, traits>::assign(typename Traits::string_type::const_iterator, typename Traits::string_type::const_iterator, flag_type) [with charT = QChar32; Traits = QRegexTraits<QString8>; typename Traits::string_type::const_iterator = QString8::const_iterator; typename Traits::string_type = QString8; flag_type = unsigned int]’
/home/giuseppe/Downloads/sources/copperspice/cmake-build-release/include/QtCore/qregularexpression.h:778:21:   required from ‘void Cs::QRegularExpression<S>::setPattern(const S&) [with S = QString8]’

(trimmed here, because I don't know how to disable markdown, which makes a strikethrough of the log message)

**Comment by bgeller** [comment]
> The build stops with the same error, not finding the declaration of intmax_t

A new release of CopperSpice was posted yesterday so now we can focus on updates. Fedora 37 was added to our CI server and we are building **successfully** with gcc 12 and clang 13. The following link is the full list of the currently supported and tested platforms and compiler versions.   

https://www.copperspice.com/docs/cs_overview/supported-platforms.html

We are about to update the Arch platform to the latest rolling release. This will add support for gcc 13.

**Comment by bgeller** [comment]
Closing as this issue has been resolved.
