### ISSUE TITLE
Do we must open source the code linked with copperspise libraries?

### ISSUE THREAD

**Issue by tonyho** [copperspice/copperspice#204]
As CS is LGPL, so if we make a program linked with copperspice, do we need to open source it?

Or can we use it just like the wxWidget/GTK without open source?

**Comment by agserm** [comment]
Thanks for your interest in CopperSpice.

CopperSpice is released under the LGPL 2.1 license. Any library which is released under this exact license can be used in a closed source or open source program. Just to be clear, with our license you are not required to release your source code

GTK is also under the LGPL 2.1 license. However it is worth noting that wxWidgets does not use an LGPL license. 

There is another part about LGPL that developers often miss and it is not difficult to satisfy. If you change CopperSpice itself you must either upstream these changes or make them available to your clients.

If you have any other questions please let us know.

**Comment by tonyho** [comment]
> Thanks for your interest in CopperSpice.
> 
> CopperSpice is released under the LGPL 2.1 license. Any library which is released under this exact license can be used in a closed source or open source program. Just to be clear, with our license you are not required to release your source code
> 
> GTK is also under the LGPL 2.1 license. However it is worth noting that wxWidgets does not use an LGPL license.
> 
> There is another part about LGPL that developers often miss and it is not difficult to satisfy. If you change CopperSpice itself you must either upstream these changes or make them available to your clients.
> 
> If you have any other questions please let us know.

Got it, thanks.
