### ISSUE TITLE
QCompleter popup does not obey arrow key inputs whatsoever (on win32 MSVC).

### ISSUE THREAD

**Issue by gdianaty** [copperspice/copperspice#205]
Hello! In working with CopperSpice's `QCompleter` recently on MSVC-win32 v142, I encountered some odd behavior when trying to navigate the QCompleter's choices with arrow keys. It appears as if the arrow keys are being treated as a request by the user to complete the given line, instead of navigate the popup's choices (or navigate the inline options).

https://user-images.githubusercontent.com/9407540/127545571-8ee460ae-d285-4edf-ac83-4d4729bba40f.mp4

This issue can only be reproduced on a win32 version of CopperSpice 1.7.2 compiled on MSVC. 
The bug does not occur on x64 MSVC versions of CopperSpice 1.7.2 and it does not occur on Qt 5.9.9 whatsoever.
Here is a table for the sake of brevity:

**Toolset:**|**Works?**
:-----:|:-----:
CopperSpice 1.7.2 on MSVC-v142-win32|No ❌
CopperSpice 1.7.2 on MSVC-v142-win64|Yes ✔
Qt 5.9.9 on MSVC-v142-win32|Yes ✔
Qt 5.9.9 on MSVC-v142-win64|Yes ✔

I have not tested for this aberrational behavior on any other compiler or toolset.

# Reproduction Sample

The following block of code has been used in all of my testing:
```cpp
#include <QMainWindow>
#include <QApplication>
#include <QLineEdit>
#include <QCompleter>
#include <QLineEdit>

int main(int argc, char* argv[])
{
	QApplication app(argc, argv);

	QStringList strList;
	strList.append("dalek_caan");
	strList.append("dalek_sec");
	strList.append("dalek_thay");
	strList.append("dalek_jast");

	QLineEdit* pLineEdit = new QLineEdit();
	QCompleter* pCompleter = new QCompleter(strList);
	pCompleter->setCompletionMode(QCompleter::PopupCompletion);
	pLineEdit->setCompleter(pCompleter);
	pLineEdit->show();

#ifdef CS_VERSION
	pLineEdit->setWindowTitle("CopperSpice QCompleter PopupCompletion Demo");
#else
	pLineEdit->setWindowTitle("Qt QCompleter PopupCompletion Demo");
#endif

	return app.exec();
}
```

Any help you could offer would be much appreciated! If you'd like, I can share my locally compiled version of CopperSpice 1.7.2 for MSVC-win32-v142, if that would be any help at all.

**Comment by agserm** [comment]
Thank you for your very detailed report, and your list of sample strings really made me laugh. Very cool.

Whether this works in Qt is not something we can really address, particularly because we cannot look at or reference any release past Qt 5.6 since they changed to LGPL 3. However, the fact that CopperSpice works differently depending on the target platform is definitely something we want to look into.

We will test this on 32-bit MSVC as well as some additional platforms and follow up when we have more information.

**Comment by gdianaty** [comment]
Thanks so much for looking into it! Good to hear it's being worked on. And, I'm glad to see you noticed my very silly sample string set. My sample strings were inspired by your own sample strings in KitchenSink, which was part of the factors that motivated me to consider using CopperSpice. It's good to see other geeks out in the wild.

Also, thanks for the info about Qt's newer versions. You learn something new every day!

**Comment by agserm** [comment]
Following up to let you know that we have been able to use your test case to confirm this also does not happen on Debian 64-bit, so this does appear to be something unique to the MSVC 32-bit. We're continuing to look at the 32-bit build to find out what the issue is.

**Comment by gdianaty** [comment]
Strange. Thanks for the update, and for looking into it!

**Comment by gdianaty** [comment]
After recompiling from a freshly-cloned copy of CopperSpice's codebase, and testing it this morning, the issue appears to have vanished from all my test cases and my deployed applications. Cheers!
