### ISSUE TITLE
ApiDoc: CS_VERSION explanation uses wrong version numbers

### ISSUE THREAD

**Issue by SvenRoederer** [copperspice/copperspice#206]
On  https://www.copperspice.com/docs/cs_api/group__qglobal-c.html#gac54999f9a4982b207620d5aeea0a15e8 is written for the CS_VERSION macro:

> This macro expands a numeric value of the form 0xMMNNPP (MM = major, NN = minor, PP = patch) that specifies the CopperSpice version number. For example, if you compile your application using CopperSpice 1.7.0, the CS_VERSION macro will expand to 0x010402.

But it should be "using CopperSpice 1.7.0, the CS_VERSION macro will expand to 0x010700", right?

**Comment by agserm** [comment]
Thanks for reporting this, and you are absolutely correct in your understanding of the CS_VERSION macro. We will update the docs. If you find anything else, please let us know!
