### ISSUE TITLE
Switching tabs in QTabWidget causes tabs to vanish in a seemingly random order (MSVC-x32)

### ISSUE THREAD

**Issue by gdianaty** [copperspice/copperspice#207]
In some recent experiments with the QTabWidget class in CopperSpice, I discovered it is effectively unusable on CopperSpice MSVC-x32. The tab entries appear to randomly vanish when their peers are clicked.

Here is a table for the sake of brevity:
**Toolset:**|**Works?**
:-----:|:-----:
CopperSpice 1.7.2 on MSVC-v142-win32|No ❌
CopperSpice 1.7.2 on MSVC-v142-win64|Yes ✔

# Video Demonstrations
Below are some demonstrations of the functionality in question.

## CopperSpice 1.7.2 win32 (Not Working ❌)

https://user-images.githubusercontent.com/9407540/128644677-0e3d1a79-fa88-42e6-8124-f6f753ce0ab2.mp4

## CopperSpice 1.7.2 win64 (Working ✔)

https://user-images.githubusercontent.com/9407540/128644674-e65d1344-a75a-47cf-b6ad-ad55dbee9de3.mp4

# Reproduction Sample
According to my testing, any use of QTabWidget on CopperSpice 1.7.2, MSVC-v142-win32 causes this behavior. The below code has been used in all of my testing:

```cpp
#include <QMainWindow>
#include <QApplication>
#include <QTabWidget>
#include <QLabel>

int main(int argc, char* argv[])
{
	QApplication app(argc, argv);

	QTabWidget* pTabs = new QTabWidget();
	pTabs->addTab(new QLabel("UNUS"), "One");
	pTabs->addTab(new QLabel("DUO"), "Two");
	pTabs->addTab(new QLabel("TRES"), "Three");
	pTabs->addTab(new QLabel("QUATTUOR"), "Four");
	pTabs->addTab(new QLabel("QUINQUE"), "Five");
	pTabs->show();

	return app.exec();
}
```

# FInal Notes

I also feel somewhat (and this is purely assumptive) that this bug may be related to my previous ticket, #205, as it can only be found on MSVC-win32 builds of CopperSpice.

Cheers!

**Comment by bgeller** [comment]
We have been unable to reproduce this issue on any platform.  We are very curious if there is something different about how you are building CopperSpice on MSVC.

**Comment by gdianaty** [comment]
After recompiling from a freshly-cloned copy of CopperSpice's codebase, and testing it this morning, the issue appears to have vanished from all my test cases.

Apologies for my delay in closing this ticket! Thanks so much for your help! Cheers.
