### ISSUE TITLE
QFileDialog::getOpenFileName() does not return anything (MSVC-x32)

### ISSUE THREAD

**Issue by gdianaty** [copperspice/copperspice#208]
When I first started using CopperSpice I discovered this bug, but decided to test it (and subsequently report my findings) today given my recent volley of other reports (#207, #205).

QFileDialog::getOpenFileName() simply returns nothing whatsoever. Even when the selected path is valid, it returns an empty string. However, the underlying QFileDialog class functions just fine (and I have written a workaround, that I will happily provide if I'm asked to do so).

Here is a table for the sake of brevity:
**Toolset:**|**Works?**
:-----:|:-----:
CopperSpice 1.7.2 on MSVC-v142-win32|No ❌
CopperSpice 1.7.2 on MSVC-v142-win64|Yes ✔

# Video Demonstrations
Below are some demonstrations of the functionality in question. Apologies for the redactions, the solution I am testing x32 CopperSpice in contains sensitive information.

## CopperSpice 1.7.2 win32 (Not Working ❌)

https://user-images.githubusercontent.com/9407540/128645605-66f315b2-5d99-4ffe-9553-f4160236acb7.mp4

## CopperSpice 1.7.2 win64 (Working ✔)

https://user-images.githubusercontent.com/9407540/128645602-31cd3056-5c0f-4ff6-880d-3c80d2edeedb.mp4

# Reproduction Sample
According to my testing, any use of this function on CopperSpice 1.7.2, MSVC-v142-win32 causes this behavior. The below code has been used in all of my testing:

```cpp
#include <QMainWindow>
#include <QApplication>
#include <QFileDialog>
#include <QMessageBox>

int main(int argc, char* argv[])
{
	QApplication app(argc, argv);

	QString str = QFileDialog::getOpenFileName();

	QMessageBox::about(NULL, "QFileDialog::getOpenFileName() result", str);

	return app.exec();
}
```

# FInal Notes

It feels a bit repetitive but, this could perhaps be related to #207 and #205.

Cheers!

**Comment by bgeller** [comment]
As a follow up we have *not* been able to repeat this issue on MSVC 32-bit or any other platform. 

What we did find was that opening a non-native QFileDialog with MSVC 32-bit causes a crash.  You can test this in KitchenSink from Samples, Standard Dialogs.  You would need to un-check the "Use Native Dialogs".  Have you tested from this code? 

Can you tell us the exact version of MSVC you are using and the exact step you used to build CS and your application.

**Comment by agserm** [comment]
Closing due to no response, please reopen if more information is available.
