### ISSUE TITLE
libCSGui1.7 isn't Found

### ISSUE THREAD

**Issue by wwderw** [copperspice/copperspice#210]
Cmake and Ninja went along fine.  The libs and the binary all went where they were supposed to go, but on my 20.04 dev computer, it couldn't find that lib.  I imagine that it wouldn't be able to find the 2 other libs that my app uses as well (core and multimedia), it just focused on this one at the this time.

I have on my CMakeLists.txt:
set(Copperspice_DIR 'path/to/cmake/CopperSpice' )
find_package(Copperspice REQUIRED)

target_link_libraries(program
                   Copperspice::CsCore
                   CopperSpice::CsGui
                   CopperSpice::CsMultimedia
                   )
cs_copy_library(CsCore)
cs_copy_library(CsGui)
cs_copy_library(CsMultimedia)

My cmake file has more, but those are the lines that I specifically reference cs.  
Is there something that I am missing here?

**Comment by wwderw** [comment]
> We do not have enough information and we need answers to the following questions
> 
> 1 Did you build CS from source or download the binaries?
For all programs, I used the already compiled binaries, I wanted to minimize any outside errors that I may bring into the equation (I know enough just to cause damage).

> 
> 2 Did you look at the KitchenSink CMake build files as a guide? This might help you figure out which step you missed.

Yes, I did.  That and the Diamond CMake as well, just to make sure, I tried to pull from different sources as my CMake is nowhere near as verbose as y'alls.  I must confuse, my knowledge of CMake isn't the best (and I'm being kind with that assessment).
> 
> 3 Please provide the exact commands you ran to configure and run CMake.

cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/Music/ -DCMAKE_PREFIX_PATH=$HOME/Downloads/copperspice/lib .
> 
> 4 When you ran "ninja install" for your project where did the files get installed to? What is the exact folder name?

I just had it go to my Music directory in $HOME.  I don't use it for anything else and it's easy enough for me to just extract it there and go on about my business.
> 
> 5 In your prior post you said "CsGui" is there but then you also said you do not have "libCsGui1.7.so". This is a bit confusing since we have no files without an extension.
![CSFiles](https://user-images.githubusercontent.com/24878362/137829830-cf027c6b-7d9d-4954-b480-eb4d116f686b.png)

The files are physically in the folder, when I try to run ldd or when I try to run the program via CLI, it says that it isn't there.  Physically it's there (at least what's in the screenshot is there, that may or may not be the correct one that I truly need) where it should be, or rather where I told it to go (which may or may not have been the correct place for it to go).

> 
> 6 As I mentioned, It would really help if you would provide a full listing of the install folder for your application.
The screenshot is everything that GCC spits out for my compiled application.

**Comment by bgeller** [comment]
>-DCMAKE_INSTALL_PREFIX=$HOME/Music/   

This is not a good value for a prefix.  We strongly suggest you change this to something like **$HOME/Projects/deploy**.  

Screenshots are too hard to read, this is why we asked for a listing in a text file. 

It really seems like you have left out some commands in your CMake files. The best way for you to figure this out is to build and install KitchenSink.  This way you will see what the deploy folder should look like. 

Then use the KS build files and comment things out one at a time to build and install your project. 

I understand that CMake can be complicated which is why we created a working demo as a place for you to start. 

Barbara

**Comment by agserm** [comment]
CS Deployment is working, please reopen if you have additional information on this issue.
