### ISSUE TITLE
CopperSpice application tries to load Qt plugins

### ISSUE THREAD

**Issue by srnwk** [copperspice/copperspice#212]
When I accidentally ran a CopperSpice application from the same directory that a Qt application & its plugins where residing in,
I got messages like these in the output of the CopperSpice application:

```
resolve_sys(): Unable to resolve symbol "cs_internal_plugin_metaobject" in D:/Example/platforms/qwindows.dll. The specified procedure could not be found.
updatePluginState(): Unable to retrieve the meta object for the D:/Example/platforms/qwindows.dll plugin
QWindowsContext::setProcessDpiAwareness(): Dpi = 2
resolve_sys(): Unable to resolve symbol "cs_internal_plugin_metaobject" in D:/Example/styles/qwindowsvistastyle.dll. The specified procedure could not be found.
updatePluginState(): Unable to retrieve the meta object for the D:/Example/styles/qwindowsvistastyle.dll plugin
resolve_sys(): Unable to resolve symbol "cs_internal_plugin_metaobject" in D:/Example/iconengines/qsvgicon.dll. The specified procedure could not be found.
updatePluginState(): Unable to retrieve the meta object for the D:/Example/iconengines/qsvgicon.dll plugin
```

It appears CopperSpice still tries to load the Qt plugins.
I wanted to ask:
1) Is this intentional? (All the other CopperSpice libraries and DLLs are prefixed with Cs instead of Q, why is it looking for plugins prefixed with Q?)
2) Does this have any consequences? For now I just make sure to avoid having Qt and CopperSpice applications in the same directory, but it would good to know if this is something to watch out for in general.

**Comment by bgeller** [comment]
Thank you for your question.  When a CS application starts it will look at every DLL in the current path and associated folders.  You are correct that our plugin files start with "Cs" but a user is free to name their plugin files any way they want. In fact, I would recommend and expect that users would not use a "CS" prefix to avoid possible conflicts. 

Yes, it would be advisable not to have a CS and Qt application in the same folder. 

Barbara

**Comment by srnwk** [comment]
> When a CS application starts it will look at every DLL in the current path and associated folders.
Ah, understandable.

> Yes, it would be advisable not to have a CS and Qt application in the same folder.
Thanks for confirming!
