### ISSUE TITLE
Switch to winlibs.com GCC

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/copperspice#218]
From this document it seems the MinGW being used is rather old.

https://www.copperspice.com/documentation-mingw.html

The MinGW-Builds project on sourceforge no longer provide up to date MinGW builds anymore.

Winlibs.com provides latest MinGW builds. UCRT MinGW is also supported.

https://winlibs.com/

**Comment by bgeller** [comment]
The CopperSpice team is investigating the process for building an updated version of msys and new versions of the MinGW compiler.
