### ISSUE TITLE
Switch to MSYS2 to build CopperSpice

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/copperspice#219]
I confirm MSYS2 works. From the documents here it seems MSYS is still used with a rather old MinGW build.

https://www.copperspice.com/docs/cs_overview/build-win.html

https://www.copperspice.com/documentation-mingw.html

MSYS + Winlibs.com MinGW still works. But MSYS2 is a better suite. It's a complete environment and you don't have to install MSYS and MinGW separately as before.

https://www.msys2.org/wiki/MSYS2-installation/

MSYS2 also has Clang and UCRT based MinGW.

https://www.msys2.org/docs/environments/

Please consider.

**Comment by bgeller** [comment]
As per our documentation building CS with msys2 is not supported since they have a rolling release and up supported changes to upstream packages. 

The CopperSpice team is investigating the process for building an updated version of msys and new versions of the MinGW compiler.
