### ISSUE TITLE
How to disable CsScript build?

### ISSUE THREAD

**Issue by hongnod** [copperspice/copperspice#221]
There is no  build option for CsScript in  page: https://www.copperspice.com/docs/cs_overview/build-options.html ,I wander how to disable CsScript build.

**Comment by bgeller** [comment]
If you want to turn of CsScript you will also need to turn off CsWebkit since CsScript is a dependency. 

Add this line to your CMake configuration:  -DWITH_SCRIPT=NO  -DWITH_WEBKIT=NO

**Comment by hongnod** [comment]
Thanks!

**Comment by bgeller** [comment]
Closing since this has been resolved.
