### ISSUE TITLE
Extending .gitignore for Qt Creator

### ISSUE THREAD

**Issue by stefanos82** [copperspice/copperspice#224]
Is it possible to extend `.gitignore` to ignore the following files `Qt Creator` when we import an existing project?

```
*.cflags
*.config
*.creator
*.creator.user
*.creator.user.*
*.cxxflags
*.files
*.includes
```

**Comment by agserm** [comment]
Can you tell us a little more about your use case? 

1) How are you opening the project in `Qt Creator`?
2) Why are you opening CopperSpice in an IDE - is it just to build or are you making changes?
3) You can set up additional ignore files in a user or repository specific git ignore file. You can put it in a global location using `core.excludesFile`, but it would probably be better to use the repository specific `<git-repo>/.git/info/exclude` file. See https://git-scm.com/docs/gitignore for more details.

**Comment by janwilmans** [comment]
in either case you could create a global
.gitignore file (in your home directory) so the rules apply over mulitple
projects.

**Comment by stefanos82** [comment]
>     2. Why are you opening CopperSpice in an IDE - is it just to build or are you making changes?

Basically I want to open copperspice inside Qt Creator so I can study the whole framework for research purposes.

> 
>     3. You can set up additional ignore files in a user or repository specific git ignore file. You can put it in a global location using `core.excludesFile`, but it would probably be better to use the repository specific `<git-repo>/.git/info/exclude` file.

Ah, I forgot about this option; I thought I had to edit `.gitignore` inside copperspice repo directory to add my ignore list.

Thank you @agserm for the reminder and @janwilmans for the suggestions.
