### ISSUE TITLE
The recommended way to edit UI files

### ISSUE THREAD

**Issue by kogiokka** [copperspice/copperspice#227]
I've come across this documentation saying there is a  [CS Designer Application](https://www.copperspice.com/docs/cs_api/tools-designer.html). But I couldn't find it anywhere on the CopperSpice download page or GitHub. Has the project been discontinued? If so, what is the recommended way to edit UI files?

**Comment by bgeller** [comment]
We are very excited about the CS Designer application. It was started in January 2022 and is entering public beta this week. We published the documentation in advance of the full release which is expected in early May.

**Comment by kogiokka** [comment]
That sounds fantastic! I am looking forward to it.

**Comment by bgeller** [comment]
The CS Designer beta is now official and open to beta testers. If this something you are interested in and have the time, please let us know.
