### ISSUE TITLE
Copperspice failed to msbuild with fatal error C1189: #error:  Unable to detect system architecture, contact CopperSpice development with MSVC on windows arm64

### ISSUE THREAD

**Issue by spacelg** [copperspice/copperspice#228]
Hi All,

Environment:
VS 2019 + Windows Server 2019

Copperspice failed to msbuild with fatal error C1189: #error:  Unable to detect system architecture, contact CopperSpice development with MSVC on windows arm64. Does Copperspice support windows arm64? Could you please help look at this issue?

Repro steps:
1. git clone https://github.com/copperspice/copperspice.git F:\gitP\copperspice\copperspice
2. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. set _CL_=/wd4251 /wd4244 /wd4291 /wd4018 /wd4275 /wd4250 /wd4996
4. cd F:\gitP\copperspice\copperspice && mkdir build_arm64
5. cd build_arm64
6. cmake -G "Visual Studio 16 2019" -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=aarch64 -A arm64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release ..
7. msbuild /m /p:Platform=arm64 /p:Configuration=Release copperspice.sln /t:Rebuild

Build log: 
[build_arm64.zip](https://github.com/copperspice/copperspice/files/8462243/build_arm64.zip)

Errors:
26>F:\gitP\copperspice\copperspice\src\core\global\qglobal.h(132,1): fatal error C1189: #error:  Unable to detect system architecture, contact CopperSpice development (compiling source file F:\gitP\copperspice\copperspice\src\core\concurrent\qfutureinterface.cpp) [F:\gitP\copperspice\copperspice\build_arm64\src\core\CsCore.vcxproj]
    26>F:\gitP\copperspice\copperspice\src\core\global\qglobal.h(132,1): fatal error C1189: #error:  Unable to detect system architecture, contact CopperSpice development (compiling source file F:\gitP\copperspice\copperspice\src\core\codecs\qtextcodec.cpp) [F:\gitP\copperspice\copperspice\build_arm64\src\core\CsCore.vcxproj]
         qrunnable.cpp
    26>F:\gitP\copperspice\copperspice\src\core\global\qglobal.h(132,1): fatal error C1189: #error:  Unable to detect system architecture, contact CopperSpice development (compiling source file F:\gitP\copperspice\copperspice\src\core\concurrent\qfuturewatcher.cpp) [F:\gitP\copperspice\copperspice\build_arm64\src\core\CsCore.vcxproj]
         qtconcurrentexception.cpp
    26>F:\gitP\copperspice\copperspice\src\core\global\qglobal.h(132,1): fatal error C1189: #error:  Unable to detect system architecture, contact CopperSpice development (compiling source file F:\gitP\copperspice\copperspice\src\core\codecs\qisciicodec.cpp) [F:\gitP\copperspice\copperspice\build_arm64\src\core\CsCore.vcxproj]
    26>F:\gitP\copperspice\copperspice\src\core\global\qglobal.h(132,1): fatal error C1189: #error:  Unable to detect system architecture, contact CopperSpice development (compiling source file F:\gitP\copperspice\copperspice\src\core\codecs\qlatincodec.cpp) [F:\gitP\copperspice\copperspice\build_arm64\src\core\CsCore.vcxproj]

**Comment by bgeller** [comment]
We can confirm that CopperSpice builds on ARM64 for OS X M1 hardware.  

1  Can you confirm what hardware you are building on. It looks like this is X86_64.  

2  Can you confirm you are trying to build CS to run on ARM64 Windows. 

Windows ARM64 is not currently a supported platform at this time. If you would like to work with our team to add this support please let us know. The first place to start looking is in /src/core/global/qglobal.h. 

Barbara

**Comment by bgeller** [comment]
Closing issue due to lack of response by submitter.  Please re-open if you have additional information.
