### ISSUE TITLE
Wrong `QLocale` behavior, possible wrong data in qlocale_data_p.h

### ISSUE THREAD

**Issue by informeti** [copperspice/copperspice#236]
When setting a Locale manually, and converting a float to a string afterwards, the conversion uses wrong characters for the group and decimal symbols:

```cpp
  // System locale: in this case, de_DE
  const QLocale loc0;

  [[maybe_unused]] const QString goodFirst = loc0.toString(1234.56f); // 1.234,56 -> OK
  [[maybe_unused]] const QString  goodSecond = loc0.toString(1234567);  // 1.234.567 -> OK

  // Now, set the german locale explicitly
  QLocale::setDefault(QLocale::German);

  // Locale which was manually set to german
  const QLocale loc;

  [[maybe_unused]] const QString  badFirst = loc.toString(1234.56f); // 1,234.56 -> NOK
  [[maybe_unused]] const QString  badSecond = loc.toString(1234567);  // 1,234,567 -> NOK
```

I reproduced this by setting the locale to de_DE and fr_FR, but I fear it affects _all_ locales.

I found out that when creating a locale which is not the system locale, CopperSpice actually performs a lookup in a static table, `static const QLocaleData locale_data[]`.

The source of this table - which, according to the comments, is generated - starts here:
https://github.com/copperspice/copperspice/blob/master/src/core/locale/qlocale_data_p.h#L1198

If you look at its data, you'll notice the 4th (decimal) and 5th (group) columns _always_ define 44 (comma) and 46 (period) respectively.

**If I interpret this correctly, the data in qlocale_data_p.h is wrong**:
de_DE, fr_Fr, and many other locales use a comma as a decimal symbol, and a period as a grouping symbol.

PS: I only verified decimal and grouping symbols, I haven't verified other data like date formats yet.

**Comment by bgeller** [comment]
Thanks for reporting this issue. We have it on our schedule to look at this next week. 

Barbara

**Comment by bgeller** [comment]
The CLDR data for handling the group separator and decimal symbol has been corrected. Thank you for being patient while the problem was tracked down.  The modification to the locale files were made in SHA e4f9b27.  Please open a new issue if you find any other locale problems. 

Barbara
