### ISSUE TITLE
Cygwin's MinGW Cross Compiler

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/copperspice#237]
Cygwin has a MinGW Cross Compiler (it's MinGW GCC not Cygwin GCC, it's the same thing as MinGW compiler and the binary compiled by it doesn't link with cygwin-1.dll). Unfortunately CopperSpice build script doesn't work with this compiler.

This command doesn't work:

`CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/cslib ..`

The platform still being detected as Cygwin 64 bit and the build failed because CopperSpice doesn't support Cygwin GCC. Let it be clear, the GCC is being used here is the MinGW Cross Compiler, not Cygwin GCC. So the build script should be updated.

**Comment by bgeller** [comment]
We noticed you closed this ticket without a comment. If you were compiling with MinGW then there is no reason it should not work.  

Did you get this working?  If not, did you have a full error report you can email to us?  We can not update our build process until we know what the exact error is. 

Barbara

**Comment by 3oheicrw** [comment]
> We noticed you closed this ticket without a comment. If you were compiling with MinGW then there is no reason it should not work.
> 
> Did you get this working? If not, did you have a full error report you can email to us? We can not update our build process until we know what the exact error is.
> 
> Barbara

It's Mingw but Mingw cross compiler, cross compiled from Cygwin host to Windows native. You should think it's the same as cross compile from Linux host to Windows. I closed it simply because I do not need it to be resolved anymore, it's still there. Describing it for you to understand what I'm talking about is hard enough. Just use MSYS2 for an easier life. Bye.
