### ISSUE TITLE
Just a thought

### ISSUE THREAD

**Issue by hongnod** [copperspice/copperspice#240]
Can be there a Rust version CS? I mean native Rust, not a wrap.

**Comment by hongnod** [comment]
close it

**Comment by agserm** [comment]
Adding a reply for clarity and history.

The CopperSpice libraries were written in C++ and therefore can only be used with an application which links with C++. 

Bindings can be created in another language for any classes in CS which map to the other language. This is doable but it can take a lot of work to set up and not every computer language supports binding to C++.   

If someone wanted to rewrite a version of CopperSpice in Rust they would most likely need to implement it from scratch.
