### ISSUE TITLE
optional': is not a member of 'std'

### ISSUE THREAD

**Issue by hongnod** [copperspice/copperspice#242]
cmakelist.txt:
```
cmake_minimum_required(VERSION 3.16 FATAL_ERROR)
project(JotPath  LANGUAGES CXX)

include(CheckCXXCompilerFlag)
include(CheckCXXSourceCompiles)
include(CheckIncludeFile)
include(CheckIncludeFiles)
include(CheckTypeSize)
if(MSVC)
   # use defaults
   add_compile_options("$<$<C_COMPILER_ID:MSVC>:/utf-8>")
   add_compile_options("$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
elseif(CMAKE_SYSTEM_NAME MATCHES "Windows")
   set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION .)
   include(${CopperSpice_DIR}/InstallMinGW.cmake)
endif(MSVC)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(CopperSpice REQUIRED)



# location for binary files
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

add_subdirectory(src)
```
outputs:
```
C:\CopperSpice\msvc\debug\include\QtCore\qglobal.h:1098: error: C2039: 'optional': is not a member of 'std'
C:\CopperSpice\msvc\debug\include\QtCore\qglobal.h(1098): error C2039: 'optional': is not a member of 'std'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include\algorithm(40): note: see declaration of 'std'\
```

Can't figure out why.

**Comment by janwilmans** [comment]
Looking at the code, I don't see the problem either ;)

Please tell us:
* what version of copperspice you are using (what link did you download?)
* what version of visual studio (see 'about' window)

**Comment by janwilmans** [comment]
On another note:

These:
```
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
```

Are Qt-features from CMake that you should turn off when using copperspice

**Comment by hongnod** [comment]
> Looking at the code, I don't see the problem either ;)
> 
> Please tell us:
> 
> * what version of copperspice you are using (what link did you download?)
    1.8.0 from CS official url: https://download.copperspice.com/copperspice/binary/cs-1.8/setup-CopperSpice-1.8.0-x64-MSVC-debug.exe
> * what version of visual studio (see 'about' window)
     VS2022 COMMUNITY 17.3.6

**Comment by hongnod** [comment]
> 

Thx！

**Comment by janwilmans** [comment]
I'm going to install that and see what happens ;)

**Comment by hongnod** [comment]
> I'm going to install that and see what happens ;)

FYI: I used Qt creator 8.02，setting as https://www.copperspice.com/docs/cs_overview/sample-toolchain.html


if I switch to Ming64, it outputs:
```
[1/31 7.8/sec] Generating helloworld.pb.cc, helloworld.pb.h, helloworld.grpc.pb.cc, helloworld.grpc.pb.h
[2/31 0.6/sec] Building CXX object src/CMakeFiles/hw_grpc_proto.dir/helloworld.pb.cc.obj
[3/31 0.3/sec] Building CXX object src/CMakeFiles/hw_grpc_proto.dir/helloworld.grpc.pb.cc.obj
[4/31 0.4/sec] Linking CXX static library src\libhw_grpc_proto.a
[5/31 0.4/sec] Generating qrc_JotPath.cpp
FAILED: src/qrc_JotPath.cpp D:/build-CsJotPath-CS-Debug/src/qrc_JotPath.cpp 
cmd.exe /C "cd /D D:\build-CsJotPath-CS-Debug\src && C:\CopperSpice\bin\rcc.exe D:/CsJotPath/src/../JotPath.qrc -o D:/build-CsJotPath-CS-Debug/src/qrc_JotPath.cpp -name JotPath"
ninja: build stopped: subcommand failed.
```

**Comment by hongnod** [comment]
> > I'm going to install that and see what happens ;)
> 
> FYI: I used Qt creator 8.02，setting as https://www.copperspice.com/docs/cs_overview/sample-toolchain.html
> 
> if I switch to Ming64, it outputs:
> 
> ```
> [1/31 7.8/sec] Generating helloworld.pb.cc, helloworld.pb.h, helloworld.grpc.pb.cc, helloworld.grpc.pb.h
> [2/31 0.6/sec] Building CXX object src/CMakeFiles/hw_grpc_proto.dir/helloworld.pb.cc.obj
> [3/31 0.3/sec] Building CXX object src/CMakeFiles/hw_grpc_proto.dir/helloworld.grpc.pb.cc.obj
> [4/31 0.4/sec] Linking CXX static library src\libhw_grpc_proto.a
> [5/31 0.4/sec] Generating qrc_JotPath.cpp
> FAILED: src/qrc_JotPath.cpp D:/build-CsJotPath-CS-Debug/src/qrc_JotPath.cpp 
> cmd.exe /C "cd /D D:\build-CsJotPath-CS-Debug\src && C:\CopperSpice\bin\rcc.exe D:/CsJotPath/src/../JotPath.qrc -o D:/build-CsJotPath-CS-Debug/src/qrc_JotPath.cpp -name JotPath"
> ninja: build stopped: subcommand failed.
> ```

Using the cmd:" cmd.exe /C "cd /D D:\build-CsJotPath-CS-Debug\src && C:\CopperSpice\bin\rcc.exe D:/CsJotPath/src/../JotPath.qrc -o D:/build-CsJotPath-CS-Debug/src/qrc_JotPath.cpp -name JotPath" produce a file "qrc_JotPath.cpp" and comment out 
```
# run rcc to generate qrc output
#COPPERSPICE_RESOURCES(
#   ${CMAKE_CURRENT_SOURCE_DIR}/../JotPath.qrc
#)
```
link to  "qrc_JotPath.cpp" dirctly, again see:
```
C:\CopperSpice\include\QtCore\qvariant.h:335: error: 'optional' in namespace 'std' does not name a template type
In file included from C:/CopperSpice/include/QtCore/csmeta_internal_1.h:30,
                 from C:/CopperSpice/include/QtCore/csmeta.h:28,
                 from C:/CopperSpice/include/QtCore/qmetaobject.h:30,
                 from C:/CopperSpice/include/QtCore/qobject.h:32,
                 from C:/CopperSpice/include/QtGui/qwidget.h:28,
                 from C:/CopperSpice/include/QtGui/qmenu.h:27,
                 from C:/CopperSpice/include/QtGui/QMenu:1,
                 from D:/CsJotPath/src/mainmenu.h:14,
                 from D:/CsJotPath/src/mainmenu.cpp:1:
C:/CopperSpice/include/QtCore/qvariant.h:335:9: error: 'optional' in namespace 'std' does not name a template type
  335 |    std::optional<T> getDataOr() const;
      |         ^~~~~~~~
C:/CopperSpice/include/QtCore/qvariant.h:335:4: note: 'std::optional' is only available from C++17 onwards
  335 |    std::optional<T> getDataOr() const;
      |    ^~~
```

that means Msvc and Ming64 both report lack of std::optional.

**Comment by janwilmans** [comment]
![image](https://user-images.githubusercontent.com/5933444/200539315-ac3414cb-f4ea-47f8-9609-5d4774f0e572.png)

I tried this sample project from https://github.com/janwilmans/copperspice-gettingstarted/tree/master/example_project_cmake and it works.... please try it

**Comment by hongnod** [comment]
> What is the content of the qrc file, I think that is part of the problem, maybe you could just .zip the project?

yes, it relates to the qrc file:
```
[6/31 1.8/sec] Building CXX object src\CMakeFiles\JotPath.dir\qrc_JotPath.cpp.obj
FAILED: src/CMakeFiles/JotPath.dir/qrc_JotPath.cpp.obj 
C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\HostX64\x64\cl.exe  /nologo /TP -DCARES_STATICLIB -D_WIN32_WINNT=0x600 -ID:\build-CsJotPath-CS-Debug\src -ID:\CsJotPath\src -ID:\CsJotPath\src\database -ID:\CsJotPath\src\JotNaviView -ID:\CsJotPath\src\JotDataView -ID:\CsJotPath\src\JotSideBar -ID:\CsJotPath\src\utils -external:IC:\CopperSpice\msvc\debug\include -external:IC:\CopperSpice\msvc\debug\include\QtCore -external:IC:\CopperSpice\msvc\debug\include\QtGui -external:IC:\CopperSpice\msvc\debug\include\QtNetwork -external:IC:\CopperSpice\msvc\debug\include\QtOpenGL -external:IC:\CopperSpice\msvc\debug\include\QtSql -external:IC:\CopperSpice\
[JotPath.zip](https://github.com/copperspice/copperspice/files/9966438/JotPath.zip)
msvc\debug\include\QtSvg -external:IC:\CopperSpice\msvc\debug\include\QtXml -external:IC:\CopperSpice\msvc\debug\include\QtXmlPatterns -external:ID:\Codelabs\libs\grpc\include -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd /utf-8 /bigobj /DNOMINMAX -std:c++14 /showIncludes /Fosrc\CMakeFiles\JotPath.dir\qrc_JotPath.cpp.obj /Fdsrc\CMakeFiles\JotPath.dir\ /FS -c D:\build-CsJotPath-CS-Debug\src\qrc_JotPath.cpp
```
the cmake file set c++17, but it compile the code with C++14(see above log: -std:c++14 )

the whole project folder is a little bit complex.

**Comment by hongnod** [comment]
Sorry, I missed there another sub include cmake file  which changed the C++ to 14.
