### ISSUE TITLE
What if declaration and implementation is in the same header?

### ISSUE THREAD

**Issue by iahung** [copperspice/copperspice#245]
From the document, it seems the syntax for slots is the same as normal methods, declarations in headers and implemented in source file.

https://www.copperspice.com/docs/cs_api/signals-slots-c.html

The code I have is a bit different. It implemented everything in headers file, combined declarations and implementations.

When running PepperMill on it, it produced something like this:

`CS_SLOT_1(Private, void clicked_hook(bool checked){if(clicked_event.func){typedefvoid(*func_type)(void*data,boolchecked);(*(func_type)clicked_event.func)(clicked_event.data,checked);}})`

Long story short, it wrapped the whole declaration and implementation into the CS_SLOT_1 macro. Is it a right thing to do?

It could be the very reason triggered this bug (very difficult to catch if use with the normal C++ discipline of separated declarations and implementations): https://github.com/copperspice/copperspice/issues/244

If I translated it by hand, should it be something like this?

```
    CS_SLOT_1(clicked_hook(bool checked))
    void clicked_hook(bool checked) {
      if ( clicked_event.func ) {
        typedef void (*func_type)(void *data, bool checked);
	(*(func_type)clicked_event.func)(clicked_event.data, checked);
      }
    }
    CS_SLOT_2(clicked_hook)

```

Do we need both CS_SLOT_1 and CS_SLOT_2?

**Comment by iahung** [comment]
Oh no, in case my English confused you. Let's ignore the above post. Just tell me, how could you translate this header to CopperSpice?

```
//******************************************************************************
//  Copyright (c) 2005-2013 by Jan Van hijfte
//
//  See the included file COPYING.TXT for details about the copyright.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//******************************************************************************


#ifndef QABSTRACTBUTTON_HOOK_H
#define QABSTRACTBUTTON_HOOK_H

#include <qabstractbutton.h>

#include "qwidget_hook.h"

class QAbstractButton_hook : public QWidget_hook {
  Q_OBJECT
  public:
    QAbstractButton_hook(QObject *handle) : QWidget_hook(handle) {
      pressed_event.func = NULL;
      released_event.func = NULL;
      clicked_event.func = NULL;
      clicked2_event.func = NULL;
      toggled_event.func = NULL;
    }
    void hook_pressed(QHook &hook) { 
      if ( !pressed_event.func )
        connect(handle, SIGNAL(pressed()), this, SLOT(pressed_hook()));
      pressed_event = hook;
      if ( !hook.func )
        disconnect(handle, SIGNAL(pressed()), this, SLOT(pressed_hook()));
    }
    void hook_released(QHook &hook) { 
      if ( !released_event.func )
        connect(handle, SIGNAL(released()), this, SLOT(released_hook()));
      released_event = hook;
      if ( !hook.func )
        disconnect(handle, SIGNAL(released()), this, SLOT(released_hook()));
    }
    void hook_clicked(QHook &hook) { 
      if ( !clicked_event.func )
        connect(handle, SIGNAL(clicked(bool)), this, SLOT(clicked_hook(bool)));
      clicked_event = hook;
      if ( !hook.func )
        disconnect(handle, SIGNAL(clicked(bool)), this, SLOT(clicked_hook(bool)));
    }
    void hook_clicked2(QHook &hook) { 
      if ( !clicked2_event.func )
        connect(handle, SIGNAL(clicked()), this, SLOT(clicked2_hook()));
      clicked2_event = hook;
      if ( !hook.func )
        disconnect(handle, SIGNAL(clicked()), this, SLOT(clicked2_hook()));
    }
    void hook_toggled(QHook &hook) { 
      if ( !toggled_event.func )
        connect(handle, SIGNAL(toggled(bool)), this, SLOT(toggled_hook(bool)));
      toggled_event = hook;
      if ( !hook.func )
        disconnect(handle, SIGNAL(toggled(bool)), this, SLOT(toggled_hook(bool)));
    }

  private slots:
    void pressed_hook() {
      if ( pressed_event.func ) {
        typedef void (*func_type)(void *data);
	(*(func_type)pressed_event.func)(pressed_event.data);
      }
    }
    void released_hook() {
      if ( released_event.func ) {
        typedef void (*func_type)(void *data);
	(*(func_type)released_event.func)(released_event.data);
      }
    }
    void clicked_hook(bool checked) {
      if ( clicked_event.func ) {
        typedef void (*func_type)(void *data, bool checked);
	(*(func_type)clicked_event.func)(clicked_event.data, checked);
      }
    }
    void clicked2_hook() {
      if ( clicked2_event.func ) {
        typedef void (*func_type)(void *data);
	(*(func_type)clicked2_event.func)(clicked2_event.data);
      }
    }
    void toggled_hook(bool checked) {
      if ( toggled_event.func ) {
        typedef void (*func_type)(void *data, bool checked);
	(*(func_type)toggled_event.func)(toggled_event.data, checked);
      }
    }
  private:
    QHook pressed_event;
    QHook released_event;
    QHook clicked_event;
    QHook clicked2_event;
    QHook toggled_event;
};


#endif

```

Please give me an example. It's enough. Thank you.

**Comment by iahung** [comment]
Qt's MOC is one of the most brilliant invention on the C++ world. This is what I just realized.

**Comment by bgeller** [comment]
> MOC is one of the most brilliant invention on the C++ world.

There is a bit of education missing here and we would like to help you out . The handling of Signal / Slot connections is fantastic, but the internals to their meta object compiler (moc) is not good C++ code at all. It is prone to undefined behavior, has threading issues, and is not type safe.  For C++ code to be considered awesome, it must be type safe which means every type cast is guaranteed safe at compile time. Moc was truly the best anyone could do prior to C++11, but with current standards it is not considered safe code. 

In CopperSpice we redesigned the internals and removed moc by implementing **all** of the functionality directly in C++ code.  Our Signals/Slots in CS are type safe and we do not rely on a C-style cast from a void *.  

>  it seems the syntax for slots is the same as normal methods

In CS you have the option of declaring a SLOT in the same way you did before or as a standard class method. Both declarations are valid. The main reason to use the older macro syntax is to support the legacy string based connect() syntax.

**Comment by bgeller** [comment]
> The code I have is a bit different. It implemented everything in headers file, combined declarations and implementations. When running PepperMill on it, it produced something like this:
> 
> `CS_SLOT_1(Private, void clicked_hook(bool checked){if(clicked_event.func){typedefvoid(*func_type)(void*data,boolchecked);(*(func_type)clicked_event.func)(clicked_event.data,checked);}})`

It is very uncommon to provide an inline implementation for a SLOT in the header file. Based on this report we have been able to determine what problem you had using PepperMill. All of the white space was trimmed in the implementation and we need to fix that in PM. 

Thank you so much for your continued effort to show us what you were doing and how PM should be enhanced. We understand you were a bit concerned about how to express your ideas in English.  You did a great job. 

Barbara

**Comment by s6nonqxt** [comment]
> > MOC is one of the most brilliant invention on the C++ world.
> 
> There is a bit of education missing here and we would like to help you out . The handling of Signal / Slot connections is fantastic, but the internals to their meta object compiler (moc) is not good C++ code at all. It is prone to undefined behavior, has threading issues, and is not type safe. For C++ code to be considered awesome, it must be type safe which means every type cast is guaranteed safe at compile time. Moc was truly the best anyone could do prior to C++11, but with current standards it is not considered safe code.
> 
> In CopperSpice we redesigned the internals and removed moc by implementing **all** of the functionality directly in C++ code. Our Signals/Slots in CS are type safe and we do not rely on a C-style cast from a void *.
> 
> > it seems the syntax for slots is the same as normal methods
> 
> In CS you have the option of declaring a SLOT in the same way you did before or as a standard class method. Both declarations are valid. The main reason to use the older macro syntax is to support the legacy string based connect() syntax.

Does your signals and slots handling thread safe yet?

This is from 2020 and still not fixed: https://github.com/copperspice/cs_signal/issues/12

If you can't fix it, consider to use this: https://github.com/libsigcplusplus/libsigcplusplus

Oh wait a minute, I almost forgot. It switched to LGPLv3+, you are stuck at LGPLv2.1 so this is not an option. Btw there are various libraries floating on github that offer signals and slots, it's easy to pick one with a compatible license, don't worry!

**Comment by s6nonqxt** [comment]
What a terrible performance! https://woboq.com/blog/verdigris-qt-without-moc.html

**Comment by s6nonqxt** [comment]
Want moc implemented in modern C++ and type safe? Here you are: https://github.com/woboq/moc-ng

**Comment by s6nonqxt** [comment]
Please stop offering lies about moc and qt!
