### ISSUE TITLE
Copperspice failed to build due to some errors on x64 and x86 with MSVC on windows

### ISSUE THREAD

**Issue by WickWeiWkSpace** [copperspice/copperspice#247]
Hi all,

Copperspice failed to build due to some errors on x64 and x86 with MSVC on windows. it can be reproduced on e2c5b4a on master branch. Could you please help look at this issue?

**Environment:**
VS 2019 + Windows Server 2019

**Repro steps:**

  1. git clone https://github.com/copperspice/copperspice F:\gitP\copperspice

  2. open x64(or x86) Native tools command prompt for VS2019

  3. set _CL_=/wd4251 /wd4244 /wd4291 /wd4018 /wd4275 /wd4250 /wd4996 %_CL_%
  4. cd F:\gitP\copperspice\copperspice\build_amd64
  5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 .. 2>&1
  6. msbuild /m /p:Platform=x64 /p:Configuration=Release copperspice.sln /t:Rebuild /p:PreferredToolArchitecture=x64 2>&1

**Error info:**
on **x64**:
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(135,18): error C2672: 'map_vector': no matching overloaded function found [F:\gitP\copperspice\copperspice\build_amd64\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(145,51): error C3536: 'queues': cannot be used before it is initialized [F:\gitP\copperspice\copperspice\build_amd64\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(145,26): error C2672: 'filter_sort_queues': no matching overloaded function found [F:\gitP\copperspice\copperspice\build_amd64\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(146,26): error C2672: 'filter_sort_queues': no matching overloaded function found [F:\gitP\copperspice\copperspice\build_amd64\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(148): error C3536: 'graphicsQueues': cannot be used before it is initialized [F:\gitP\copperspice\copperspice\build_amd64\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(153): error C3536: 'transferQueues': cannot be used before it is initialized [F:\gitP\copperspice\copperspice\build_amd64\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(654,24): error C2672: 'map_vector': no matching overloaded function found [F:\gitP\copperspice\copperspice\build_amd64\src\vulkan\CsVulkan.vcxproj]

on **x86**:
 F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(135,18): error C2672: 'map_vector': no matching overloaded function found [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_instance.cpp(110,37): error C2440: '=': cannot convert from 'VkBool32 (__cdecl *)(VkDebugReportFlagsEXT,VkDebugReportObjectTypeEXT,uint64_t,size_t,int32_t,const char *,const char *,void *)' to 'PFN_vkDebugReportCallbackEXT' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(145,51): error C3536: 'queues': cannot be used before it is initialized [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(145,26): error C2672: 'filter_sort_queues': no matching overloaded function found [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(146,26): error C2672: 'filter_sort_queues': no matching overloaded function found [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(148): error C3536: 'graphicsQueues': cannot be used before it is initialized [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(153): error C3536: 'transferQueues': cannot be used before it is initialized [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_instance.cpp(194,77): error C2665: 'QVulkanDeviceFunctions::QVulkanDeviceFunctions': no overloaded function could convert all the argument types [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(163,35): error C2664: 'QVulkanDeviceFunctions *QVulkanInstance::deviceFunctions(VkDevice)': cannot convert argument 1 from 'Type' to 'VkDevice' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(654,24): error C2672: 'map_vector': no matching overloaded function found [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_instance.cpp(443,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkSurfaceKHR' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_instance.cpp(451,11): error C2440: 'return': cannot convert from 'const Type' to 'VkInstance' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(945,64): error C2440: 'return': cannot convert from 'const Type' to 'VkCommandBuffer' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(956,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkFramebuffer' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(959,58): error C2440: 'return': cannot convert from 'const Type' to 'VkFramebuffer' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(970,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkRenderPass' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(973,27): error C2440: 'return': cannot convert from 'Type' to 'VkRenderPass' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(984,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkImage' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(987,56): error C2440: 'return': cannot convert from 'const Type' to 'VkImage' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(993,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkImageView' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(996,56): error C2440: 'return': cannot convert from 'const Type' to 'VkImageView' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1001,31): error C2440: 'return': cannot convert from 'const Type' to 'VkDevice' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1088,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkImage' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1091,47): error C2440: 'return': cannot convert from 'const Type' to 'VkImage' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1097,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkImageView' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1100,47): error C2440: 'return': cannot convert from 'const Type' to 'VkImageView' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1114,50): error C2440: 'return': cannot convert from '_Ty' to 'VkPhysicalDevice' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1214,23): error C2664: 'VkResult QVulkanFunctions::vkEnumerateDeviceExtensionProperties(VkPhysicalDevice,const char *,uint32_t *,VkExtensionProperties *)': cannot convert argument 1 from '_Ty' to 'VkPhysicalDevice' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1222,14): error C2664: 'VkResult QVulkanFunctions::vkEnumerateDeviceExtensionProperties(VkPhysicalDevice,const char *,uint32_t *,VkExtensionProperties *)': cannot convert argument 1 from '_Ty' to 'VkPhysicalDevice' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1275,24): error C2440: 'return': cannot convert from 'Type' to 'VkSurfaceKHR' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1281,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkImage' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1284,22): error C2440: 'return': cannot convert from 'const vk::Image' to 'VkImage' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1300,14): error C2440: 'return': cannot convert from 'nullptr' to 'VkImageView' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]
F:\gitP\copperspice\copperspice\src\vulkan\qvulkan_window.cpp(1303,47): error C2440: 'return': cannot convert from 'const Type' to 'VkImageView' [F:\gitP\copperspice\copperspice\build_x86\src\vulkan\CsVulkan.vcxproj]

**Comment by bgeller** [comment]
(1) Looking at your error report the problems happen when building the CsVulkan library.  As a test, recompile CopperSpice and turn off building CsVulkan using the following CMake command.

`-DWITH_VULKAN=NO `

This information is listed in our **CS Overview Documentation**.

https://www.copperspice.com/docs/cs_overview/build-options.html

(2)  We need to know the exact version of your installed Vulkan SDK. The minimum version is listed in our **CS API Documentation**.

https://www.copperspice.com/docs/cs_api/group__qtvulkan.html

Barbara

**Comment by WickWeiWkSpace** [comment]
Thank you very much for your information, we will try what you said, and the version of Vulkan SDK we installed is 1.2.154.1.

**Comment by bgeller** [comment]
Thanks for reporting this issue.  We did additional testing on MSVC with a newer version of the Vulkan SDK and found an issue. LunarG likes to change the data type of passed parameters and return values.  We will make the necessary changes to this library.  

In the mean time, if you turn off building this one library everything else should compile.

**Comment by bgeller** [comment]
This was fully resolved as of CopperSpice 1.8.1 which was officially released in January 2023.
