### ISSUE TITLE
build cs 1.8.1 with nXiman Mingw-W64_x86_64-12.2.0-release-posix-seh-ucrt-rt_v10-rev2 failed

### ISSUE THREAD

**Issue by hongnod** [copperspice/copperspice#252]
log: 
[build.txt](https://github.com/copperspice/copperspice/files/10686805/build.txt)
key  message:
![image](https://user-images.githubusercontent.com/6680267/217565526-f0ed329b-5aeb-4971-8b80-eb21648731d1.png)

**Comment by bgeller** [comment]
This is not a currently supported or tested toolchain of MinGW on Windows. Please provide a link to where you obtained this compiler. 

We will note this issue for review. If this is an incompatibility with the Standard Library our options may be limited.

**Comment by hongnod** [comment]
> This is not a currently supported or tested toolchain of MinGW on Windows. Please provide a link to where you obtained this compiler.
> 
Mingw-w64:
https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev2/x86_64-12.2.0-release-posix-seh-ucrt-rt_v10-rev2.7z
> We will note this issue for review. If this is an incompatibility with the Standard Library our options may be limited.

there is another issue:  struct std::iterator' is deprecated [-Wdeprecated-declarations]
CS is modern lib, better support newer compiler.

**Comment by bgeller** [comment]
We support a variety of compilers and versions. Many of our Linux platforms have been tested on GCC 11. 

Our lowest supported platform is currently Windows MinGW. Someone is actively working on upgrading the Windows tool chain to support version 10, 11, and 12. This will include an a set of updated development tools.

**Comment by hongnod** [comment]
with up fix.

**Comment by bgeller** [comment]
We looked at the MinGW headers and found a slightly improved implementation. This has been committed in SHA be1e07f.  

Please retest and close this ticket if the issue is resolved for your build.

**Comment by hongnod** [comment]
> We looked at the MinGW headers and found a slightly improved implementation. This has been committed in SHA [be1e07f](https://github.com/copperspice/copperspice/commit/be1e07ff50d2353bc5b70c179047f38d45f87408).
> 
> Please retest and close this ticket if the issue is resolved for your build.

yes. it works.
