### ISSUE TITLE
Depreated iterator

### ISSUE THREAD

**Issue by bergwc55b** [copperspice/copperspice#255]
Using GCC 12.2.1
copperspice 1.8
Issues an warning.  Still builds so I consider it a low priority. 

In file included from /home/rick/copperspice/sc_build/include/QtCore/regex/regex.h:49:
/home/rick/copperspice/sc_build/include/QtCore/regex/regex_token_iterator.h:130:18: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  130 |    : public std::iterator <std::forward_iterator_tag, sub_match<BidirectionalIterator>,
      |                  ^~~~~~~~
/usr/include/c++/12/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~

**Comment by bgeller** [comment]
Thank you for reporting this issue.  We have it noted and on our list of items to correct.

**Comment by bgeller** [comment]
This has been resolved in SHA b395f392fb
