### ISSUE TITLE
Just FYI(LLVM-Mingw & small dll size)

### ISSUE THREAD

**Issue by hongnod** [copperspice/copperspice#259]
I did a test, after making following changes, I can build CS with LLVM-Mingw(https://github.com/mstorsjo/llvm-mingw) and output small lib size.

[0001-modification-made-CS-can-be-built-with-LLVM-MINGW-re.patch](https://github.com/copperspice/copperspice/files/11242293/0001-modification-made-CS-can-be-built-with-LLVM-MINGW-re.patch)

![1681649213100(1)](https://user-images.githubusercontent.com/6680267/232312470-a1b413f6-81b8-4771-80d3-d8e2a9fabe9b.png)

**Comment by bgeller** [comment]
We appreciate the time you are investing in this issue. Sadly these changes would break building CS on most Unix platforms and MSVC so they can not be accepted. A valid solution will not involve removing the test for minGW but to find out how llvm-mingw should be detected.  

Although we are not adding this compiler to our CI at this time someone on our team will reach out to a member of the llvm project to inquire about the correct implementation for compiler detection.

**Comment by hongnod** [comment]
After reading the "/src/core/global/qglobal.h", I realized "Q_CC_MINGW" was defined in "defined(__GNUC__)" block, it was lack in "defined(__clang__)",  so "Q_CC_MINGW" was not defined in source file "qfilesystemengine_win.cpp"  under Clang building env. 

This patch looks better, but I am not sure.
[0001-Support-build-with-LLVM-Mingw.patch](https://github.com/copperspice/copperspice/files/11245619/0001-Support-build-with-LLVM-Mingw.patch)
