### ISSUE TITLE
How to force it to use lld instead of gnu ld?

### ISSUE THREAD

**Issue by 97tn** [copperspice/copperspice#261]
For the reason, please see: https://github.com/brechtsanders/winlibs_mingw/issues/118

It's a regression in gnu ld that they don't care to fix.

On MSYS2 (I mean the MINGW64 and UCRT64 environments as the CLANG64 environment is already using lld), one could install lld using pacman: `mingw-w64-x86_64-lld` for MINGW64 and `mingw-w64-ucrt-x86_64-lld` for UCRT64.

My problem is I don't know how to tell cmake to force it using lld instead of gnu ld. Please help.

**Comment by bgeller** [comment]
Please be aware that we do not use or support the msys2 toolchain on Windows. Their project uses custom patches which are not approved by most of the upstream projects. Our team 

With the help of some other compiler developers we were able to discover the correct process for building MinGW-w64 and most of the POSIX utilities.  Nothing we have released requires the Cygwin run time. 

I believe the question you are asking is how to use a different linker when compiling with GCC.  This should involve passing `-fuse-ld=lld` in your CXX flags.  Give this a try and let us know what happens.

Barbara
