### ISSUE TITLE
[Idea] What about CsCreator?

### ISSUE THREAD

**Issue by 97tn** [copperspice/copperspice#262]
As you already known Qt6 dropped support for Windows 7 and Windows 8.1. Here I'm on Windows 8.1 I can install QtCreator on MSYS2 but I can't use it since it's a Qt6 application:

You already have CsDesigner so I think it's sooner or later you will need to have CsCreator to be a complete alternative to Qt.

**Comment by bgeller** [comment]
Thank you, this is a lovely question.  

CopperSpice, CsDesigner, and all of our other CS libraries are fully supported on Windows 7 and newer. We have no plans on dropping support for these versions.  I personally maintain a Windows 7 system and will continue to do so for testing. 

The release of CsDesigner was partially based on existing LGPL 2 source code. We did make several changes and enhancements. If there are features users want to add in CsDesigner our team will maintain contributions and assist with the development. 

We looked at the idea of CsCreator however their product is GPL 3 and the license is not compatible with the CS project. Developing an equivalent type of program would involve starting from scratch.  A better approach might be writing a plug in for something like Eclipse. 

We are very curious, what does a Creator like program provide for you? The combination of CsDesigner and an editor like Diamond seems to meet most of users needs.

**Comment by 97tn** [comment]
I failed to see that Qt Creator's license is incompatible with CopperSpice, though. Diamond Editor's editor is GPLv2, as is DoxyPress, and it's not considered incompatible with CopperSpice. Please remember that Qt Creator is an application. CopperSpice is a library. One could use a LGPLv2.1 library to develop a GPLv3 application without any problems. Or because you just hate GPLv3?

**Comment by bgeller** [comment]
There is a lot to know about software licenses and occasionally it requires the expertise of an Intellectual Property lawyer to find out about all the regulations. 

Qt Creator has an GPL 3 license which means this code base can only be viewed and used with libraries which are GPL 3. The legality of using this code base is not a line we want to infringe upon out of respect for their intellectual property rights. 

CopperSpice uses a more open and less restrictive license of LGPL 2. In order for us to create derivative work of their application we would need to change the license for the CopperSpice libraries. Our reason for not doing this is strictly about keeping the CS libraries on a less restrictive license. New libraries we develop like CsLibGuarded use a BSD license which is even more permissive.  

Applications released under GPL 2 are allowed to use any library released with an LGPL 2 license. It is very important for us to explain that developers can use the CopperSpice libraries to write an application which you release under GPL 3 or even closed source. If you make this choice it simply limits who can create derivative work from your source code.
