### ISSUE TITLE
[Question] How to setup Eclipse to use with CopperSpice?

### ISSUE THREAD

**Issue by 97tn** [copperspice/copperspice#263]
I downloaded the Windows version of Eclipse:

https://www.eclipse.org/downloads/packages/release/2023-03/r/eclipse-ide-cc-developers

What to do next?

**Comment by bgeller** [comment]
You can use the their IDE unmodified to develop your source code and build executables which link with CopperSpice. Eclipse already supports developing C++ applications using CMake.

As we mentioned in your other issue,  _"A better approach might be writing a plug in for something like Eclipse."_ If you want to use CsDesigner from Eclipse, you will need to do a bit of research to figure out how to write a plugin for Eclipse. It seems like the main feature this plugin should provide is to open the CsDesigner program when you want to change a UI form. 

There is a lot of information on the Eclipse forums and this should not be very complicated. If you have specific questions about CopperSpice feel free to ask and we will do our best to help out. Once you have this working our team will be happy to assist with testing, documentation, and maintaining the plugin.

Barbara

**Comment by 97tn** [comment]
I don't need the ability to call CsDesigner from Eclipse. CMake currently failed to find CopperSpice. My question is how to configure the Eclipse IDE so CMake will be able to find CopperSpice.

**Comment by bgeller** [comment]
Since Eclipse supports CMake natively, this is likely a configuration setting. Please let us a short version of the error you received. Maybe just the last few lines of whatever message Eclipse reported.

**Comment by 97tn** [comment]
For example, I created an cmake based project with the template `Empty or Existing CMake project` (it will create an empty cmake project). Then I use Import feature to import `kitchensink` from `File System` (I imported everything so I have a complete source tree of `kitchensink` including `CMakeLists.txt`). I choose to build project. This is what I see:

```
Configuring in: C:\Users\97tn\eclipse-workspace\kitchensink\build\default
cmake -G MinGW Makefiles -DCMAKE_EXPORT_COMPILE_COMMANDS=ON C:\Users\97tn\eclipse-workspace\kitchensink
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:29 (find_package):
-- Configuring incomplete, errors occurred!
  By not providing "FindCopperSpice.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CopperSpice", but CMake did not find one.

  Could not find a package configuration file provided by "CopperSpice" with
  any of the following names:

    CopperSpiceConfig.cmake
    copperspice-config.cmake

  Add the installation prefix of "CopperSpice" to CMAKE_PREFIX_PATH or set
  "CopperSpice_DIR" to a directory containing one of the above files.  If
  "CopperSpice" provides a separate development package or SDK, be sure it
  has been installed.


Building in: C:\Users\97tn\eclipse-workspace\kitchensink\build\default
cmake --build . --target all
mingw32-make: Makefile: No such file or directory
mingw32-make: *** No rule to make target 'Makefile'.  Stop.
Build complete (1 errors, 0 warnings): C:\Users\97tn\eclipse-workspace\kitchensink\build\default
```

**Comment by 97tn** [comment]
On the command line, I could pass `-DCMAKE_PREFIX_PATH=C:\CopperSpice\cmake\CopperSpice` but on Eclipse I don't know how. I have never used this IDE before.

**Comment by bgeller** [comment]
So where you able to build KitchenSink in Eclipse?

**Comment by 97tn** [comment]
> So where you able to build KitchenSink in Eclipse?

Yep, open the project's Settings, go to CMake and click Launch CMake GUI. You do everything CMake related on CMake GUI. Eclipse is nothing but a frontend for you to call CMake GUI. Now back to Eclipse it will be able to build the project. But you will quickly realize code completion doesn't work. Try to open a random source file it will give you dozen of warnings about unresolved symbols. This doesn't happen with Eclipse's Managed C++ Build project where you could manually specify the include paths (this is not possible on CMake based project).

Another problem is, even though you are able to build `kitchensink` now. If you choose to run the binary, it will fail to run. On the command prompt, you will have to use `mingw32-make install` for it to properly copy all of the needed DLLs. My final conclusion is Eclipse is in no way comparable to Qt Creator.

**Comment by bgeller** [comment]
Most Windows developers who want these features tend to use MSVC however we have heard that Eclipse works pretty well for the things you are looking for. I will ask someone on our CS team to take a look at steps required to make Eclipse work a bit better. 

Applications need to be installed before you can run the binary. I am sure there is a way to configure a deploy step in Eclipse without having to do this at the command prompt.

**Comment by 97tn** [comment]
> Most Windows developers who want these features tend to use MSVC however we have heard that Eclipse works pretty well for the things you are looking for. I will ask someone on our CS team to take a look at steps required to make Eclipse work a bit better.
> 
> Applications need to be installed before you can run the binary. I am sure there is a way to configure a deploy step in Eclipse without having to do this at the command prompt.

The most annoying problem with Eclipse is that there will be no code completion with CMake-based projects. Even if you could add a deploy step, it's still not comparable to Qt Creator. It seems both Eclipse and Qt Creator are using `clangd`. I found Eclipse added `-DCMAKE_EXPORT_COMPILE_COMMANDS=1` to the cmake command to generate `compile_commands.json`, but for unknown reasons, code completion simply doesn't work on CMake-based projects. It's even not able to resolve symbols.
