### ISSUE TITLE
Porting qmake and qbs to CopperSpice

### ISSUE THREAD

**Issue by PHdrr** [copperspice/copperspice#270]
CMake is the industrial standard but sometimes you will just want to setup a build system as quick as possible to start building. When porting from Qt to CopperSpice, I want to be able to jump to the coding part immediately instead of having to deal with CMakeLists.txt. I know the porting to CMake build system is just a once time process but sometimes it's really time consuming, especially if the qmake build script or qbs build script is non-trivial. Both qmake and qbs have LGPL versions that you could use to port to CopperSpice. Please consider. Thank you.

**Comment by bgeller** [comment]
Both of the build systems you mentioned are specific to one project and not used universally in C++. Their company is aware of this issue and many of their developers are pushing for a move to CMake. There are also other build systems like Meson and Bazel, which we did considered before choosing CMake. 

We have a basic CMake project file to help users get started. Please have a look at our examples on the Journal website. We currently have 38 examples with full source code and explanations. 

https://journal.copperspice.com/
https://journal.copperspice.com/?p=180  **"Compile, Link, Run"**
