### ISSUE TITLE
Using libraries designed for Qt with CopperSpice?

### ISSUE THREAD

**Issue by PHdrr** [copperspice/copperspice#271]
I mean libraries like QScintilla. Qt is not just a library but also an ecosystem. Yes I know CopperSpice is not Qt but it's hard for you to find a non-trivial Qt project that only uses the pure Qt library. No one will want to maintain a downstream fork of something like QScintilla. It's better to be provided by the CopperSpice team.

**Comment by bgeller** [comment]
Another CS user has actually already ported this library to CopperSpice. We have not officially added this project to our downloads. If you encounter any issues please let us know.  

If there are other libraries someone would like ported to CopperSpice, we are happy to help out. 


>  Copied from the CopperSpice Forum,  https://forum.copperspice.com/viewtopic.php?t=2240
>  

> After a lot of life got in the way, **CsScintilla** is now an actual SourceForge project. Those looking to create your own text editors and IDEs now have a CopperSpice compatible editing library with major capabilities.  

https://sourceforge.net/projects/csscintilla/
