### ISSUE TITLE
Prefering debug and release target in same dir, but "CopperSpiceConfigVersion.cmake"  is a barrier

### ISSUE THREAD

**Issue by hongnod** [copperspice/copperspice#284]
Build CS using this script:
`cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=destination  -DWITH_SCRIPT=NO -DWITH_WEBKIT=NO -DCMAKE_DISABLE_FIND_PACKAGE_ZLIB=TRUE -DCMAKE_DEBUG_POSTFIX="d" -DCMAKE_EXE_LINKER_FLAGS="/manifest:no" -DCMAKE_MODULE_LINKER_FLAGS="/manifest:no" -DCMAKE_SHARED_LINKER_FLAGS="/manifest:no"

cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=destination  -DWITH_SCRIPT=NO -DWITH_WEBKIT=NO -DCMAKE_DISABLE_FIND_PACKAGE_ZLIB=TRUE -DCMAKE_EXE_LINKER_FLAGS="/manifest:no" -DCMAKE_MODULE_LINKER_FLAGS="/manifest:no" -DCMAKE_SHARED_LINKER_FLAGS="/manifest:no"  -DCMAKE_CXX_FLAGS="/Os" -DCMAKE_C_FLAGS="/Os" -DCMAKE_CXX_FLAGS="/EHsc"`

which means set postfix to debug version target.
After building, the target home looks like:
![1702994915520](https://github.com/copperspice/copperspice/assets/6680267/d28f7721-039a-4625-a6d5-a586c87bdf4f)

when build app with this mixed  libs, in debug mode, it complains compatible issue, after digging into  cmake script files,
I found contents in red box  are answer. after comment out some lines as pics,  debug and release app both work fine.

![1702995177100](https://github.com/copperspice/copperspice/assets/6680267/e803604f-b332-4efd-bb63-2791c1e7439f)

**Comment by hongnod** [comment]
There is still has a little trouble, CsGuiWin1.8.dll and CsGuiWin1.8d.dll cann't co-exist, or the app will not start.

**Comment by bgeller** [comment]
As you found out, CopperSpice does not support having the release and debug builds in the same directory. You also can not have a user application with the release and debug in the same directory. 

It is not as simple as just having two sets of CMake configuration files. The install paths are resolved at build time. Trying to make two sets of CMake files would make everything too complicated and error prone.

Barbara

**Comment by hongnod** [comment]
I had found solution on CS official manual.
thx!

**Comment by bgeller** [comment]
Since this is not supported by CopperSpice, it would be nice to know what solution you found.
