### ISSUE TITLE
Build CsSignal as a standalone static library

### ISSUE THREAD

**Issue by hs-apotell** [copperspice/copperspice#286]
This is in reference to an open issue on the CsSignal repository but I guess this is better platform to discuss this as CopperSpice actually embeds the library in CsCore.

Related issue: https://github.com/copperspice/cs_signal/issues/4

Some background context - We use CsSignal (slightly modified version) in our non-GUI library projects that gets linked to the larger GUI projects. There is signaling that goes both ways. So far, this worked with a hack where we were compiling CsSignal into a different namespace for the standalone library use case. This approach is getting a little tedious to maintain and introducing some unnecessary dependencies that we could potentially avoid.

Note that using both independently compiled CsSignal and CsCore in the same namespace, in the same project won't work because of name conflicts.  These are all reported as link errors when building.

Potential Solution - How about if we compiled CsSignal as a standalone library that is installed/deployed with CS and is also linked into CsCore just like any other library? None of the code has to move, with no code edits except for small change to the build system. This would avoid us having to maintain an modified version of the library and it doesn't change anything for other users. However, users with use case like ours could benefit with a maintained library.

If this is an acceptable solution, I can introduce a PR with the necessary changes to the build system. Alternative approaches that could potentially solve the issue are welcome.

**Comment by bgeller** [comment]
A major change was made in December 2022 which will solve this issue. The solution required some fancy changes to the CMake build files. 

The CsCore library depends on functionality in the stand alone CsLibGuarded, CsSignal, and the CsString libraries. Files from each of these libraries are embedded in the CopperSpice source code. The required files from these three libraries are located in the **cs/src/annex** directory.  

The CopperSpice CMake build files were re-designed to look for a system version of CsLibGuarded, CsSignal, and CsString when building CsCore. The term "system" version refers to a copy of one of these libraries which is external to the CS source code. The path to a system version must be specified in your config file. You are free to use a system version of one of these and the embedded version of the other libraries. 

To build CsCore using a system library you will need to provide a search path to the CMake files located in the install prefix path for that library. You must also set the CMake variable CS_INSTALL_MODE to either Package or Deploy.

For more information please refer to the following page in our CS Overview documentation:
https://www.copperspice.com/docs/cs_overview/build-annex.html
