### ISSUE TITLE
QString is very slow compared to std::string

### ISSUE THREAD

**Issue by velvet-jones** [copperspice/copperspice#289]
The following performance test consistently shows the CopperSpice QString as 12-17 times slower than std::string when doing std::map::find. 

```
#include <iostream>
#include <random>
#include <map>
#include <chrono>
#include <QString>

std::string rstring()
{
  std::mt19937 generator{std::random_device{}()};
  std::uniform_int_distribution<int> distribution{'a', 'z'};
  std::string r(20, '\0');
  for(auto& dis: r)
    dis = distribution(generator);

  return r;
}

int main()
{
  std::map<std::string,std::string> m1;
  std::map<QString,QString> m2;

  for (size_t count = 0; count < 10000; count++)
  {
    std::string key = rstring();
    std::string val = rstring();
    m1[key] = val;
    m2[QString::fromStdString(key)] = QString::fromStdString(val);
  }

  auto start = std::chrono::steady_clock::now();
  auto stop = start;
  m1.find("mykey");
  stop = std::chrono::steady_clock::now();

  auto diff1 = stop - start;

  QString csKey("mykey");
  start = std::chrono::steady_clock::now();
  m2.find(csKey);
  stop = std::chrono::steady_clock::now();

  auto diff2 = stop - start;

  std::cout << "m1 find " << std::chrono::duration_cast<std::chrono::microseconds>(diff1).count() << std::endl;
  std::cout << "m2 find " << std::chrono::duration_cast<std::chrono::microseconds>(diff2).count() << std::endl;
}
```

**Comment by velvet-jones** [comment]
Thank you for the invitation to help, I may jump in and profile the less-than operator a little more if I find the time.

It seems to me that some things work in practice without knowing string encoding; for example substring:

s1 = "hello"; s2 = "hello world"; s2.find(s1)

It seems this would work without having any knowledge of the encoding. At any rate, you have written a string class and I have not, I am sure there are a hundred little gotchas. Having a backing store separate from the encoding seems like the best of both worlds, but again I only have some vague ideas and I am not about to try to write yet another string for C++. I won't die on this hill IOW. :)

I'm happy to see CopperSpice using CMake and I applaud the effort to rebuild the Qt codebase in a way that feels like it has a long-term viability. It feels like Qt is becoming bloated and losing focus.

If it's useful, I am attaching the visual output of qcachegrind and the original callgrind file that can be used with qcachegrind.
[callgrind.out.1177629.zip](https://github.com/copperspice/copperspice/files/15498819/callgrind.out.1177629.zip)
![qstring](https://github.com/copperspice/copperspice/assets/2877548/258dadb7-16e9-4634-b11d-9b382434b1df)

**Comment by bgeller** [comment]
As previously stated QString and std::string do not accomplish the same task and are simply not interchangeable. String support for UTF-8 is essential and currently C++ does not provide built in support. 

Most of slow string processing is not caused by our QString class.  We did an extensive study and found this is a byproduct of how strings are used in classes like QTextDocument. Our roadmap has been expanded to improve the usage of QString to resolve the known performance issue.

Thank you for all of your information regarding this issue.

Barbara
