### ISSUE TITLE
Mnemonics work in the menu bar only

### ISSUE THREAD

**Issue by wocard2** [copperspice/copperspice#290]
If I create a menu named "&File" in the menubar that has an item named "&Exit", Alt+F followed by Alt+E should invoke the associated action. Alt+F works (the menu opens), but then Alt+E doesn't have any effect (unlike with Qt Group's Qt).

This problem occurs with CS 1.9.1 on Linux (I tried various flavors of Linux). Code attached.

[Test.zip](https://github.com/user-attachments/files/16426625/Test.zip)

**Comment by e-mattes** [comment]
Please try this patch.

[mnemonic-patch.zip](https://github.com/user-attachments/files/16438774/mnemonic-patch.zip)

**Comment by wocard2** [comment]
Works, thanks!

**Comment by agserm** [comment]
Thank you to @wocard2 for the report and @e-mattes for the patch. We will apply this shortly.

**Comment by agserm** [comment]
We have applied this change in 73280cb.
