### ISSUE TITLE
FindGObject2.cmake and cmake 3.28.5

### ISSUE THREAD

**Issue by e-mattes** [copperspice/copperspice#293]
When using cmake 3.28.5 for building CopperSpice 1.9.1, I get this warning:

CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (GOBJECT2)
  does not match the name of the calling package (GObject2).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindGObject2.cmake:62 (find_package_handle_standard_args)
  CMakeLists.txt:493 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

and this error message:

-- Could NOT find GOBJECT2 (missing: NAME_MISMATCHED) 

This patch fixes the problem, but I don't know whether/how it affects cmake 3.17 through 3.27:

[cmake.zip](https://github.com/user-attachments/files/16596371/cmake.zip)

**Comment by bgeller** [comment]
Thanks for this information! 

The current CMake policy in CopperSpice supports 3.16 though 3.23, we have not tested with some of the newer versions. We are in the process of dropping support for older versions of Ubuntu and Debian which will make it easier to support newer versions of CMake in our next release.

Barbara

**Comment by bgeller** [comment]
We have replicated the problem you brought to our attention.  There was a slightly better fix which works with more versions of CMake.  We are in the process of testing on CI and will push a commit shortly.

**Comment by agserm** [comment]
Thanks for reporting this. Our fix has now been applied in 2f6bce3.
