### ISSUE TITLE
build.ninja not linking against libGL.so on Linux

### ISSUE THREAD

**Issue by e-mattes** [copperspice/copperspice#294]
At least with cmake 3.16.7 and 3.28.5, the generated build.ninja file for CopperSpice 1.9.1 on Linux fails to link against libGL.so. This happens at least on Debian stretch and on Gentoo Linux.

This time, I don't have a patch as I opted for fixing the resulting build.ninja file with sed.

**Comment by agserm** [comment]
We discontinued support for Debian 9 in early 2023, however I was able to check the binaries on GitHub for version 1.8.1 and the CsOpenGL library is linked with libGL.so.  I checked version 1.8.1 for debian 10, and it links with libOpenGL.so.

Support for Debian 10 may be discontinued soon, since it is no longer supported by Debian. Our suggestion is to build with Debian 11 using the vendor version of CMake 3.18, and the build process should automatically link with libOpenGL.so.

**Comment by e-mattes** [comment]
I tried Debian 11 with its cmake 3.18.4: the generated build.ninja file doesn't link against libGL.so.

**Comment by bgeller** [comment]
CMake is responsible for finding and linking with the platform OpenGL library. This is not something which is normally specified manually. As we mentioned, when we build on Debian 11 with CMake 3.18 the  libOpenGL.so library is used, not libGL.so.

Are you using our exact build files? Or did you make changes to anything? 

Barbara

**Comment by e-mattes** [comment]
For me, CMake 3.18.4 on Debian 11 doesn't link against libOpenGL.so or libGL.so. Here's what I do:

mkdir cs_build
cd cs_build
CXX=clang++ \
CC=clang \
CXXFLAGS='-stdlib=libc++' \
LDFLAGS='-stdlib=libc++' \
cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug \
	-DCMAKE_INSTALL_PREFIX=/u/temp/copperspice-debian11 \
	-DWITH_WEBKIT=NO -DWITH_NETWORK=NO -DWITH_OPENGL=NO -DWITH_SCRIPT=NO \
	-DWITH_MULTIMEDIA=NO -DWITH_XMLPATTERNS=NO \
	-DWITH_SQL=NO -DWITH_PSQL_PLUGIN=NO -DWITH_MYSQL_PLUGIN=NO \
	-DWITH_ODBC_PLUGIN=NO \
	..
ninja

Note -DWITH_OPENGL=NO! Perhaps that's the problem: libGL.so is needed even with WITH_OPENGL=NO.

**Comment by bgeller** [comment]
Your original message implied that your project needed to link with OpenGL or GL.  Do you actually want to build CS with this feature turned off?  This is a different issue and I am glad we now understand what you want. 

We will have someone on the CS team test this combination.

Barbara

**Comment by e-mattes** [comment]
With -DWITH_OPENGL=NO I get undefined symbols for linking libCsGui1.9.so (Debian 11, Ninja):

glMatrixMode
glLoadIdentity
glOrtho
glLoadMatrixf
glViewport
glTexSubImage2D
glTexParameteriv
glTexParameteri
glTexParameterfv
glTexParameterf
glTexImage2D
glStencilOp
glStencilMask
glStencilFunc
glScissor
glReadPixels
glPolygonOffset
glPixelStorei
glLineWidth
glIsTexture

**Comment by agserm** [comment]
We have a change we would like you to try.

1) Open the root CMakeLists.txt file.
2) Change line 570 in the root CMakeLists.txt file from `if (WITH_OPENGL)` to `if (WITH_GUI)`
3) Test if CsGui links with this change

**Comment by e-mattes** [comment]
That change fixes the problem. Thanks! Tested on Debian 11.

**Comment by agserm** [comment]
Thanks for testing, the fix will be in our next release.
