### ISSUE TITLE
Use CopperSpice with Meson

### ISSUE THREAD

**Issue by vmz9poa5** [copperspice/copperspice#298]
Meson has support for Qt. The support for compiling .ui files, resources files, and translations files could be reused. But the problem is the Qt module of Meson requires Qmake. It seems you will need to submit your own CopperSpice module to Meson.

**Comment by bgeller** [comment]
The CopperSpice project provides full support for the CMake build system. If you need support for Meson you can either submit a pull request or our team can provide a quote for the necessary consulting work.

Barbara
