### ISSUE TITLE
Can you add support for illumos and Solaris?

### ISSUE THREAD

**Issue by vmz9poa5** [copperspice/copperspice#299]
Defined by both illumos and Solaris: `sun` and `__sun`. Defined only by illumos: `__illumos__`.

Solaris is a closed source crap. illumos support alone is enough for me.

**Comment by bgeller** [comment]
The CS team is focused on supporting the most common operating systems. As you mentioned, Solaris is closed source and we have no current plans to support it. 

If you need us to add custom support for a an open source Solaris compatible platform we can provide a quote for the necessary consulting work.

**Comment by vmz9poa5** [comment]
> The CS team is focused on supporting the most common operating systems. As you mentioned, Solaris is closed source and we have no current plans to support it.
> 
> If you need us to add custom support for a an open source Solaris compatible platform we can provide a quote for the necessary consulting work.

Is it that serious? illumos is just another Unix platform. Just add `__illumos__` to the ifdefs in source code alongside `__linux__` and `__FreeBSD__`, and modify the CMake scripts to include `illumos` after `Linux|OpenBSD|FreeBSD|NetBSD|DragonFly`. No new code is required.

**Comment by bgeller** [comment]
> No new code is required

Just to be clear, any modifications to an ifdef is in fact a change to the code base. We do agree the changes you are suggesting are small. 

Please submit a pull request and we will review the changes.  We need to know the exact distribution you are using for testing.  We may not release pre-built binary files for this platform. 

Barbara

**Comment by bgeller** [comment]
** For anyone reading this thread. 

There are at least 40 different CMake files and Source files which would need to be modified to add support for the illumos platform.  The CopperSpice team is happy to assist with the process.
