### ISSUE TITLE
Does CopperSpice support DBus Adaptor?

### ISSUE THREAD

**Issue by ghost** [copperspice/copperspice#302]
_[ Links to LGPL 3 software removed ]_

Refer to usingadaptors html

**Comment by vmz9poa5** [comment]
Example usage:

https://github.com/tsujan/FeatherPad/blob/8f76debb826afda6268f7151ecff6f1e3ee4b401/featherpad/CMakeLists.txt#L114

**Comment by bgeller** [comment]
CopperSpice does not support DBus at this time, however it is on our roadmap. If you would like to contribute to this work please let us know.

Barbara
