### ISSUE TITLE
Please provide binary build for FreeBSD 14

### ISSUE THREAD

**Issue by chatchoi** [copperspice/copperspice#305]
I'm using: FreeBSD 14.1-RELEASE-p2 amd64. There are only FreeBSD 13 builds available.

**Comment by bgeller** [comment]
We can only provide a certain number of release builds. If you are unable to build CS for FreeBSD 14 you may want to consider a support subscription.  

Have you tried to build CopperSpice for FreeBSD 14? If you did and there were issues, please let us know what you found. We are happy to work with you. 

Barbara

**Comment by chatchoi** [comment]
If I don't use parallel build, I think it's no problem to build CopperSpice. The only constraint is time. My computer is not powerful, I afraid I can't wait the build of CopperSpice to complete. Btw, I'm only a high school student.

**Comment by agserm** [comment]
> If I don't use parallel build, I think it's no problem to build CopperSpice.

The CopperSpice build system supports parallel builds, can you tell us what happened when you tried to do so?

**Comment by chatchoi** [comment]
> > If I don't use parallel build, I think it's no problem to build CopperSpice.
> 
> The CopperSpice build system supports parallel builds, can you tell us what happened when you tried to do so?

Out of memory. My PC is old with only 4GB of RAM.

**Comment by agserm** [comment]
A system with only 4GB is too underpowered to compile any substantial C++ project. This includes CopperSpice. You will need to upgrade your hardware if you want to build modern software.

A machine with this little memory will also make it appear like everything runs very slowly.
