### ISSUE TITLE
A trimmed-down CopperSpice?

### ISSUE THREAD

**Issue by mh466lfa** [copperspice/copperspice#316]
Currently, libCsGui1.9.dll is 108MB in size. I have the impression that Qt DLLs are much lighter. I don't know why CopperSpice DLLs are that bloated. But I got an idea from the LeanQt project (https://github.com/rochus-keller/LeanQt). What do you think about a trimmed-down version of CopperSpice?

I'm pretty interested in LeanQt. But the developer is very annoying. First, his BUSY build system doesn't support parallel builds. Second, he refused to integral new patches from upstream, including security patches, making his fork a security nightmare. LeanQt currently doesn't compile on Windows with MinGW because a bug that CopperSpice and Qt have fixed a long time ago.

**Comment by chatchoi** [comment]
Believe me or not, Qt with MinGW will always explode in size. I have plenty of time, and I have tried all major Qt versions in the 5 and 6 series. The small DLL you see is compiled using MSVC. You can try running strip --strip-all on the CopperSpice DLL.
