### ISSUE TITLE
InstallMinGW.cmake and fully static GCC distros

### ISSUE THREAD

**Issue by chatchoi** [copperspice/copperspice#327]
GCC distros like w64devkit and equation.com's are fully static. They don't provide shared libraries. This CMake script will not work.

**Comment by janwilmans** [comment]
It is currently not possible to build Copperspice without using dynamic libraries.

**Comment by bgeller** [comment]
It is true that CopperSpice must be built as dynamic libraries, however this is completely unrelated to the GCC runtime libraries being built statically.  As per our CS documentation we have a list of supported platforms, operating systems, and compilers.  

The distribution you mentioned is not on our supported list of compilers for Windows. You are free try it, however we are not using this one in our CI so it may not work.  If you are interested in enhancing the CopperSpice CMake build process, we do accept pull requests.
