### ISSUE TITLE
copperspice-1.3.0 does not compile on fedora 24 beta (gcc 6.0)

### ISSUE THREAD

**Issue by zuzzurro** [copperspice/copperspice#50]
libtool: compile:  g++ -DHAVE_CONFIG_H -DQT_SHARED -DQT_NO_CUPS -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I./src/3rdparty/zlib -Iinclude -Iinclude/QtCore -Iprivateinclude/QtCore -Iprivateinclude/QtCore/private -I./src/core/io -Isrc/core/animation -Isrc/core/kernel -Isrc/core/io -Isrc/core/statemachine -I./src/3rdparty/harfbuzz/src -DBUILD_DATE=\"2016-05-12\" -DQT_BUILD_CORE_LIB -DBUILDING_LIB_CS_SIGNAL -DQT_SHARED -DQT_MAKEDLL -I./src/3rdparty/zlib -g -O2 -MT src/core/io/lib_libCsCore1_la-qstandardpaths.lo -MD -MP -MF src/core/io/.deps/lib_libCsCore1_la-qstandardpaths.Tpo -c src/core/io/qstandardpaths.cpp  -fPIC -DPIC -o src/core/io/.libs/lib_libCsCore1_la-qstandardpaths.o
In file included from include/QtCore/cs_signal.h:27:0,
                 from include/QtCore/csobject_macro.h:29,
                 from include/QtCore/qobject.h:29,
                 from include/QtCore/qiodevice.h:29,
                 from include/QtCore/qdatastream.h:30,
                 from include/QtCore/qstringlist.h:30,
                 from include/QtCore/qstandardpaths.h:29,
                 from src/core/io/qstandardpaths.cpp:26:
include/QtCore/cs_internal.h: In instantiation of ‘std::unique_ptrCsSignal::Internal::BentoAbstract CsSignal::Internal::Bento<MethodReturn (MethodClass::*)(MethodArgs ...)>::clone() const [with MethodClass = QObject; MethodReturn = void; MethodArgs = {QList<std::pair<int, int> >}]’:
src/core/io/qstandardpaths.cpp:518:1:   required from here
include/QtCore/cs_internal.h:651:74: error: call of overloaded ‘make_unique(const CsSignal::Internal::Bento<void (QObject::*)(QList<std::pair<int, int> >)>&)’ is ambiguous
    return make_unique<Bento<MethodReturn(MethodClass::*)(MethodArgs...)>>(_this);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
include/QtCore/cs_internal.h:112:20: note: candidate: std::unique_ptr<_Tp> CsSignal::Internal::make_unique(Args&& ...) [with T = CsSignal::Internal::Bento<void (QObject::_)(QList<std::pair<int, int> >)>; Args = {const CsSignal::Internal::Bento<void (QObject::*)(QList<std::pair<int, int> >)>&}]
 std::unique_ptr<T> make_unique(Args &&... args) {
                    ^~~~~~~~~~~
In file included from /usr/include/c++/6.0.0/memory:81:0,
                 from /usr/include/c++/6.0.0/thread:40,
                 from include/QtCore/cs_signal.h:21,
                 from include/QtCore/csobject_macro.h:29,
                 from include/QtCore/qobject.h:29,
                 from include/QtCore/qiodevice.h:29,
                 from include/QtCore/qdatastream.h:30,
                 from include/QtCore/qstringlist.h:30,
                 from include/QtCore/qstandardpaths.h:29,
                 from src/core/io/qstandardpaths.cpp:26:
/usr/include/c++/6.0.0/bits/unique_ptr.h:786:5: note: candidate: typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = CsSignal::Internal::Bento<void (QObject::*)(QList<std::pair<int, int> >)>; _Args = {const CsSignal::Internal::Bento<void (QObject::*)(QList<std::pair<int, int> >)>&}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<CsSignal::Internal::Bento<void (QObject::*)(QList<std::pair<int, int> >)>, std::default_delete<CsSignal::Internal::Bento<void (QObject::*)(QList<std::pair<int, int> >)> > >]
     make_unique(_Args&&... __args)

**Comment by agserm** [comment]
Thank you for your bug report. We will investigate this as soon as possible. Currently this version of GCC is not in our CI suite. It will be added in the next week or so.

**Comment by agserm** [comment]
Closing this ticket since Fedora 24 is no longer supported.
