### ISSUE TITLE
libcsguixx

### ISSUE THREAD

**Issue by topillar** [copperspice/copperspice#52]
the binary libcsguixx.dll on Windows is more than 50M, that is too big. is that normal?

**Comment by topillar** [comment]
the binary libcsguixx.dll on Windows is more than 50M, that is too big. is that normal?

**Comment by agserm** [comment]
This is not an unusual size for a Windows DLL. For example, the libClang DLL we are using is around 45M. The size of a Windows DLL is not indicative of the performance.

The way some projects handle this is by separating functionality into smaller DLLs. Then you have to link a larger number of files into your project, which can result in pretty much the same thing.

We are however in the process of refactoring the Core and GUI libraries to simplify the code and one benefit will be reduced size.
