### ISSUE TITLE
Wont compile on Fedora 28 RPC problem

### ISSUE THREAD

**Issue by ghost** [copperspice/copperspice#70]
It appears Fedora 28 has moved away from <rpc/rpc.h> (Sun gcc rpc) to a independent release called <rpc2/rpc2.h>.  Simply modifying the effect line from <rpc/rpc.h> to <rpc2/rpc2.h> will not work, causing new errors.  While I am still investigating a solution possibly someone is aware of a fix.
src/gui/dialogs/.deps/lib_libCsGui1.4_la-qprintdialog_unix.Tpo -c src/gui/dialogs/qprintdialog_unix.cpp  -fPIC -DPIC -o src/gui/dialogs/.libs/lib_libCsGui1.4_la-qprintdialog_unix.o
In file included from src/gui/dialogs/qprintdialog_unix.cpp:51:
privateinclude/QtGui/private/qprinterinfo_unix_p.h:32:12: fatal error: rpc/rpc.h: No such file or directory
 #  include <rpc/rpc.h>
            ^~~~~~~~~~~

**Comment by agserm** [comment]
Our current supported releases of Fedora are 24, 25, and 26. We are in the process of upgrading our CI systems to track more current distributions. Thanks for the heads up.

**Comment by chrislrobson** [comment]
Status so far with rebuilding for Fedora 28.  This has NOT been runtime tested yet ONLY compiled error free.
1.  RPC(Sun version) is replaced witth TIRPC.  To use TIRPC the file ./src/gui/painting/qprinterinfo_unix_p.h is edited changing line to #include <tirpc/rpc/rpc.h>
2.  Install rpcsvc rpm and edit ./src/gui/painting/qprinterinfo_unix_p.h again to #include <rpcsvc/ypclnt.h> and next line to #include <rpcsvc/yp_prot.h>
3.  ./configure --disable-openssl CPPFLAGS='-I/usr/include/tirpc -I/usr/include/rpcsvc' has to be run.  Openssl causes compiler errors, so need to look into why.

**Comment by agserm** [comment]
Thanks so much for the additional information. Fedora 27 was successfully added to CI, and I am starting work on Fedora 28. I will update the ticket as the process continues.

**Comment by agserm** [comment]
We have built successfully on Fedora 28 and added it to our CI. You can find the full information about the build requirements for all unix platforms at http://www.copperspice.com/docs/cs_overview/requirements-unix.html#required-packages

The notable changes from Fedora 27 to 28 are the requirement to install the libtirpc-devel and libnsl2-devel packages, and to pass additional arguments to configure so that these libraries are detected and used.

Can you confirm that these steps resolve the build issues on your system?

**Comment by chrislrobson** [comment]
Ansel

The good news is, KitchenSink built and ran just fine on my Fedora 28 
system.  Now can it build my Testbed Tester CMS system, that's the real 
test.

The bad news for me is, Copperspice built on a fresh built Fedora 28 
system to include OpenSSL.  So obviously the Fedora 28 system I have 
been using has some issues.  A quick check shows the problem Fedora 28 
system as some 3rdparty OpenSSL libraries.  So its elimination time to 
find the bad guy.

Anyway, well let you know what I find........Chris

**Comment by agserm** [comment]
Glad to hear that with the additional libraries you were able to get further. If you want to work with us on any of the other build issues you are encountering on your Fedora system, whether CopperSpice related or not, we are glad to help in any way we can.

**Comment by chrislrobson** [comment]
The bad guy is openssl-devel.  Uninstalling (dnf remove openssl-devel) 
solved the problem.

I would love to work with the Copperspice effort.  Let  me know if there 
are any other testing needed.

So the next step with the current effort is to find the MySQL issue.  
Both MySQL and MariaDB are installed which is probably why it wont 
configure.

l8r

Chris

**Comment by agserm** [comment]
Thanks for your continued work on this, and we will work with you to get CopperSpice building on your platform with your applications. One of the other areas which needs to be tested, if you are interested, is the CMake build. We are particularly interested in finding out if the CMake build and CPack can generate RPM packages which work and make sense for Fedora systems.

**Comment by chrislrobson** [comment]
Ansel

Sure I'll start poking around with CMake/CPack testing.

As an update, the OpenSSL issue actual didnt get resolved, I need to 
look a little deeper into that problem.  Will update later.

Chris

**Comment by agserm** [comment]
Closing since it sounds like this issue was resolved as of your message on Jul 8th. Please let us know of any further questions.

**Comment by scottfurry** [comment]
Please clarify status? [Fedora Changes](https://fedoraproject.org/wiki/Changes/SunRPCRemoval) indicates libtirpc is to be used. Are changes to CMake/autotools required to detect package? Is libtirpc now a dependency?

**Comment by agserm** [comment]
Recent changes to our CMake configuration and the implementation of the printing system have resolved this issue. Thank you for your report, and if there are any further issues let us know.
