### ISSUE TITLE
How is this project?

### ISSUE THREAD

**Issue by topillar** [copperspice/copperspice#71]
The latest commit is on March. where is this project now? pls keep it on going.

**Comment by bgeller** [comment]
Thank you so much for the wonderful feedback. Please know the project is moving forward and a good deal of work has been done in the last three months.  The project was in flux and pushing changes was difficult. All new changes will be pushed and new binary files and API documentation will be available by the end of June. 

We are in the last round of integrating the CsString library into CopperSpice.  This will add full Unicode aware strings to the Core library.  

- QString (typedef for QString8) supports UTF-8 and QString16 uses UTF-16 encoding. 
- QStringParser class was added with fully redesigned methods like number(), split(), arg()
- A brand new QRegularExpression class has been added with enhanced features
- JSON classes were modified to use the new QString classes
- Multiple internal and obsolete string classes in areas like json and xml classes were removed
- Codec classes were improved to use the new UTF-8 string classes

There are a lot more changes and we are very excited with our pending release.  Thanks for your patience.

Barbara

**Comment by topillar** [comment]
Nice ！
