### ISSUE TITLE
QDockWidget not scaling to fill parent

### ISSUE THREAD

**Issue by ghost** [copperspice/copperspice#75]
When there's only a single QDockWidget under centralWidget, it should scale itself to cover the area but it doesn't. The following code does the right thing in Qt v5.11.2 but fails in CS v1.5

```
#include <QtGui/QApplication>
#include <QtGui/QMainWindow>
#include <QtGui/QDockWidget>

#include <Windows.h>

int APIENTRY WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, PSTR lpCmdLine, INT nCmdShow)
{
  QApplication a(__argc, __argv);

  QMainWindow mw;
  mw.setDockOptions(QMainWindow::AllowNestedDocks | QMainWindow::AllowTabbedDocks);

  mw.setCentralWidget(new QWidget);
  mw.centralWidget()->setMaximumSize(0, 0);

  auto d1 = new QDockWidget("Foo");

  // Paint the background so we can identify the widget boundaries.
  d1->setAutoFillBackground(true);
  QPalette p(d1->palette());
  p.setColor(QPalette::Background, Qt::red);
  d1->setPalette(p);

  d1->setAllowedAreas(Qt::TopDockWidgetArea);
  mw.addDockWidget(Qt::TopDockWidgetArea, d1);

  mw.showMaximized();
  return a.exec();
}
```

**Comment by de1001** [comment]
Any stop gap solution to fix this problem? This issue is blocking our progress. I tried reproducing the issue in Qt 4.8 as well but looks like it is specific to CS.

**Comment by agserm** [comment]
Thanks for the detailed bug reports and the test cases. This current report with QDockWidget was not a known issue, so I don't know a workaround as of yet. We are currently finishing up a prior commitment and will be able to devote more time to your specific issues next week.

Thanks for your patience.

**Comment by de1001** [comment]
Any update on this?

**Comment by agserm** [comment]
We are finishing up some changes with the text system as we are currently integrating unicode 11. We will be done with that shortly, and we will then address this issue.
