### ISSUE TITLE
CopperSpice failed to build with error C1061 on x64 when build with MSVC

### ISSUE THREAD

**Issue by spacelg** [copperspice/copperspice#79]
Describe the problem:
CopperSpice failed to build with error C1061 on x64 when build with MSVC. This issue can be reproduced from the cs-1.5 revision 8f610ef. We found that when we compile the D:\CopperSpice\src\src\core\string\qchar32.cpp file, we generate error C1061:compiler limit: blocks nested too deeply. I think #include "../tools/qunicodetables.cpp" in qchar32.cpp will cause this error .This should be copperspice source issue, could you please help take a look at this? Thanks!

The failures like:
 The whole log file please see attachment.
[log_x64_build.zip](https://github.com/copperspice/copperspice/files/2579393/log_x64_build.zip)

Repro steps:
1. git clone https://github.com/copperspice/copperspice D:\CopperSpice\src
2. Open a VS 2017 x64 command prompt as admin and browse to D:\CopperSpice
3. mkdir build_x64 && pushd build_x64
4. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0  ..\src\
5. msbuild /m /p:Configuration=Release;Platform=x64 copperspice.sln /t:Rebuild

Build Message:
28>D:\CopperSpice\src\src\core\tools\qunicodetables.cpp(9155,29): error C1061:  compiler limit: blocks nested too deeply [D:\CopperSpice\build_x64\src\core\CsCore1.5.vcxproj]
D:\CopperSpice\src\src\core\tools\qunicodetables.cpp(9155,29): error C1061:     } else if (value < 369) { [D:\CopperSpice\build_x64\src\core\CsCore1.5.vcxproj]
D:\CopperSpice\src\src\core\tools\qunicodetables.cpp(9155,29): error C1061:                             ^ [D:\CopperSpice\build_x64\src\core\CsCore1.5.vcxproj]

**Comment by agserm** [comment]
Thank you for your report and the detailed build log. We will look into this issue and let you know what we discover. Do you know if there is a way to override this limit? This is generated code and would be awkward and inefficient to split into smaller functions. So far in our initial testing neither GCC, MinGW or Clang reports errors on this code.

**Comment by spacelg** [comment]
Thanks for your feedback. We don't know how to override this limit. If you have any discover please let me know.

**Comment by spacelg** [comment]
Thanks for your feedback. We verified this issue has been fixed in 90f1b43. So close it.

**Comment by spacelg** [comment]
CopperSpice failed to build with error C1061 on x64 when build with MSVC again. This issue can be reproduced from the cs-1.5 latest revision 7b88678 .When we compile the D:\CopperSpice\src\src\core\string\qchar32.cpp file, we generate error C1061:compiler limit: blocks nested too deeply. could you please help take a look at this? Thanks!

**Comment by agserm** [comment]
Oops. it looks like we generated the unicode tables from the wrong script. Try the latest commit in 2081cf2.

**Comment by agserm** [comment]
Closing this ticket due to no response. Please reopen if the problem still exists.
