### ISSUE TITLE
correct missing rpc.h

### ISSUE THREAD

**Issue by scottfurry** [copperspice/copperspice#83]
As noted at [Fedora](https://fedoraproject.org/wiki/Changes/SunRPCRemoval), SunRPC was removed from glibc. A replacement package to install Transport Independent rpc is available as libtirpc.

Attached diff (inside zip - no thanks to github) shows changes necessary to build CopperSpice from sources. This creates a dependency on libtirpc but no allowances have been made for reverse compatibility or MacOS/BSD. From [libtirpc Repology information page](https://repology.org/metapackage/libtirpc/versions), libtiprc has not yet been incorporated into some linux or BSD distributions yet. But this is the basics I could sort out to get the library to build.

[tirpc.diff.zip](https://github.com/copperspice/copperspice/files/2683235/tirpc.diff.zip)

**Comment by agserm** [comment]
Thanks for the contribution! I will take a look and see how we can integrate these changes while maintaining cross platform build compatibility.

**Comment by scottfurry** [comment]
[localchanges.diff.zip](https://github.com/copperspice/copperspice/files/2704889/localchanges.diff.zip)
Updating contributed diff file. Original zip uploaded was missing FindLIBTIRPC.cmake file in [cs root]/cmake/modules/ folder. This upload corrects this oversight.

**Comment by agserm** [comment]
Thanks for the updated information. We will be back on a regular schedule at the end of next week and we will be taking a look at this as soon as we can.

**Comment by agserm** [comment]
Recent changes to our CMake configuration and the implementation of the printing system have resolved this issue. Thank you for your report, and if there are any further issues let us know.
