### ISSUE TITLE
CopperSpice failed to build with error C2429 on x64 when build with MSVC

### ISSUE THREAD

**Issue by spacelg** [copperspice/copperspice#84]
Describe the problem:
 CopperSpice failed to build with error C2429 on x64 when build with MSVC. This issue can be reproduced from the cs-1.5 revision 63cb2f3. We reproduce this issue when we compile the "D:\CopperSpice\src\src\3rdparty\harfbuzz\src\harfbuzz-shaper-all.cpp", it generated error C2429:  language feature 'terse static assert' requires compiler flag '/std:c++17'.  When we replace /std:c++14 in the compile command with /std:c++17, it can be compiled  pass. This should be copperspice source issue, could you please help take a look at this? Thanks!

The failures like:
 The whole log file please see attachment.
[log_x64_build.log](https://github.com/copperspice/copperspice/files/2693586/log_x64_build.log)

Repro steps:
1.git clone https://github.com/copperspice/copperspice D:\CopperSpice\src
2.Open a VS 2017 x64 command prompt as admin and browse to D:\CopperSpice
3.mkdir build_x64 && pushd build_x64
4.cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src\
5.msbuild /m /p:Configuration=Release;Platform=x64 copperspice.sln /t:Rebuild

Build Message:
28>D:\CopperSpice\src\src\3rdparty\harfbuzz\src\harfbuzz-shaper.cpp(979,84): error C2429:  language feature 'terse static assert' requires compiler flag '/std:c++17' [D:\CopperSpice\build_x64\src\core\CsCore1.5.vcxproj]
D:\CopperSpice\src\src\3rdparty\harfbuzz\src\harfbuzz-shaper.cpp(979,84): error C2429: static_assert( (sizeof(HB_ScriptEngines)/sizeof(HB_ScriptEngine)) == HB_ScriptCount);

**Comment by agserm** [comment]
Thank you for reporting this. The issue should be resolved by fad5c15. Can you please test and verify?

**Comment by agserm** [comment]
Closing this ticket due to no response. Please reopen if the problem still exists.
