### ISSUE TITLE
msvc build fails on hash a71a0d5  (only if zlib is _found_ on windows, which is very rare)

### ISSUE THREAD

**Issue by janwilmans** [copperspice/copperspice#86]
a71a0d59993d520abb136ac32f1fcdd9a73f3d4b failed to build on msvc due to:

copperspice\src\core\tools\qbytearray.cpp(32): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory

* this happens only when using the 'Open Folder' method of building and zlib **is found** by cmake (which is kindof rare, unless you have it installed using for example vcpkg), I was able to compile fine on a different machine 
* it happens both with vs2017 and vs2019

```
 [73/3498] C:\PROGRA~2\MIB055~1\2019\Preview\VC\Tools\MSVC\1420~1.273\bin\HostX64\x64\cl.exe  /nologo /TP   @src\core\CMakeFiles\CsCore1.5.dir\tools\qbytearray.cpp.obj.rsp /showIncludes /Fosrc\core\CMakeFiles\CsCore1.5.dir\tools\qbytearray.cpp.obj /Fdsrc\core\CMakeFiles\CsCore1.5.dir\ /FS -c C:\project\copperspice\src\core\tools\qbytearray.cpp
  FAILED: src/core/CMakeFiles/CsCore1.5.dir/tools/qbytearray.cpp.obj 
  C:\PROGRA~2\MIB055~1\2019\Preview\VC\Tools\MSVC\1420~1.273\bin\HostX64\x64\cl.exe  /nologo /TP   @src\core\CMakeFiles\CsCore1.5.dir\tools\qbytearray.cpp.obj.rsp /showIncludes /Fosrc\core\CMakeFiles\CsCore1.5.dir\tools\qbytearray.cpp.obj /Fdsrc\core\CMakeFiles\CsCore1.5.dir\ /FS -c C:\project\copperspice\src\core\tools\qbytearray.cpp
C:\project\cl : Command line warning D9025: overriding '/W3' with '/w'
C:\project\copperspice\src\core\tools\qbytearray.cpp(32): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory

```

**Comment by agserm** [comment]
@janwilmans, can you check if this issue still exists? I'm pretty sure this has been resolved.

**Comment by janwilmans** [comment]
I will check it. Note that this was never about easy of use at the labels might indicate. 
I think the trigger for this was: the combination of using MSVC compiler + zlib being _found_. (normally never happens, because zlib is normally never available on windows)

**Comment by bgeller** [comment]
We are in the process of updating all the CMake build files and this may no longer be an issue for you.

**Comment by bgeller** [comment]
This should have been resolved with the changes in our CMake files.  Please reopen this issue if there is still a problem.
