### ISSUE TITLE
incorrect linker flags during msvc build

### ISSUE THREAD

**Issue by janwilmans** [copperspice/copperspice#87]
the msvc linked doesn't understand /Wl,--no-undefined and friends, so we should not pass them 

'''
[249/3493] Linking CXX shared library bin\CsCore1.5.dll
LINK : warning LNK4044: unrecognized option '/Wl,--no-undefined'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-luuid'; ignored
   Creating library lib\CsCore1.5.lib and object lib\CsCore1.5.exp
LINK : warning LNK4044: unrecognized option '/Wl,--no-undefined'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,-luuid'; ignored
[300/3493] Linking CXX shared library bin\CsNetwork1.5.dll
LINK : warning LNK4044: unrecognized option '/Wl,--no-undefined'; ignored
   Creating library lib\CsNetwork1.5.lib and object lib\CsNetwork1.5.exp
LINK : warning LNK4044: unrecognized option '/Wl,--no-undefined'; ignored
'''

**Comment by bgeller** [comment]
Closing, should be resolved in CS 1.6.0.
