### ISSUE TITLE
consider detection of the gold linker

### ISSUE THREAD

**Issue by janwilmans** [copperspice/copperspice#88]
https://en.wikipedia.org/wiki/Gold_(linker)
http://www.bitsnbites.eu/faster-c-builds/

'''
if (UNIX AND NOT APPLE)
  execute_process(COMMAND ${CMAKE_C_COMPILER} -fuse-ld=gold -Wl,--version ERROR_QUIET OUTPUT_VARIABLE ld_version)
  if ("${ld_version}" MATCHES "GNU gold")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fuse-ld=gold -Wl,--disable-new-dtags")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fuse-ld=gold -Wl,--disable-new-dtags")
  endif()
endif()
'''

**Comment by bgeller** [comment]
Specifying a particular linker in the CopperSpice build files would be restrictive and hard to maintain.  We would like to give users the freedom to use the linker of their choice.
