### ISSUE TITLE
CMAKE

### ISSUE THREAD

**Issue by pip010** [copperspice/copperspice#9]
Any chance of adopting the only true cross-platform build solution: cmake.org ???
then this message will be gone:
"
Note: Windows does not provide a Bourne shell as a standard component. In order to build CopperSpice a shell program is required to run the configure scripts. This is installed as part of the MSYS project.
"

one should not require mingw but the native win toolchain.

**Comment by mortaromarcello** [comment]
I.e. MSVC? But it is not an open source project.

**Comment by pip010** [comment]
Yes, but MSVC is used even for OSS projects.
Clang/llvm might be coming native for win but mingw is hardly matured for win :)
In fact even for Linux I might want to use different toolchain than GNU and cmake makes it easy and transparent !

**Comment by mortaromarcello** [comment]
@pip010, https://github.com/fluxer has a fork with cmake   integrated.

**Comment by fluxer** [comment]
@pip010 Keep in mind that it's work in progress.

**Comment by pip010** [comment]
thanks guys, will have a look.

**Comment by markand** [comment]
Yeah I was also surprised when I saw that CopperSpice has selected deprecated autotools for a modern project targetting modern C++11. Switching to CMake would be a very great benefit.

**Comment by ahmedcharles** [comment]
@agserm I believe this can be closed now.
