### ISSUE TITLE
The cmake files could be improved

### ISSUE THREAD

**Issue by janwilmans** [copperspice/copperspice#91]
if we're updating to C++17, we should also consider updating to Cmake 3.12? (todo: check what version is generally available at that time)

* add_dependencies and include_directories should not be used anymore (that is old-cmake)

instead we should use target_link_libraries and target_include_directories
also, the current top-level cmake file assumes its always top-level, which means it does not allow you to make copperspice part of a larger build

**Comment by bgeller** [comment]
Closing since this ticket has been superseded by #111.
